-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\HomelandPlacement\\HomelandPlacementView.lua

local logger = require("Core.Log.LoggerManager").getLogger("InteractSecondView")
local Class = require("Core.Framework.Class")
local UIView = require("Guis.UIView")
local HomelandPlacementView = Class.LightClass("HomelandPlacementView", UIView)

function HomelandPlacementView:findObjects()
	self.objectReference = self.transform:GetComponent("ObjectReference")
	self.btnBack = self.objectReference:GetRefValue("btnBack")
	self.simpleViewCtrl = self.objectReference:GetRefValue("viewCtrl")
	self.objectEditRoot = self.objectReference:GetRefValue("objectEditRoot"):GetComponent("USimplePosFollow")
	self.undoBtn = self.objectReference:GetRefValue("undoBtn")
	self.redoBtn = self.objectReference:GetRefValue("redoBtn")
	self.confirmBtn = self.objectReference:GetRefValue("confirmBtn")
	self.cancelBtn = self.objectReference:GetRefValue("cancelBtn")
	self.withdrawBtn = self.objectReference:GetRefValue("withdrawBtn")
	self.undoBtnHotKeyContent = self.objectReference:GetRefValue("undoBtnHotKeyContent")
	self.redoBtnHotKeyContent = self.objectReference:GetRefValue("redoBtnHotKeyContent")
	self.okBtnHotKeyContent = self.objectReference:GetRefValue("okBtnHotKeyContent")
	self.noBtnHotKeyContent = self.objectReference:GetRefValue("noBtnHotKeyContent")
	self.recycleBtnHotKeyContent = self.objectReference:GetRefValue("recycleBtnHotKeyContent")
	self.tabBtnGridUButton = self.objectReference:GetRefValue("tabBtnGridUButton")
	self.widgetPrompt = self.objectReference:GetRefValue("widgetPrompt")
	self.warningUContainer = self.objectReference:GetRefValue("warningUContainer")
	self.listCurrencyUList = self.objectReference:GetRefValue("listCurrencyUList")
	self.globalEditingUWidget = self.objectReference:GetRefValue("globalEditingUWidget")
	self.operateMobileUContainer = self.objectReference:GetRefValue("operateMobileUContainer")
	self.uIPbHomePlacementUWidget = self.objectReference:GetRefValue("uIPbHomePlacementUWidget")
	self.tabBarUWidget = self.objectReference:GetRefValue("tabBarUWidget")
	self.stateWidget = self.objectReference:GetRefValue("stateWidget")
	self.btnSaveUButton = self.objectReference:GetRefValue("btnSaveUButton")
	self.txtSaveUSDFText = self.objectReference:GetRefValue("txtSaveUSDFText")
	self.btnDisplayUButton = self.objectReference:GetRefValue("btnDisplayUButton")
	self.selectorMetreUSelector = self.objectReference:GetRefValue("selectorMetreUSelector")
	self.txtCameraHeightUSDFText = self.objectReference:GetRefValue("txtNumUSDFText")
	self.txtMUSDFText = self.objectReference:GetRefValue("txtMUSDFText")
	self.txtDisplayUSDFText = self.objectReference:GetRefValue("txtDisplayUSDFText")
	self.txtMetreUSDFText = self.objectReference:GetRefValue("txtMetreUSDFText")
	self.itemObjectReference = self.objectEditRoot:GetComponent("ObjectReference")
	self.btnWorldItem = self.itemObjectReference:GetRefValue("btnWorldItem")
	self.btnWorldItemSimple = self.itemObjectReference:GetRefValue("btnWorldItemSimple")
	self.btnWorldPet = self.itemObjectReference:GetRefValue("btnWorldPet")
	self.ownedWidget = self.itemObjectReference:GetRefValue("ownedWidget")
	self.ownedText = self.itemObjectReference:GetRefValue("ownedText")
	self.txtNumUSDFText = self.itemObjectReference:GetRefValue("txtNumUSDFText")
	self.iconCurrencyUImage = self.itemObjectReference:GetRefValue("iconCurrencyUImage")
	self.btnAreaUButton = self.objectReference:GetRefValue("btnAreaUButton")
	self.progressUProgress = self.objectReference:GetRefValue("progressUProgress")
end

return HomelandPlacementView
