-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\Nourish\\NourishView.lua

local Class = require("Core.Framework.Class")
local UIView = require("Guis.UIView")
local NourishView = Class.LightClass("NourishView", UIView)

function NourishView:findObjects()
	self.objectReference = self.transform:GetComponent("ObjectReference")
	self.btnBackUButton = self.objectReference:GetRefValue("btnBackUButton")
	self.listCurrencyUList = self.objectReference:GetRefValue("listCurrencyUList")
	self.txtTitleUSDFText = self.objectReference:GetRefValue("txtTitleUSDFText")
	self.txtNumUSDFText = self.objectReference:GetRefValue("txtNumUSDFText")
	self.btnNourishRecoverUButton = self.objectReference:GetRefValue("btnNourishRecoverUButton")
	self.iconUImage = self.objectReference:GetRefValue("iconUImage")
	self.consumeCostNum = self.objectReference:GetRefValue("consumeCostNum")
	self.root = self.objectReference:GetRefValue("root")
	self.btnNourishUButton = self.objectReference:GetRefValue("btnNourishUButton")
	self.niurishDetailsUComponent = self.objectReference:GetRefValue("niurishDetailsUComponent")
	self.windowAnimation = self.objectReference:GetRefValue("windowAnimation")
	self.btnTipsUButton = self.objectReference:GetRefValue("btnTipsUButton")
	self.btnInfoUButton = self.objectReference:GetRefValue("btnInfoUButton")
	self.progressCountDown1 = self.objectReference:GetRefValue("progressCountDown1")
	self.progressCountDown2 = self.objectReference:GetRefValue("progressCountDown2")
	self.progressCountDown3 = self.objectReference:GetRefValue("progressCountDown3")
	self.txtFullUSDFText = self.objectReference:GetRefValue("txtFullUSDFText")
	self.listLeftUList = self.objectReference:GetRefValue("listLeftUList")
	self.listRightUList = self.objectReference:GetRefValue("listRightUList")
	self.listPetUList = self.objectReference:GetRefValue("listPetUList")
	self.lockedTitleTip = self.objectReference:GetRefValue("lockedTitleTip")
	self.txtDetailsUSDFText = self.objectReference:GetRefValue("txtDetailsUSDFText")
	self.btnMapUButton = self.objectReference:GetRefValue("btnMapUButton")
	self.weatherTips = self.objectReference:GetRefValue("weatherTips")
	self.btnWeatherUButton = self.objectReference:GetRefValue("btnWeatherUButton")
	self.weatherIconUImage = self.objectReference:GetRefValue("weatherIconUImage")
	self.weatherTxtNumUSDFText = self.objectReference:GetRefValue("weatherTxtNumUSDFText")
	self.weatherCountDown = self.objectReference:GetRefValue("weatherCountDown")
	self.vXMapCultivateMeshLineRectTransform = self.objectReference:GetRefValue("vXMapCultivateMeshLineRectTransform")
	self.weatherTransform = self.objectReference:GetRefValue("weatherTransform")
	self.btnRulesUButton = self.objectReference:GetRefValue("btnRulesUButton")
	self.iconUp3UContainer = self.objectReference:GetRefValue("iconUp3UContainer")
	self.btnAddPropUButton1 = self.objectReference:GetRefValue("btnAddPropUButton1")
	self.btnCleanUButton1 = self.objectReference:GetRefValue("btnCleanUButton1")
	self.extraIconPropUImage1 = self.objectReference:GetRefValue("extraIconPropUImage1")
	self.extraCount1 = self.objectReference:GetRefValue("extraCount1")
	self.popTransform = self.objectReference:GetRefValue("popTransform")
	self.tributeText = self.objectReference:GetRefValue("tributeText")
	self.addUWidget = self.objectReference:GetRefValue("addUWidget")
	self.txtTipsUSDFText = self.objectReference:GetRefValue("txtTipsUSDFText")
	self.txtProbabilityUSDFText = self.objectReference:GetRefValue("txtProbabilityUSDFText")
	self.cultivateTipsUComponent = self.objectReference:GetRefValue("cultivateTipsUComponent")
	self.progressProbabilityUComponent = self.objectReference:GetRefValue("progressProbabilityUComponent")
	self.txtQualityUSDFText = self.objectReference:GetRefValue("txtQualityUSDFText")
end

function NourishView:initView()
	return
end

return NourishView
