-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\Photo\\PhotoView.lua

local UIView = require("Guis.UIView")
local Class = require("Core.Framework.Class")
local PhotoView = Class.LightClass("PhotoView", UIView)
local LuaUIUtils = require("Utils.LuaUIUtils")
local UIConst = require("Const.UIConst")
local ClientTextUtils = require("Utils.ClientTextUtils")

function PhotoView:findObjects()
	local objectReference = self.transform:GetComponent("ObjectReference")

	self.rootComponent = objectReference:GetRefValue("rootComponent")
	self.animation = objectReference:GetRefValue("animation")
	self.btnCameraMode = objectReference:GetRefValue("btnCameraMode")
	self.btnReset = objectReference:GetRefValue("btnReset")
	self.zoom = objectReference:GetRefValue("zoom")
	self.zoomDec = objectReference:GetRefValue("zoomDec")
	self.zoomAdd = objectReference:GetRefValue("zoomAdd")
	self.zoomTxt = objectReference:GetRefValue("zoomTxt")
	self.joyStickArea = objectReference:GetRefValue("joyStickArea")
	self.boxSlider = objectReference:GetRefValue("boxSlider")
	self.btnJS = objectReference:GetRefValue("btnJS")
	self.joyStick = objectReference:GetRefValue("joyStick")
	self.closeBtn = objectReference:GetRefValue("closeBtn")
	self.keys = objectReference:GetRefValue("keys")
	self.quickCaptureEntry = objectReference:GetRefValue("quickCaptureEntry")
	self.btnUnLockedUButton = objectReference:GetRefValue("btnUnLockedUButton")
	self.focusTransform = objectReference:GetRefValue("focusTransform")
	self.btnLockedUButton = objectReference:GetRefValue("btnLockedUButton")
	self.btnSwitchUButton = objectReference:GetRefValue("btnSwitchUButton")
	self.btnScanUButton = objectReference:GetRefValue("btnScanUButton")
	self.cameraCtrlDragUpdateListener = objectReference:GetRefValue("cameraCtrlDragUpdateListener")
	self.capturePhoto = objectReference:GetRefValue("capturePhoto")
	self.captureBtn = objectReference:GetRefValue("captureBtn")
	self.ecologyNameUText = objectReference:GetRefValue("ecologyNameUText")
	self.captureTip = objectReference:GetRefValue("captureTip")
	self.captureNewFeatures = objectReference:GetRefValue("captureNewFeatures")
	self.ecologyUWidget = objectReference:GetRefValue("ecologyUWidget")
	self.capture = objectReference:GetRefValue("capture")
	self.btnMenuUButton = objectReference:GetRefValue("btnMenuUButton")
	self.btnPoseUButton = objectReference:GetRefValue("btnPoseUButton")
	self.btnRotatePhotoUButton = objectReference:GetRefValue("btnRotatePhotoUButton")
	self.cameraMenuPanelUComponent = objectReference:GetRefValue("cameraMenuPanelUComponent")
	self.btnAlbumUButton = objectReference:GetRefValue("btnAlbumUButton")
	self.bgClickUButton = objectReference:GetRefValue("bgClickUButton")
	self.center2Transform = objectReference:GetRefValue("center2Transform")
	self.btnVideoTapeUButton = objectReference:GetRefValue("btnVideoTapeUButton")
	self.settingWidgetUWidget = objectReference:GetRefValue("settingWidgetUWidget")
	self.btnSettingUButton = objectReference:GetRefValue("btnSettingUButton")
	self.identificationBtnsUWidget = objectReference:GetRefValue("identificationBtnsUWidget")
	self.rootWindowsRectTransform = objectReference:GetRefValue("rootWindowsRectTransform")
	self.changeLensAnimation = objectReference:GetRefValue("changeLensAnimation")
	self.referenceLineUWidget = objectReference:GetRefValue("referenceLineUWidget")
	self.mobileCameraCtrlUButton = objectReference:GetRefValue("mobileCameraCtrlUButton")
	self.btnTimePauseUButton = objectReference:GetRefValue("btnTimePauseUButton")
	self.btnUpUButton = objectReference:GetRefValue("btnUpUButton")
	self.btnDownUButton = objectReference:GetRefValue("btnDownUButton")
	self.titleUWidget = objectReference:GetRefValue("titleUWidget")
	self.keyBox3RectTransform = objectReference:GetRefValue("keyBox3RectTransform")
	self.capturedBtnHotKeyContent = objectReference:GetRefValue("capturedBtnHotKeyContent")
	self.targetAppearUWidget = objectReference:GetRefValue("targetAppearUWidget")
	self.targetContent = objectReference:GetRefValue("targetContent")
	self.followFrameUWidget = objectReference:GetRefValue("followFrameUWidget")
	self.center2UWidget = objectReference:GetRefValue("center2UWidget")
	self.takePhotoBtn = objectReference:GetRefValue("takePhotoBtn")
	self.btnPhotographUButton = objectReference:GetRefValue("btnPhotographUButton")
	self.btnAppearanceUButton = objectReference:GetRefValue("btnAppearanceUButton")
	self.btnHideUIUButton = objectReference:GetRefValue("btnHideUIUButton")
	self.btnScanCodeUButton = objectReference:GetRefValue("btnScanCodeUButton")
	self.btnFocusUButton = objectReference:GetRefValue("btnFocusUButton")
	self.operateMobileUWidget = objectReference:GetRefValue("operateMobileUWidget")
	self.cameraBtnsUWidget = objectReference:GetRefValue("cameraBtnsUWidget")
	self.textQRCodeUBaseText = objectReference:GetRefValue("textQRCodeUBaseText")
	self.textHIdeUIUBaseText = objectReference:GetRefValue("textHIdeUIUBaseText")
	self.textAppearanceUBaseText = objectReference:GetRefValue("textAppearanceUBaseText")
	self.textAlbumUBaseText = objectReference:GetRefValue("textAlbumUBaseText")
	self.textSettingUBaseText = objectReference:GetRefValue("textSettingUBaseText")
	self.textTrackUBaseText = objectReference:GetRefValue("textTrackUBaseText")
	self.textTimeUBaseText = objectReference:GetRefValue("textTimeUBaseText")
	self.textResetUBaseText = objectReference:GetRefValue("textResetUBaseText")
	self.safeBoxMobileUWidget = objectReference:GetRefValue("safeBoxMobileUWidget")
	self.btnSettingMenuUButton = objectReference:GetRefValue("btnSettingMenuUButton")
	self.btnBackMainUButton = objectReference:GetRefValue("btnBackMainUButton")
	self.backKeyHotkeyContent = objectReference:GetRefValue("backKeyHotkeyContent")
	self.settingMenuHotKeyContent = objectReference:GetRefValue("settingMenuHotKeyContent")
	self.settingMenuProgressPressContainerUContainer = objectReference:GetRefValue("settingMenuProgressPressContainerUContainer")
	self.keyLeftConsoleUWidget = objectReference:GetRefValue("keyLeftConsoleUWidget")
	self.pictureQualityUWidget = objectReference:GetRefValue("pictureQualityUWidget")

	local pictureQualityObjectReference = self.pictureQualityUWidget.transform:GetComponent("ObjectReference")

	self.pictureQualitySelectedUButton = pictureQualityObjectReference:GetRefValue("btnSelectedUButton")
	self.pictureQualityNameUBaseText = pictureQualityObjectReference:GetRefValue("txtNameUBaseText")
	self.eventTopUWidget = objectReference:GetRefValue("eventTopUWidget")
	self.txtEventTop = objectReference:GetRefValue("txtEventTop")
end

function PhotoView:initView()
	ClientTextUtils.setText(self.textQRCodeUBaseText, pg.getGameString("PHOTO_TITLE_QRCODE"))
	ClientTextUtils.setText(self.textHIdeUIUBaseText, pg.getGameString("PHOTO_TITLE_HIDEUI"))
	ClientTextUtils.setText(self.textAppearanceUBaseText, pg.getGameString("PHOTO_TITLE_APPEARANCE"))
	ClientTextUtils.setText(self.textAlbumUBaseText, pg.getGameString("PHOTO_TITLE_ALBUM"))
	ClientTextUtils.setText(self.textSettingUBaseText, pg.getGameString("PHOTO_TITLE_SETTINGS"))
	ClientTextUtils.setText(self.textTrackUBaseText, pg.getGameString("PHOTO_TITLE_TRACK"))
	ClientTextUtils.setText(self.textTimeUBaseText, pg.getGameString("PHOTO_TITLE_TIME"))
	ClientTextUtils.setText(self.textResetUBaseText, pg.getGameString("PHOTO_TITLE_RESET"))
	ClientTextUtils.setText(self.pictureQualityNameUBaseText, pg.getGameString("PHOTO_TOP_VIDEO_QUALITY"))
	ClientTextUtils.setText(self.txtEventTop, pg.getGameString("REDNOTE_CORRECT_PLACE"))
end

function PhotoView:showCapturePhoto(sprite, title, hideCapture)
	self.rootComponent:TryChangePage("CaptureState", hideCapture and 0 or 1)

	self.photoSprite = sprite
	self.photoTitle = title
	self.capturePhoto.sprite = self.photoSprite

	if self.photoTitle ~= nil then
		ClientTextUtils.setText(self.ecologyNameUText, pg.getLocalizationText(self.photoTitle))
	end
end

function PhotoView:closeCapturePhoto()
	self.rootComponent:TryChangePage("CaptureState", 0)
end

return PhotoView
