-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\MarkShareEdit\\MarkShareEditView.lua

local Class = require("Core.Framework.Class")
local UIView = require("Guis.UIView")
local MarkShareEditView = Class.LightClass("MarkShareEditView", UIView)

function MarkShareEditView:findObjects()
	local objectReference = self.transform:GetComponent("ObjectReference")

	self.mainBackBtn = objectReference:GetRefValue("mainBackBtn")
	self.root = objectReference:GetRefValue("root")
	self.btnNewUButton = objectReference:GetRefValue("btnNewUButton")
	self.btnHistoryUButton = objectReference:GetRefValue("btnHistoryUButton")
	self.createNewMarkBtn = objectReference:GetRefValue("createNewMarkBtn")
	self.consumeUList = objectReference:GetRefValue("consumeUList")
	self.btnSendUButton = objectReference:GetRefValue("btnSendUButton")
	self.editingTxtContent = objectReference:GetRefValue("editingTxtContent")
	self.listMainUList = objectReference:GetRefValue("listMainUList")
	self.btnBackUButton = objectReference:GetRefValue("btnBackUButton")
	self.btnConfiemUButton = objectReference:GetRefValue("btnConfiemUButton")
	self.listTemplateUList = objectReference:GetRefValue("listTemplateUList")
	self.btnSubBackUButton = objectReference:GetRefValue("btnSubBackUButton")
	self.listWordUList = objectReference:GetRefValue("listWordUList")
	self.listTabUList = objectReference:GetRefValue("listTabUList")
	self.listBubbleUList = objectReference:GetRefValue("listBubbleUList")
	self.listActionUList = objectReference:GetRefValue("listActionUList")
	self.btnBubbleUButton = objectReference:GetRefValue("btnBubbleUButton")
	self.btnActionUButton = objectReference:GetRefValue("btnActionUButton")
	self.historyCount = objectReference:GetRefValue("historyCount")
	self.historyList = objectReference:GetRefValue("historyList")
	self.uselessBtn = objectReference:GetRefValue("uselessBtn")
	self.activeDeleModeBtn = objectReference:GetRefValue("activeDeleModeBtn")
	self.btnClearTextUButton = objectReference:GetRefValue("btnClearTextUButton")
	self.holdingTxtContent = objectReference:GetRefValue("holdingTxtContent")
	self.editingWordBtn = objectReference:GetRefValue("editingWordBtn")
	self.editingWordDeleteBtn = objectReference:GetRefValue("editingWordDeleteBtn")
	self.editingBubbleDeleteBtn = objectReference:GetRefValue("editingBubbleDeleteBtn")
	self.editingAnimationDeleteBtn = objectReference:GetRefValue("editingAnimationDeleteBtn")
	self.listConjUList = objectReference:GetRefValue("listConjUList")
	self.animationAvatarIcon = objectReference:GetRefValue("animationAvatarIcon")
	self.txtTipsUSDFText = objectReference:GetRefValue("txtTipsUSDFText")
	self.btnConfirmDeleteUButton = objectReference:GetRefValue("btnConfirmDeleteUButton")
	self.bubbleTypeIcon = objectReference:GetRefValue("bubbleTypeIcon")
	self.contentAnimation = objectReference:GetRefValue("contentAnimation")
	self.btnClearAlterUButton = objectReference:GetRefValue("btnClearAlterUButton")
	self.btnLeftUButton = objectReference:GetRefValue("btnLeftUButton")
	self.btnRightUButton = objectReference:GetRefValue("btnRightUButton")
	self.fillerWordTitle = objectReference:GetRefValue("fillerWordTitle")
	self.editingTxtContentButton = objectReference:GetRefValue("editingTxtContentButton")
	self.gMButtonUButton = objectReference:GetRefValue("gMButtonUButton")
	self.inputFieldUTMPInputField = objectReference:GetRefValue("inputFieldUTMPInputField")
	self.templateUWidget = objectReference:GetRefValue("templateUWidget")
	self.txtEdit = objectReference:GetRefValue("txtEdit")
	self.txtTitleUBaseText = objectReference:GetRefValue("txtTitleUBaseText")
	self.leftKeyHotKeyContent = objectReference:GetRefValue("leftKeyHotKeyContent")
	self.rightKeyHotKeyContent = objectReference:GetRefValue("rightKeyHotKeyContent")
	self.btnInfoUButton = objectReference:GetRefValue("btnInfoUButton")
end

function MarkShareEditView:initView()
	if pg.me.gmMode == 1 then
		self.gMButtonUButton.gameObject:SetActiveEx(true)
	end
end

return MarkShareEditView
