-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\Chat\\ChatView.lua

local Class = require("Core.Framework.Class")
local UIView = require("Guis.UIView")
local ClientTextUtils = require("Utils.ClientTextUtils")
local ChatView = Class.LightClass("ChatView", UIView)

function ChatView:findObjects()
	local objectReference = self.transform:GetComponent("ObjectReference")

	self.bgCloseUButton = objectReference:GetRefValue("bgCloseUButton")
	self.rootUComponent = objectReference:GetRefValue("rootUComponent")
	self.btnChatUButton = objectReference:GetRefValue("btnChatUButton")
	self.btnNoticeUButton = objectReference:GetRefValue("btnNoticeUButton")
	self.btnPublicUButton = objectReference:GetRefValue("btnPublicUButton")
	self.btnSetUButton = objectReference:GetRefValue("btnSetUButton")
	self.privateUComponent = objectReference:GetRefValue("privateUComponent")
	self.personalUComponent = objectReference:GetRefValue("personalUComponent")
	self.publicUComponent = objectReference:GetRefValue("publicUComponent")
	self.channelListUList = objectReference:GetRefValue("channelListUList")
	self.btnAddUButton = objectReference:GetRefValue("btnAddUButton")
	self.btnExpendUButton = objectReference:GetRefValue("btnExpendUButton")
	self.bottomSendUComponent = objectReference:GetRefValue("bottomSendUComponent")
	self.btnNewUButton = objectReference:GetRefValue("btnNewUButton")
	self.btnSwitchUButton = objectReference:GetRefValue("btnSwitchUButton")
	self.btnVoiceUButton = objectReference:GetRefValue("btnVoiceUButton")
	self.inputFieldUTMPInputField = objectReference:GetRefValue("inputFieldUTMPInputField")
	self.btnSendAddUButton = objectReference:GetRefValue("btnSendAddUButton")
	self.btnConfirmUButton = objectReference:GetRefValue("btnConfirmUButton")
	self.addPanelUWidget = objectReference:GetRefValue("addPanelUWidget")
	self.extendFuncList = objectReference:GetRefValue("extendFuncList")
	self.txtDisUBaseText = objectReference:GetRefValue("txtDisUBaseText")
	self.warningTipsUWidget = objectReference:GetRefValue("warningTipsUWidget")
	self.btnPrivateAddUButton = objectReference:GetRefValue("btnPrivateAddUButton")
	self.iconPrivateAddUImage = objectReference:GetRefValue("iconPrivateAddUImage")
	self.txtPrivateEmptyUBaseText = objectReference:GetRefValue("txtPrivateEmptyUBaseText")
	self.iconEmptyUImage = objectReference:GetRefValue("iconEmptyUImage")
	self.txtEmptyUBaseText = objectReference:GetRefValue("txtEmptyUBaseText")
	self.imgFigureUImage = objectReference:GetRefValue("imgFigureUImage")
	self.channelNameUText = objectReference:GetRefValue("channelNameUText")
	self.chatBoxTopAddBtn = objectReference:GetRefValue("chatBoxTopAddBtn")
	self.btnPrivateOtherUButton = objectReference:GetRefValue("btnPrivateOtherUButton")
	self.listOtherUList = objectReference:GetRefValue("listOtherUList")
	self.personalTxtName = objectReference:GetRefValue("personalTxtName")
	self.listMembersUList = objectReference:GetRefValue("listMembersUList")
	self.personalTopAddBtn = objectReference:GetRefValue("personalTopAddBtn")
	self.publicTxtName = objectReference:GetRefValue("publicTxtName")
	self.btnPublicOtherUButton = objectReference:GetRefValue("btnPublicOtherUButton")
	self.btnPublicOtherUList = objectReference:GetRefValue("btnPublicOtherUList")
	self.txtSettingsUBaseText = objectReference:GetRefValue("txtSettingsUBaseText")
	self.settingListUList = objectReference:GetRefValue("settingListUList")
	self.chatUInputField = objectReference:GetRefValue("chatUInputField")
	self.btnBottomAddUButton = objectReference:GetRefValue("btnBottomAddUButton")
	self.btnCloseUButton = objectReference:GetRefValue("btnCloseUButton")
	self.panelUComponent = objectReference:GetRefValue("panelUComponent")
	self.noMessageRectTransform = objectReference:GetRefValue("noMessageRectTransform")
	self.topInfoRectTransform = objectReference:GetRefValue("topInfoRectTransform")
	self.otherPanelRectTransform = objectReference:GetRefValue("otherPanelRectTransform")
	self.txtNumUBaseText = objectReference:GetRefValue("txtNumUBaseText")
	self.secondTabRectTransform = objectReference:GetRefValue("secondTabRectTransform")
	self.emblemUImage = objectReference:GetRefValue("emblemUImage")
	self.imgLikabilityUImage = objectReference:GetRefValue("imgLikabilityUImage")
	self.txtNameChangeUSDFText = objectReference:GetRefValue("txtNameChangeUSDFText")
	self.nameCoverUSDFText = objectReference:GetRefValue("nameCoverUSDFText")
	self.addBtnCloseUButton = objectReference:GetRefValue("addBtnCloseUButton")
	self.otherBtnCloseUButton = objectReference:GetRefValue("otherBtnCloseUButton")
	self.messageListUList = objectReference:GetRefValue("messageListUList")
	self.textAreaRectTransform = objectReference:GetRefValue("textAreaRectTransform")
	self.btnMailUButton = objectReference:GetRefValue("btnMailUButton")
	self.mailUComponent = objectReference:GetRefValue("mailUComponent")
	self.btnGoUButton = objectReference:GetRefValue("btnGoUButton")
	self.historyInformationUComponent = objectReference:GetRefValue("historyInformationUComponent")
	self.settingUComponent = objectReference:GetRefValue("settingUComponent")
	self.chatItemUComponent = objectReference:GetRefValue("chatItemUComponent")
	self.petShareUComponent = objectReference:GetRefValue("petShareUComponent")
	self.friendListPanelUComponent = objectReference:GetRefValue("friendListPanelUComponent")
	self.gameplayUComponent = objectReference:GetRefValue("gameplayUComponent")
	self.btnReplyUButton = objectReference:GetRefValue("btnReplyUButton")
	self.replyTextUSDFText = objectReference:GetRefValue("replyTextUSDFText")
	self.btnBottomEmojiUButton = objectReference:GetRefValue("btnBottomEmojiUButton")
	self.emojiUWidget = objectReference:GetRefValue("emojiUWidget")
	self.listEmojiUList = objectReference:GetRefValue("listEmojiUList")
	self.replyUWidget = objectReference:GetRefValue("replyUWidget")
	self.playerStateUSDFText = objectReference:GetRefValue("playerStateUSDFText")
	self.channelPanelUComponent = objectReference:GetRefValue("channelPanelUComponent")
	self.channelTipUWidget = objectReference:GetRefValue("channelTipUWidget")
	self.textTipsUSDFText = objectReference:GetRefValue("textTipsUSDFText")
	self.btnSystemCheckUButton = objectReference:GetRefValue("btnSystemCheckUButton")
	self.bottomSearchUTMPInputField = objectReference:GetRefValue("bottomSearchUTMPInputField")
	self.expendNumUSDFText = objectReference:GetRefValue("expendNumUSDFText")
	self.btnFriendUButton = objectReference:GetRefValue("btnFriendUButton")
	self.topOtherBtnCloseUButton = objectReference:GetRefValue("topOtherBtnCloseUButton")
	self.emojiCloseUButton = objectReference:GetRefValue("emojiCloseUButton")
	self.extensionCloseUButton = objectReference:GetRefValue("extensionCloseUButton")
	self.btnGoTextUSDFText = objectReference:GetRefValue("btnGoTextUSDFText")
	self.listFriendChannelUList = objectReference:GetRefValue("listFriendChannelUList")
	self.friendUComponent = objectReference:GetRefValue("friendUComponent")
	self.listEmojiTabUList = objectReference:GetRefValue("listEmojiTabUList")
	self.searchPlaceHolderUSDFText = objectReference:GetRefValue("searchPlaceHolderUSDFText")
	self.voicePanelUWidget = objectReference:GetRefValue("voicePanelUWidget")
	self.btnVoicePlayUButton = objectReference:GetRefValue("btnVoicePlayUButton")
	self.btnVoiceNotUButton = objectReference:GetRefValue("btnVoiceNotUButton")
	self.textVoiceUSDFText = objectReference:GetRefValue("textVoiceUSDFText")
	self.mainConsoleBarTransform = objectReference:GetRefValue("mainConsoleBarTransform")
	self.textSystemCheckUSDFText = objectReference:GetRefValue("textSystemCheckUSDFText")
	self.chatInformUWidget = objectReference:GetRefValue("chatInformUWidget")
	self.chatInputHolderUSDFText = objectReference:GetRefValue("chatInputHolderUSDFText")
	self.btnImgLikabilityUButton = objectReference:GetRefValue("btnImgLikabilityUButton")
	self.txtNewMsgUSDFText = objectReference:GetRefValue("txtNewMsgUSDFText")
	self.uiBlurDynamic = objectReference:GetRefValue("uiBlurDynamic")
	self.uiBlurStatic = objectReference:GetRefValue("uiBlurStatic")
end

function ChatView:registerObjects()
	return
end

function ChatView:initView()
	ClientTextUtils.setText(self.chatInputHolderUSDFText, pg.getGameString("CHAT_TIP_INPUT"))
end

return ChatView
