-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\BossRushChallenge\\BossRushChallengeView.lua

local logger = require("Core.Log.LoggerManager").getLogger("BossRushChallengeView")
local Class = require("Core.Framework.Class")
local UIView = require("Guis.UIView")
local ClientTextUtils = require("Utils.ClientTextUtils")
local BossRushChallengeView = Class.LightClass("BossRushChallengeView", UIView)

function BossRushChallengeView:findObjects()
	self.objectReference = self.transform:GetComponent("ObjectReference")
	self.btnBackUButton = self.objectReference:GetRefValue("btnBackUButton")
	self.rankUBaseText = self.objectReference:GetRefValue("rankUBaseText")
	self.scoreUBaseText = self.objectReference:GetRefValue("scoreUBaseText")
	self.timeUBaseText = self.objectReference:GetRefValue("timeUBaseText")
	self.recommentEleUList = self.objectReference:GetRefValue("recommentEleUList")
	self.listTipsUList = self.objectReference:GetRefValue("listTipsUList")
	self.listPlayerUList = self.objectReference:GetRefValue("listPlayerUList")
	self.btnConfirmUButton = self.objectReference:GetRefValue("btnConfirmUButton")
	self.bossTitleUBaseText = self.objectReference:GetRefValue("bossTitleUBaseText")
	self.buffUList = self.objectReference:GetRefValue("buffUList")
	self.helpUList = self.objectReference:GetRefValue("helpUList")
	self.chatUWidget = self.objectReference:GetRefValue("chatUWidget")
	self.readyUBaseText = self.objectReference:GetRefValue("readyUBaseText")
	self.readyUWidget = self.objectReference:GetRefValue("readyUWidget")
	self.teamMemUWidget = self.objectReference:GetRefValue("teamMemUWidget")
	self.rootUComponent = self.objectReference:GetRefValue("rootUComponent")
	self.specialBuffUList = self.objectReference:GetRefValue("specialBuffUList")
	self.normalBuffUList = self.objectReference:GetRefValue("normalBuffUList")
	self.playIconUImage = self.objectReference:GetRefValue("playIconUImage")
	self.playTitleUBaseText = self.objectReference:GetRefValue("playTitleUBaseText")
	self.playDetailUBaseText = self.objectReference:GetRefValue("playDetailUBaseText")
	self.envIconUImage = self.objectReference:GetRefValue("envIconUImage")
	self.envTitleUBaseText = self.objectReference:GetRefValue("envTitleUBaseText")
	self.envDetailUBaseText = self.objectReference:GetRefValue("envDetailUBaseText")
	self.btnLeftUButton = self.objectReference:GetRefValue("btnLeftUButton")
	self.btnRightUButton = self.objectReference:GetRefValue("btnRightUButton")
	self.detail1UButton = self.objectReference:GetRefValue("detail1UButton")
	self.detail2UButton = self.objectReference:GetRefValue("detail2UButton")
	self.fxRefreshAnimation = self.objectReference:GetRefValue("fxRefreshAnimation")
	self.starUBaseText = self.objectReference:GetRefValue("starUBaseText")
	self.panelTankUButton = self.objectReference:GetRefValue("panelTankUButton")
	self.selectTankUList = self.objectReference:GetRefValue("selectTankUList")
	self.luckyPetUWidget = self.objectReference:GetRefValue("luckyPetUWidget")
	self.luckyUButton = self.objectReference:GetRefValue("luckyUButton")
	self.consoleBarTransform = self.objectReference:GetRefValue("consoleBarTransform")
	self.btnTankUButton = self.objectReference:GetRefValue("btnTankUButton")
	self.tankBgUButton = self.objectReference:GetRefValue("tankBgUButton")
	self.textWarningTipsUBaseText = self.objectReference:GetRefValue("textWarningTipsUBaseText")
	self.recommendPetUBaseText = self.objectReference:GetRefValue("recommendPetUBaseText")
	self.recommendUButton = self.objectReference:GetRefValue("recommendUButton")
	self.cycleBuffUList = self.objectReference:GetRefValue("cycleBuffUList")
	self.seasonBuffBtnSearchUButton = self.objectReference:GetRefValue("seasonBuffBtnSearchUButton")
	self.seasonBuffTitle2USDFText = self.objectReference:GetRefValue("seasonBuffTitle2USDFText")
	self.cycleBuffBtnSearchUButton = self.objectReference:GetRefValue("cycleBuffBtnSearchUButton")
	self.seasonBuffTitleUSDFText = self.objectReference:GetRefValue("seasonBuffTitleUSDFText")
	self.seasonBuffBtnSearch2UButton = self.objectReference:GetRefValue("seasonBuffBtnSearch2UButton")
	self.numBoxTextUSDFText = self.objectReference:GetRefValue("numBoxTextUSDFText")
	self.playDetailUScrollRect = self.objectReference:GetRefValue("playDetailUScrollRect")
	self.envDetailUScrollRect = self.objectReference:GetRefValue("envDetailUScrollRect")
end

function BossRushChallengeView:registerObjects()
	local objectReference = self.btnConfirmUButton:GetComponent("ObjectReference")

	self.confirmUText = objectReference:GetRefValue("txtNameUText")

	local chatObjectReference = self.chatUWidget:GetComponent("ObjectReference")

	self.btnChat = chatObjectReference:GetRefValue("btnChat")
end

function BossRushChallengeView:initView()
	ClientTextUtils.setText(self.seasonBuffTitle2USDFText, ClientTextUtils.getGameString("BOSS_RUSH_CHALLENGE_TIP1"))
	ClientTextUtils.setText(self.seasonBuffTitleUSDFText, ClientTextUtils.getGameString("BOSS_RUSH_CHALLENGE_TIP1"))
	ClientTextUtils.setText(self.numBoxTextUSDFText, ClientTextUtils.getGameString("BOSS_RUSH_CHALLENGE_TIP4"))
end

return BossRushChallengeView
