-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\PetLevelUp\\PetLevelUpView.lua

local UIView = require("Guis.UIView")
local Class = require("Core.Framework.Class")
local PetLevelUpView = Class.LightClass("PetLevelUpView", UIView)

function PetLevelUpView:findObjects()
	self.objectReference = self.transform:GetComponent("ObjectReference")
	self.btnCloseUButton = self.objectReference:GetRefValue("btnCloseUButton")
	self.txtTitleUText = self.objectReference:GetRefValue("txtTitleUText")
	self.imgPetUImage = self.objectReference:GetRefValue("imgPetUImage")
	self.txtLevelUText = self.objectReference:GetRefValue("txtLevelUText")
	self.petDemensionObjectReference = self.objectReference:GetRefValue("petDemensionObjectReference")
	self.upTipsUWidget = self.objectReference:GetRefValue("upTipsUWidget")
	self.textUSDFText = self.objectReference:GetRefValue("textUSDFText")
	self.hpNum = self.petDemensionObjectReference:GetRefValue("hpNum")
	self.atkNum = self.petDemensionObjectReference:GetRefValue("atkNum")
	self.defNum = self.petDemensionObjectReference:GetRefValue("defNum")
	self.regenNum = self.petDemensionObjectReference:GetRefValue("regenNum")
	self.defMagNum = self.petDemensionObjectReference:GetRefValue("defMagNum")
	self.atkMagNum = self.petDemensionObjectReference:GetRefValue("atkMagNum")
	self.hpCmp = self.petDemensionObjectReference:GetRefValue("hpCmp")
	self.atkCmp = self.petDemensionObjectReference:GetRefValue("atkCmp")
	self.defCmp = self.petDemensionObjectReference:GetRefValue("defCmp")
	self.regenCmp = self.petDemensionObjectReference:GetRefValue("regenCmp")
	self.defMagCmp = self.petDemensionObjectReference:GetRefValue("defMagCmp")
	self.atkMagCmp = self.petDemensionObjectReference:GetRefValue("atkMagCmp")
	self.hpLevelCmp = self.petDemensionObjectReference:GetRefValue("hpLevelCmp")
	self.atkLevelCmp = self.petDemensionObjectReference:GetRefValue("atkLevelCmp")
	self.defLevelCmp = self.petDemensionObjectReference:GetRefValue("defLevelCmp")
	self.regenLevelCmp = self.petDemensionObjectReference:GetRefValue("regenLevelCmp")
	self.defMagLevelCmp = self.petDemensionObjectReference:GetRefValue("defMagLevelCmp")
	self.atkMagLevelCmp = self.petDemensionObjectReference:GetRefValue("atkMagLevelCmp")
	self.hpLv = self.petDemensionObjectReference:GetRefValue("hpLv")
	self.atkLv = self.petDemensionObjectReference:GetRefValue("atkLv")
	self.defLv = self.petDemensionObjectReference:GetRefValue("defLv")
	self.regenLv = self.petDemensionObjectReference:GetRefValue("regenLv")
	self.defMagLv = self.petDemensionObjectReference:GetRefValue("defMagLv")
	self.atkMagLv = self.petDemensionObjectReference:GetRefValue("atkMagLv")
	self.defaultRadar = self.petDemensionObjectReference:GetRefValue("defaultRadar")
	self.addedRadar = self.petDemensionObjectReference:GetRefValue("addedRadar")
	self.hpValueAdd = self.petDemensionObjectReference:GetRefValue("hpValueAdd")
	self.atkValueAdd = self.petDemensionObjectReference:GetRefValue("atkValueAdd")
	self.defValueAdd = self.petDemensionObjectReference:GetRefValue("defValueAdd")
	self.regenValueAdd = self.petDemensionObjectReference:GetRefValue("regenValueAdd")
	self.defMagValueAdd = self.petDemensionObjectReference:GetRefValue("defMagValueAdd")
	self.atkMagValueAdd = self.petDemensionObjectReference:GetRefValue("atkMagValueAdd")
end

function PetLevelUpView:initView()
	return
end

return PetLevelUpView
