-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Guis\\Panels\\ActiveDungeon\\ActiveDungeonView.lua

local logger = require("Core.Log.LoggerManager").getLogger("ActiveDungeonView")
local Class = require("Core.Framework.Class")
local ClientTextUtils = require("Utils.ClientTextUtils")
local UIView = require("Guis.UIView")
local ActiveDungeonView = Class.LightClass("ActiveDungeonView", UIView)

function ActiveDungeonView:findObjects()
	self.objectReference = self.transform:GetComponent("ObjectReference")
	self.picUImage = self.objectReference:GetRefValue("picUImage")
	self.btnBackUButton = self.objectReference:GetRefValue("btnBackUButton")
	self.currencyItemUButton = self.objectReference:GetRefValue("currencyItemUButton")
	self.btnConfirmUButton = self.objectReference:GetRefValue("btnConfirmUButton")
	self.dungeonNameUText = self.objectReference:GetRefValue("dungeonNameUText")
	self.dungeonDetailUText = self.objectReference:GetRefValue("dungeonDetailUText")
	self.rewardUList = self.objectReference:GetRefValue("rewardUList")
	self.challengeUText = self.objectReference:GetRefValue("challengeUText")
	self.consoleBarTransform = self.objectReference:GetRefValue("consoleBarTransform")
	self.peopleNumUBaseText = self.objectReference:GetRefValue("peopleNumUBaseText")
	self.recommendEleList = self.objectReference:GetRefValue("recommendEleList")
	self.skillListUList = self.objectReference:GetRefValue("skillListUList")
	self.chestNumUBaseText = self.objectReference:GetRefValue("chestNumUBaseText")
	self.elementRecommendUWidget = self.objectReference:GetRefValue("elementRecommendUWidget")
	self.skillRecommendUWidget = self.objectReference:GetRefValue("skillRecommendUWidget")
	self.chestUWidget = self.objectReference:GetRefValue("chestUWidget")
	self.petLimitUWidget = self.objectReference:GetRefValue("petLimitUWidget")
	self.petLimitListUList = self.objectReference:GetRefValue("petLimitListUList")
	self.listCurrencyUList = self.objectReference:GetRefValue("listCurrencyUList")
	self.bossDungeonContainerUContainer = self.objectReference:GetRefValue("bossDungeonContainerUContainer")
	self.textPanelUWidget = self.objectReference:GetRefValue("textPanelUWidget")
	self.textPanelTxtName = self.objectReference:GetRefValue("textPanelTxtName")
	self.textPanelDesc = self.objectReference:GetRefValue("textPanelDesc")
	self.rewardUWidget = self.objectReference:GetRefValue("rewardUWidget")
	self.rewardList = self.objectReference:GetRefValue("rewardList")
	self.txtNameUSDFText = self.objectReference:GetRefValue("txtNameUSDFText")
	self.elementTxtDetails = self.objectReference:GetRefValue("elementTxtDetails")
	self.btnPlayUButton = self.objectReference:GetRefValue("btnPlayUButton")
	self.btnMatchUButton = self.objectReference:GetRefValue("btnMatchUButton")
	self.btnPlayTeamFullUButton = self.objectReference:GetRefValue("btnPlayTeamFullUButton")
	self.teamBtnBoxUComponent = self.objectReference:GetRefValue("teamBtnBoxUComponent")
	self.btnCancelUButton = self.objectReference:GetRefValue("btnCancelUButton")
	self.countDownUCountDown = self.objectReference:GetRefValue("countDownUCountDown")
	self.backTitle = self.objectReference:GetRefValue("backTitle")
end

function ActiveDungeonView:registerObjects()
	self.bossDungeonContainerUContainer:LoadDefaultUrlManually()
	self.bossDungeonContainerUContainer:SetActive(true)
end

function ActiveDungeonView:initView()
	self.petLimitUWidget:SetActive(false)
	self.skillRecommendUWidget:SetActive(false)
	self.chestUWidget:SetActive(false)
	self.elementTxtDetails:SetActive(false)
	ClientTextUtils.setText(self.txtNameUSDFText, pg.getGameString("BOSS_CHALLENGE_TEXT2"))
end

return ActiveDungeonView
