-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Common\\Const\\AbilityConst.lua

local bit = bit
local AbilityConst = {
	ACTION_TIMELINE_CMD_SET = 1,
	ABILITY_CAST_FAILED_NOT_IN_SPECIAL_STATE = 27,
	ABILITY_CAST_FAILED_ROUGE_DUNGEON_NOT_IN_COMBAT = 28,
	ABILITY_CAST_FAILED_ROGUE_EP_NOT_ENOUGH = 29,
	ABILITY_CAST_AUTO_CAST = 30,
	ABILITY_CAST_FAILED_LOADED_CNT = 31,
	ABILITY_CAST_FAILED_BACK_NOT_IN_COMBAT = 32,
	ABILITY_CAST_ABILITY_NOT_ENOUGH_WATER = 33,
	ABILITY_CAST_FAILED_PET_NOT_FOUND = 20,
	ABILITY_CAST_PUSH_SKILL = 19,
	ABILITY_CAST_FAILED_STATE_CHECK_FAILED = 18,
	ABILITY_CAST_FAILED_NOT_ENOUGH_STAMINA = 17,
	ATTRIBUTE_ID_OFFSET_SINGLE = -1,
	ATTRIBUTE_ID_OFFSET_CUR = 0,
	ATTRIBUTE_ID_OFFSET_V = 1,
	ATTRIBUTE_ID_OFFSET_P = 2,
	ATTRIBUTE_ID_OFFSET_FIX = 3,
	ATTRIBUTE_ID_OFFSET_CONV = 4,
	ATTRIBUTE_ID_OFFSET_MAX = 5,
	ATTRIBUTE_ID_OFFSET_XP_CUR = 5,
	ATTRIBUTE_ID_OFFSET_XP_REGEN_V = 6,
	ATTRIBUTE_ID_OFFSET_MAX_PVC_CUR = 5,
	ATTRIBUTE_SRC_TYPE_LEVEL = 1,
	ATTRIBUTE_SRC_TYPE_BUFF = 2,
	ATTRIBUTE_SRC_TYPE_PET_PROPERTY = 3,
	ATTRIBUTE_SRC_TYPE_BUFF_DYNAMIC = 4,
	ATTRIBUTE_SRC_TYPE_BUFF_LAYER = 5,
	ATTRIBUTE_SRC_TYPE_ENTRY = 6,
	ATTRIBUTE_SRC_TYPE_SPACE = 7,
	ATTRIBUTE_SRC_TYPE_APPEARANCE = 8,
	ATTRIBUTE_SRC_TYPE_BUFF_CONDITIONAL = 9,
	ATTRIBUTE_SRC_TYPE_BUFF_SERIES_CNT = 10,
	ATTRIBUTE_SRC_TYPE_SINGLE_WORLD_HP_SCALE = 20,
	ATTRIBUTE_SRC_TYPE_ROB_EGG_EQUIP = 21,
	ATTRIBUTE_SRC_TYPE_FIRST_ATTACK_CALC = 22,
	ATTRIBUTE_SRC_TYPE_CORE_CARRY_CONVERSION = 23,
	ATTRIBUTE_SRC_TYPE_PET_PRIMARY_PROPERTY = 24,
	ATTRIBUTE_SRC_TYPE_PET_RESONANCE = 25,
	ATTRIBUTE_SRC_TYPE_PET_JERELRY = 26,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_EX = 27,
	NOTIFY_STATE_TIME_NODE_EXIT = 2,
	ACTION_TIMELINE_CMD_CONTINUE = 3,
	ACTION_TIMELINE_CMD_STOP = 2,
	TIMELINE_HIT = 2,
	TIMELINE_COMBAT = 1,
	ACTION_TIMELINE_LAYER_PARALLEL = "Parallel",
	ACTION_TIMELINE_LAYER_ADDITIVE = "Additive",
	ACTION_TIMELINE_LAYER_BASE = "Base",
	TIMELINE_EVENT_NOTIFY_STATE = "NotifyState",
	TIMELINE_EVENT_NOTIFY = "Notify",
	TIMELINE_EVENT_EXIT = "EventExit",
	ABILITY_CAST_FAILED_NONE = 0,
	MAX_EFX_NUM = 65535,
	TRIGGER_ON_BUFF_BE_INHERIT = "onBuffBeInheritIds",
	ABILITY_CAST_ABILITY_NOT_ENOUGH_ITEM = 24,
	ABILITY_CAST_FAILED_IN_TAKEROOT = 25,
	ABILITY_EFFECT_TAG_REDUCE_DEFENCE = 8,
	ABILITY_EFFECT_TAG_DEBUFF = 9,
	ABILITY_EFFECT_TAG_CHARGE_ENERGY = 10,
	ABILITY_EFFECT_TAG_CREATION = 11,
	WEAPON_NORMAL_ATK_ABILITY = 0,
	WEAPON_SKILL_ABILITY = 1,
	WEAPON_SKILL_ABILITY2 = 2,
	ULTIMATE_ABILITY = 3,
	APPEAR_ABILITY = 4,
	DEAD_ABILITY = 5,
	EXPLORE_ABILITY = 6,
	EXPLORE_ABILITY2 = 7,
	RULE_ABILITY = 8,
	CHAIN_ABILITY = 9,
	SRC_TYPE_ABILITY = 1,
	SRC_TYPE_BUFF = 2,
	SRC_TYPE_CREATION = 3,
	COMBAT_CONTEXT_TYPE_ABILITY = 0,
	TAG_ABILITY_ELEMENT = 125904,
	CLIENT_COMBAT_CONTEXT_ID_MIN = 0,
	SKILL_STATE_CHARM = 3,
	SKILL_STATE_KNOCK_BACK = 5,
	SKILL_STATE_KNOCK_UP = 6,
	SKILL_STATE_BOSS_SPECIAL_BREAK_FALL = 8,
	SKILL_STATE_APPEAR_DASH = 9,
	SKILL_STATE_BOSS_SPECIAL_LAND = 10,
	ATTACK_TYPE_SPECIAL = 2,
	DAMAGE_UI_TAG_PALSY = 1,
	DAMAGE_UI_TAG_FROZEN = 2,
	SPECIFIC_ABILITY_INDEX_CLIMB = 1,
	SPECIFIC_ABILITY_INDEX_SWIM = 3,
	SPECIFIC_ABILITY_INDEX_WATERFALL = 4,
	SPECIFIC_ABILITY_INDEX_FLY = 5,
	SPECIFIC_ABILITY_INDEX_MAX = 5,
	TRIGGER_ON_BUFF_REFRESH = "onBuffRefreshIds",
	TRIGGER_ON_BUFF_DESTROY = "onBuffDestroyIds",
	TRIGGER_ON_BUFF_THINK = "onBuffThinkIds",
	TRIGGER_ON_BUFF_START = "onBuffStartIds",
	TRIGGER_ON_ABILITY_REMOVED = "onAbilityRemovedIds",
	TRIGGER_ON_ABILITY_ADDED = "onAbilityAddedIds",
	TRIGGER_ON_PROJECT_TICK = "onProjectileTickIds",
	TRIGGER_ON_PROJECT_SEGMENT_FINISH = "onProjectileSegmentFinishIds",
	TRIGGER_ON_PROJECT_GROUNDED = "onProjectileGroundedIds",
	TRIGGER_ON_PROJECT_FINISH = "onProjectileFinishIds",
	TRIGGER_ON_PROJECT_START = "onProjectileStartIds",
	TRIGGER_ON_PROJECT_HIT = "onProjectileHitIds",
	TRIGGER_ON_ABILITY_END = "onAbilityEndIds",
	TRIGGER_ON_ABILITY_CAST = "onAbilityCastIds",
	BUFF_EGG_MODE_SPEED_DOWN_BUFF = 6005027,
	BUFF_CATCH_ROGUE_NEXT_SUCCESS = 11139,
	BUFF_GRAB_EGG_ROOM_SOV = 1114401,
	BUFF_INCREASE_SIGHT_OF_VIEW = 11144,
	BUFF_REDUCE_STAMINA_RECOVERY_RATE_ID = 920000201,
	BUFF_10222_SWITCH_SUBMODEL_ID = 2122201,
	BUFF_BUBBLE_FREEZE_HP_ID = 920002001,
	BUFF_BREAK_FALL_ID = 10005,
	BUFF_BREAK_ID = 10003,
	BUFF_STACK_HIGH_LEVEL_OVERRIDE = 5,
	BUFF_STACK_TIME_MAX_REFRESH = 4,
	BUFF_STACK_STACKABLE_TIME_REFRESH = 3,
	BUFF_STACK_STACKABLE = 2,
	BUFF_STACK_OVERRIDE = 1,
	BUFF_MERGE_SRC_CASTER_ABILITY = 3,
	BUFF_MERGE_SRC_CASTER = 2,
	BUFF_MERGE_SRC_ALL = 1,
	BUFF_MERGE_SRC_NONE = 0,
	BUFF_ADD_FAILED_CONFLICT = 4,
	BUFF_ADD_FAILED_IMMUNE = 3,
	BUFF_ADD_FAILED_BUFF_MAX_SIZE = 2,
	BUFF_ADD_FAILED_BUFF_NOT_EXIST = 1,
	BUFF_ADD_FAILED_NONE = 0,
	ABILITY_CAST_FAILED_NOT_IN_TAKEROOT = 26,
	NOTIFY_STATE_TIME_NODE_ENTER = 1,
	ACTION_TIMELINE_CMD_RESET = 4,
	ABILITY_CAST_FAILED_CALL_FRIENDS = 23,
	ABILITY_CAST_FAILED_NOT_IN_BURROW = 22,
	ABILITY_CAST_FAILED_IN_BURROW = 21,
	ACTION_TIMELINE_CMD_NONE = 0,
	PET_EXPLORE_ABILITY_COUNT = 2,
	ABILITY_CAST_FAILED_IN_DEAD = 16,
	ABILITY_CAST_ERR_ITEM_SKILL_COUNT = 15,
	ABILITY_CAST_FAILED_IN_FLY = 14,
	ABILITY_CAST_FAILED_NOACTOR = 13,
	ABILITY_CAST_OUT_SEARCH_RANGE = 12,
	ABILITY_CAST_NOT_ENOUGH_SP = 11,
	ABILITY_CAST_NOT_ENOUGH_EP = 10,
	ABILITY_CAST_COMBAT_STATE_FORBID = 9,
	ABILITY_CAST_INTERRUPT_CASTING_FAILED = 7,
	ABILITY_CAST_COMBO_CHECK_FAILED = 6,
	ABILITY_CAST_FAILED_IN_CD = 5,
	ABILITY_CAST_TARGET_NOT_EXIST = 4,
	ABILITY_CAST_IS_CASTING = 3,
	ABILITY_CAST_ABILITY_NOT_EXIST = 2,
	ABILITY_CAST_FAILED_FAULT = 1,
	TIMELINE_EVENT_ENTER = "EventEnter",
	TIMELINE_EVENT_NONE = "",
	SPECIFIC_ABILITY_INDEX_GLIDE = 2,
	TRIGGER_ON_BUFF_LAYER_CHANGE = "onBuffLayerChangeIds",
	DAMAGE_UI_TAG_REMOVE_BUFF = 3,
	MAX_ABILITY_LEVEL = 80,
	TRIGGER_ON_BUFF_INHERIT = "onBuffInheritIds",
	ATTACK_TYPE_PHYSICAL = 1,
	BUFF_DESTROY_REASON_NONE = 0,
	BUFF_PROP_LOGIC_PART_IDX = 5,
	BUFF_PROP_ABILITY_ID = 4,
	BUFF_PROP_CASTER_ID = 3,
	BUFF_PROP_LAYER = 2,
	BUFF_PROP_LEVEL = 1,
	SKILL_STATE_BREAK = 2,
	SKILL_STATE_BREAK_FALL = 1,
	SKILL_STATE_NONE = 0,
	SERVER_COMBAT_CONTEXT_ID_MAX = 32767,
	SERVER_COMBAT_CONTEXT_ID_MIN = 16384,
	CLIENT_COMBAT_CONTEXT_ID_MAX = 16383,
	MAX_ID_GEN = 4294967295,
	MIN_ID_GEN = 0,
	TAG_NONE = 0,
	ATTACK_RESULT_REFLECT = 17,
	ATTACK_RESULT_KILL_THRESHOLD = 16,
	ATTACK_RESULT_IMMUNE = 15,
	ATTACK_RESULT_SHIELD_ABSORB = 13,
	ATTACK_RESULT_NEGATIVE_IGNORE = 11,
	ATTACK_RESULT_NEGATIVE_RESIST = 10,
	ATTACK_RESULT_FALL = 9,
	ATTACK_RESULT_BESHARED = 8,
	ATTACK_RESULT_SHARE = 7,
	ATTACK_RESULT_BLOCK = 6,
	ATTACK_RESULT_REBOUND = 5,
	ATTACK_RESULT_DRAIN = 4,
	ATTACK_RESULT_MISS = 3,
	ATTACK_RESULT_CRITICAL = 2,
	ATTACK_RESULT_NORMAL = 1,
	HURT_TYPE_FORCE = 3,
	HURT_TYPE_HP_ADD = 2,
	HURT_TYPE_HP_REDUCE = 1,
	HURT_TYPE_NONE = 0,
	COMBAT_CONTEXT_TYPE_MAX = 15,
	COMBAT_CONTEXT_TYPE_CHAIN_ATTACK = 5,
	COMBAT_CONTEXT_TYPE_TAG_REACTION = 4,
	COMBAT_CONTEXT_TYPE_BUFF = 3,
	COMBAT_CONTEXT_TYPE_PROJECTILE = 2,
	COMBAT_CONTEXT_TYPE_TIMELINE = 1,
	ATTRIBUTE_SRC_TYPE_END = 44,
	ATTRIBUTE_SRC_TYPE_ROG_EGG_COMPENSATION_FIX = 44,
	ATTRIBUTE_SRC_TYPE_ROB_EGG_TALENT = 43,
	ATTRIBUTE_SRC_TYPE_PVP_TEMPLATE_EXTRA = 42,
	ATTRIBUTE_SRC_TYPE_PET_PROPERTY_EXTRA = 41,
	ATTRIBUTE_SRC_TYPE_ROB_EGG_CHIP = 40,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_10 = 39,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_9 = 38,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_8 = 37,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_7 = 36,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_6 = 35,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_5 = 34,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_4 = 33,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_3 = 32,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_2 = 31,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY_1 = 30,
	ATTRIBUTE_SRC_TYPE_PUPPET_BORN_MODIFIER = 29,
	ATTRIBUTE_SRC_TYPE_ASSIST_CARRY = 28,
	ABILITY_EFFECT_TAG_ADD_DMG = 7,
	ABILITY_EFFECT_TAG_ADD_ATK = 6,
	ABILITY_EFFECT_TAG_REDUCE_DAMAGE = 5,
	ABILITY_EFFECT_TAG_ADD_DEFENCE = 4,
	ABILITY_EFFECT_TAG_SHIELD = 3,
	ABILITY_EFFECT_TAG_HEAL = 2,
	ABILITY_EFFECT_TAG_MOVEMENT = 1,
	ABILITY_EFFECT_TAG_ATTACK = 0,
	ATTRIBUTE_SRC_TYPE_ROGUE_TALENT = 19,
	ATTRIBUTE_SRC_TYPE_CORE_CARRY_EX = 18,
	ATTRIBUTE_SRC_TYPE_CORE_CARRY = 17,
	ATTRIBUTE_SRC_TYPE_ABILITY_DYNAMIC = 16,
	ATTRIBUTE_SRC_TYPE_BE_HIT_BY_NEXT_SKILL = 15,
	ATTRIBUTE_SRC_TYPE_PET_TALENT = 14,
	ATTRIBUTE_SRC_TYPE_BUFF_CONVERSION = 13,
	ATTRIBUTE_SRC_TYPE_ROGUE_DYNAMIC = 12,
	ATTRIBUTE_SRC_TYPE_CREATION_INHERIT = 11,
	BUFF_SERIES_NORMAL_ATTACK = 9,
	BUFF_SERIES_AGAINST = 8,
	BUFF_SERIES_BREAK = 7,
	BUFF_SERIES_CRIT = 6,
	BUFF_SERIES_RECEIVE_DMG = 5,
	BUFF_SERIES_DEFENSE = 4,
	BUFF_SERIES_HEAL = 3,
	BUFF_SERIES_SHIELD = 2,
	BUFF_SERIES_ULTIMATE = 1,
	BUFF_SERIES_SKILL = 0,
	ATTRIBUTE_ID_OFFSET_CUR_MAX = 1,
	ATTRIBUTE_ID_OFFSET_XP_SCALE = 12,
	ATTRIBUTE_ID_OFFSET_XP_TEMP_MAX = 11,
	ATTRIBUTE_ID_OFFSET_XP_TEMP_CUR = 10,
	ATTRIBUTE_ID_OFFSET_XP_FORCE_SET = 9,
	ATTRIBUTE_ID_OFFSET_XP_INC_RATE_V = 8,
	ATTRIBUTE_ID_OFFSET_XP_REGEN_P = 7,
	BUFF_DESTROY_REASON_CONTROL_PET = 8,
	BUFF_DESTROY_REASON_DEATH = 7,
	BUFF_DESTROY_REASON_MIGRATE = 6,
	BUFF_DESTROY_REASON_INHERIT = 5,
	BUFF_DESTROY_REASON_PET_UN_SUMMON = 4,
	BUFF_DESTROY_REASON_ARMOR_VANISH = 3,
	BUFF_DESTROY_REASON_INTERRUPT = 2,
	BUFF_DESTROY_REASON_TIMEOUT = 1,
	RIG_TYPE_WALKING_ATTACK = 3,
	RIG_TYPE_HOOK_SPRINT = 2,
	RIG_TYPE_VINE_CHAIN = 1,
	CHECK_TYPE_ALL = 2,
	CHECK_TYPE_VOXEL = 1,
	CHECK_TYPE_ENTITY = 0,
	SWEEP_TYPE_BOX = 1,
	LX_GEOMETRY_TYPE_ANNULARSECTOR3D = 7,
	LX_GEOMETRY_TYPE_TRAPEZOID3D = 6,
	LX_GEOMETRY_TYPE_SECTOR3D = 5,
	LX_GEOMETRY_TYPE_CIRCLE3D = 4,
	LX_GEOMETRY_TYPE_BOX = 3,
	LX_GEOMETRY_TYPE_CAPSULE = 2,
	LX_GEOMETRY_TYPE_SPHERE = 1,
	LX_GEOMETRY_TYPE_SEGMENT = 0,
	LX_GEOMETRY_TYPE_INVALID = -1,
	ACTOR_RELATION_MODE_FORBID = 3,
	ACTOR_RELATION_MODE_ALLOW = 2,
	ACTOR_RELATION_MODE_MUST = 1,
	ACTION_MASK_COUNT = 12,
	ACTION_MASK_KEY_FRAME_BACKSWING = 12,
	ACTION_MASK_IN_HIT_BACKSWING = 11,
	ACTION_MASK_CANCELLABLE = 10,
	ACTION_MASK_CAN_MOVE = 9,
	ACTION_MASK_CAN_ROTATE = 8,
	ACTION_MASK_IN_HIT = 7,
	ACTION_MASK_IN_ATTACK = 6,
	ACTION_MASK_IN_SKILL = 5,
	ACTION_MASK_IN_COMBO = 4,
	ACTION_MASK_IN_CAST = 3,
	ACTION_MASK_IN_BACKSWING = 2,
	ACTION_MASK_DISABLE_COMBO_INPUT = 1,
	ACTION_MASK_INVALID = -1,
	POS_ROOT_POS = "RootPos",
	POS_ON_HIT_POSITION = "HitPos",
	DAMAGE_TYPE_MAG = 3,
	DAMAGE_TYPE_PHY = 2,
	DAMAGE_TYPE_PURE = 1,
	DAMAGE_TYPE_NONE = 0,
	ABILITY_MAX_LOOP_CNT = 8,
	CONDITION_TYPE_GRASS_GROW_FLOWER = 11,
	CONDITION_TYPE_GROW_UP = 10,
	CONDITION_TYPE_PLANT_GRASS = 9,
	CONDITION_TYPE_FORCE_IGNITE = 8,
	CONDITION_TYPE_ACTION_WATER = 7,
	CONDITION_TYPE_IGNITE = 6,
	CONDITION_TYPE_ACTION_WET = 5,
	CONDITION_TYPE_BREAK = 4,
	CONDITION_TYPE_BLOW = 3,
	CONDITION_TYPE_CONDUCT = 2,
	CONDITION_TYPE_FROZE = 1,
	CONDITION_TYPE_NONE = 0,
	EFFECT_TARGET_VOXEL = "VOXEL",
	EFFECT_TARGET_ELEMENT = "ELEMENT",
	EFFECT_TARGET_ACTOR = "ACTOR",
	EFFECT_TARGET_NONE = "",
	LEARN_ABILITY_TYPE_TEMP = true,
	LEARN_ABILITY_TYPE_NORMAL = false,
	ABILITY_CAST_FAILED_CUR_STATE_FORBIDDEN = 34,
	LEVEL_CURVE_TYPES = {
		"cd",
		"epCost",
		"actionTimelineId"
	},
	TIMELINE_LAYER_INT_TO_STR = {
		"Base",
		"Additive",
		"Parallel"
	},
	TIMELINE_LAYER_STR_TO_INT = {
		Parallel = 3,
		Base = 1,
		Additive = 2
	},
	ABILITY_CAST_FAILED_REASONS = {
		"failed_fault",
		"ability_not_exist",
		"is_casting",
		"target_not_exist",
		"failed_in_cd",
		"combo_check_failed",
		"interrupt_casting_failed",
		"occupied",
		"combat_state_forbid",
		"not_enough_ep",
		"not_enough_sp",
		"out_search_range",
		"failed_noactor",
		"failed_in_fly",
		"err_item_skill_count",
		"failed_in_dead",
		"failed_not_enough_stamina",
		"failed_state_check_failed",
		"push_skill",
		"failed_pet_not_found",
		"failed_in_burrow",
		"failed_not_in_burrow",
		"failed_call_friends",
		"ability_not_enough_item",
		"failed_in_take_root",
		"failed_not_in_take_root",
		"failed_not_in_special_state",
		"failed_rouge_dungeon_not_in_combat",
		"failed_rogue_ep_not_enough",
		"auto_cast",
		"failed_loaded_cnt",
		"failed_back_not_in_combat",
		"failed_not_enough_water",
		"failed_cur_state_check"
	},
	CAMERA_IMPULSE_DIR_ENUM = {
		CameraDir = 0,
		ActorDir = 2,
		WorldDir = 1
	},
	ATTRIBUTE_SRC_TYPE_NAMES = {
		"level",
		"buff",
		"pet_property",
		"buff_dynamic",
		"buff_layer",
		"entry",
		"space",
		"appearance",
		"buffConditional",
		"buff_series_cnt",
		"creation_inherit",
		"rouge_dynamic",
		"buff_conversion",
		"pet_talent",
		"hit_by_next_skill",
		"ability_dynamic",
		"core_carry",
		"core_carry_ex",
		"rogue_talent",
		"single_world_hp_scale",
		"rob_egg_equip",
		"first_attack_calc",
		"core_carry_conversion",
		"pet_primary_property",
		"pet_resonance",
		"pet_jerelry",
		"assist_carry_ex",
		"assist_carry",
		"puppet_born_modifier",
		"assist_carry_1",
		"assist_carry_2",
		"assist_carry_3",
		"assist_carry_4",
		"assist_carry_5",
		"assist_carry_6",
		"assist_carry_7",
		"assist_carry_8",
		"assist_carry_9",
		"assist_carry_10",
		"rob_egg_chip",
		"pet_property_extra",
		"pvp_template_extra",
		"rob_egg_talent",
		"rog_egg_compensation_fix"
	},
	CHARACTER_BUFF_TYPE = {
		TRIGGER_ACTION = 2,
		CONDITIONAL_ATTR = 1
	},
	ABILITY_SKILL_TYPE = {
		CHARGE = "Charge",
		SWITCH = "Switch",
		NORMAL = "Normal"
	},
	BUFF_DESTROY_REASON_PARSER = {
		controlPet = 8,
		death = 7,
		migrate = 6,
		petUnSummon = 4,
		armorVanish = 3,
		interrupt = 2,
		timeout = 1
	},
	EnumAbilityType = {
		Item = 6,
		Support = 5,
		Ultimate = 4,
		Appear = 3,
		Skill = 2,
		Attack = 1,
		Explore = 9,
		CHAIN = 8,
		PASSIVE = 7
	},
	TAG_INFLAMMABLE = bit.lshift(1, 1),
	TAG_CONDUCTIVE = bit.lshift(1, 2),
	TAG_FRAGILE = bit.lshift(1, 3),
	TAG_WATERPOOL = bit.lshift(1, 4),
	TAG_FRAGMENT = bit.lshift(1, 5),
	TAG_BURNING = bit.lshift(1, 6),
	TAG_ENVWATERPOOL = bit.lshift(1, 7),
	TAG_ENVGRASS = bit.lshift(1, 8),
	TAG_ENVICE = bit.lshift(1, 9),
	TAG_ENVGROUND = bit.lshift(1, 10),
	TAG_ELECTRICITY = bit.lshift(1, 11),
	TAG_WET = bit.lshift(1, 12),
	TAG_PLANT_GRASS = bit.lshift(1, 13),
	TAG_SEED = bit.lshift(1, 14),
	TAG_NORMAL_GRASS = bit.lshift(1, 15),
	TAG_GRASS_GROW_FLOWER = bit.lshift(1, 16),
	TAG_MATERIAL_END = bit.lshift(1, 31)
}

AbilityConst.SPECIFIC_ABILITY_INDEX_2_NAME = {
	[AbilityConst.SPECIFIC_ABILITY_INDEX_CLIMB] = "canClimb",
	[AbilityConst.SPECIFIC_ABILITY_INDEX_GLIDE] = "canGlide",
	[AbilityConst.SPECIFIC_ABILITY_INDEX_SWIM] = "canSwim",
	[AbilityConst.SPECIFIC_ABILITY_INDEX_WATERFALL] = "canClimbWaterfall",
	[AbilityConst.SPECIFIC_ABILITY_INDEX_FLY] = "canFly"
}
AbilityConst.SPECIFIC_ABILITY_NAME_2_INDEX = {
	canSwim = 3,
	canGlide = 2,
	canClimb = 1,
	canFly = 5,
	canClimbWaterfall = 4
}
AbilityConst.CONDITION_TYPE_PARSER = {
	none = 0,
	froze = AbilityConst.CONDITION_TYPE_FROZE,
	conduct = AbilityConst.CONDITION_TYPE_CONDUCT,
	blow = AbilityConst.CONDITION_TYPE_BLOW,
	["break"] = AbilityConst.CONDITION_TYPE_BREAK,
	actWet = AbilityConst.CONDITION_TYPE_ACTION_WET,
	ignite = AbilityConst.CONDITION_TYPE_IGNITE,
	actWater = AbilityConst.CONDITION_TYPE_ACTION_WATER,
	forceIgnite = AbilityConst.CONDITION_TYPE_FORCE_IGNITE,
	plantGrass = AbilityConst.CONDITION_TYPE_PLANT_GRASS,
	grassGrowFlower = AbilityConst.CONDITION_TYPE_GRASS_GROW_FLOWER
}
AbilityConst.ABILITY_TYPE_NAME = {
	[AbilityConst.WEAPON_SKILL_ABILITY] = "ABILITY_NAME_SKILL",
	[AbilityConst.WEAPON_SKILL_ABILITY2] = "ABILITY_NAME_SKILL",
	[AbilityConst.WEAPON_NORMAL_ATK_ABILITY] = "ABILITY_NAME_NORMAL",
	[AbilityConst.ULTIMATE_ABILITY] = "ABILITY_NAME_ULTIMATE",
	[AbilityConst.APPEAR_ABILITY] = "ABILITY_NAME_APPEAR",
	[AbilityConst.EXPLORE_ABILITY] = "ABILITY_NAME_EXPLORE",
	[AbilityConst.EXPLORE_ABILITY2] = "ABILITY_NAME_EXPLORE"
}
AbilityConst.CONDITION_CHECK_TYPE_MAP = {
	[AbilityConst.CONDITION_TYPE_CONDUCT] = AbilityConst.CHECK_TYPE_ALL,
	[AbilityConst.CONDITION_TYPE_FROZE] = AbilityConst.CHECK_TYPE_ALL,
	[AbilityConst.CONDITION_TYPE_ACTION_WATER] = AbilityConst.CHECK_TYPE_ALL,
	[AbilityConst.CONDITION_TYPE_ACTION_WET] = AbilityConst.CHECK_TYPE_ALL,
	[AbilityConst.CONDITION_TYPE_IGNITE] = AbilityConst.CHECK_TYPE_ALL,
	[AbilityConst.CONDITION_TYPE_FORCE_IGNITE] = AbilityConst.CHECK_TYPE_ALL,
	[AbilityConst.CONDITION_TYPE_BLOW] = AbilityConst.CHECK_TYPE_ENTITY,
	[AbilityConst.CONDITION_TYPE_BREAK] = AbilityConst.CHECK_TYPE_ENTITY,
	[AbilityConst.CONDITION_TYPE_PLANT_GRASS] = AbilityConst.CHECK_TYPE_VOXEL,
	[AbilityConst.CONDITION_TYPE_GROW_UP] = AbilityConst.CHECK_TYPE_ENTITY
}
AbilityConst.CONDITION_NUM_TO_STR = {
	[AbilityConst.CONDITION_TYPE_CONDUCT] = "conduct",
	[AbilityConst.CONDITION_TYPE_FROZE] = "froze",
	[AbilityConst.CONDITION_TYPE_ACTION_WATER] = "actWater",
	[AbilityConst.CONDITION_TYPE_ACTION_WET] = "actWet",
	[AbilityConst.CONDITION_TYPE_IGNITE] = "ignite",
	[AbilityConst.CONDITION_TYPE_FORCE_IGNITE] = "forceIgnite",
	[AbilityConst.CONDITION_TYPE_PLANT_GRASS] = "plantGrass",
	[AbilityConst.CONDITION_TYPE_GRASS_GROW_FLOWER] = "grassGrowFlower"
}
AbilityConst.TAG_NUM_TO_STR = {
	[AbilityConst.TAG_INFLAMMABLE] = "inflammable",
	[AbilityConst.TAG_CONDUCTIVE] = "conductive",
	[AbilityConst.TAG_FRAGILE] = "fragile",
	[AbilityConst.TAG_WATERPOOL] = "waterPool",
	[AbilityConst.TAG_FRAGMENT] = "fragment",
	[AbilityConst.TAG_BURNING] = "burning",
	[AbilityConst.TAG_ELECTRICITY] = "electricity",
	[AbilityConst.TAG_SEED] = "seed"
}
AbilityConst.TAG_STR_TO_NUM = {
	none = AbilityConst.TAG_NONE,
	inflammable = AbilityConst.TAG_INFLAMMABLE,
	conductive = AbilityConst.TAG_CONDUCTIVE,
	fragile = AbilityConst.TAG_FRAGILE,
	waterPool = AbilityConst.TAG_WATERPOOL,
	fragment = AbilityConst.TAG_FRAGMENT,
	burning = AbilityConst.TAG_BURNING,
	electricity = AbilityConst.TAG_ELECTRICITY,
	plantGrass = AbilityConst.TAG_PLANT_GRASS,
	envWaterPool = AbilityConst.TAG_ENVWATERPOOL,
	envGrass = AbilityConst.TAG_ENVGRASS,
	envIce = AbilityConst.TAG_ENVICE,
	envGround = AbilityConst.TAG_ENVGROUND,
	seed = AbilityConst.TAG_SEED,
	grassGroupFlower = AbilityConst.TAG_GRASS_GROW_FLOWER,
	normalGrass = AbilityConst.TAG_NORMAL_GRASS
}
AbilityConst.TAG_ABILITY_ELEMENT_LIST = {
	AbilityConst.TAG_WATERPOOL,
	AbilityConst.TAG_BURNING,
	AbilityConst.TAG_ENVWATERPOOL,
	AbilityConst.TAG_ENVGRASS,
	AbilityConst.TAG_ENVICE,
	AbilityConst.TAG_ELECTRICITY,
	AbilityConst.TAG_PLANT_GRASS,
	AbilityConst.TAG_SEED,
	AbilityConst.TAG_NORMAL_GRASS,
	AbilityConst.TAG_GRASS_GROW_FLOWER
}
AbilityConst.ACTION_MASK_PARSER = {
	disableComboInput = AbilityConst.ACTION_MASK_DISABLE_COMBO_INPUT,
	inSkill = AbilityConst.ACTION_MASK_IN_SKILL,
	inAttack = AbilityConst.ACTION_MASK_IN_ATTACK,
	inHit = AbilityConst.ACTION_MASK_IN_HIT,
	inBackswing = AbilityConst.ACTION_MASK_IN_BACKSWING,
	inCast = AbilityConst.ACTION_MASK_IN_CAST,
	inCombo = AbilityConst.ACTION_MASK_IN_COMBO,
	canRotate = AbilityConst.ACTION_MASK_CAN_ROTATE,
	canMove = AbilityConst.ACTION_MASK_CAN_MOVE,
	cancellable = AbilityConst.ACTION_MASK_CANCELLABLE,
	inHitBackswing = AbilityConst.ACTION_MASK_IN_HIT_BACKSWING
}
AbilityConst.LX_GEOMETRY_TYPE_PARSER = {
	Invalid = -1,
	Segment = AbilityConst.LX_GEOMETRY_TYPE_SEGMENT,
	Sphere = AbilityConst.LX_GEOMETRY_TYPE_SPHERE,
	Capsule = AbilityConst.LX_GEOMETRY_TYPE_CAPSULE,
	Box = AbilityConst.LX_GEOMETRY_TYPE_BOX,
	Circle3D = AbilityConst.LX_GEOMETRY_TYPE_CIRCLE3D,
	Sector3D = AbilityConst.LX_GEOMETRY_TYPE_SECTOR3D,
	Trapezoid3D = AbilityConst.LX_GEOMETRY_TYPE_TRAPEZOID3D,
	AnnularSector3D = AbilityConst.LX_GEOMETRY_TYPE_ANNULARSECTOR3D
}
AbilityConst.SWEEP_GEOMETRY_TYPE_PARSE = {
	BoxSweep = AbilityConst.SWEEP_TYPE_BOX
}
AbilityConst.WEAPON_ABILITY_MAP = {
	[AbilityConst.WEAPON_NORMAL_ATK_ABILITY] = "normalAtkAbilityId",
	[AbilityConst.WEAPON_SKILL_ABILITY] = "skillAbilityId",
	[AbilityConst.WEAPON_SKILL_ABILITY2] = "skillAbility2Id",
	[AbilityConst.ULTIMATE_ABILITY] = "comboAbilityId",
	[AbilityConst.APPEAR_ABILITY] = "appearAbilityId",
	[AbilityConst.DEAD_ABILITY] = "deadAbility"
}
AbilityConst.WEAPON_ABILITY_LIST = {
	AbilityConst.WEAPON_NORMAL_ATK_ABILITY,
	AbilityConst.WEAPON_SKILL_ABILITY,
	AbilityConst.WEAPON_SKILL_ABILITY2,
	AbilityConst.ULTIMATE_ABILITY,
	AbilityConst.APPEAR_ABILITY
}
AbilityConst.EGGMAN_ID_TO_EGG_PATTERN = {
	[70100003] = 4,
	[70100002] = 3,
	[70100001] = 2,
	[70100004] = 5,
	[70100000] = 1
}
AbilityConst.COMBAT_EVENT_ON_ARMOR_BLOCK_DAMAGE = "onArmorBlockDamage"
AbilityConst.COMBAT_EVENT_ON_SHIELD_ABSORB_DAMAGE = "onShieldAbsorbDamage"
AbilityConst.COMBAT_EVENT_END_CHARGE = "onEndCharge"
AbilityConst.COMBAT_EVENT_RECEIVE_DAMAGE = "onReceiveDamage"
AbilityConst.COMBAT_EVENT_PET_RECEIVE_DAMAGE = "onPetReceiveDamage"
AbilityConst.COMBAT_EVENT_ON_ENTER_TRAP = "onEnterTrap"
AbilityConst.COMBAT_EVENT_ON_LEAVE_TRAP = "onLeaveTrap"
AbilityConst.COMBAT_EVENT_DEAD = "onDead"
AbilityConst.COMBAT_EVENT_ATTACK = "onAttack"
AbilityConst.COMBAT_EVENT_RECEIVE_BE_ATTACKED = "onReceiveBeAttacked"
AbilityConst.COMBAT_EVENT_ATTRIBUTE_CHANGE = "onAttributeChange"
AbilityConst.COMBAT_EVENT_PET_ATTRIBUTE_CHANGE = "onPetAttributeChange"
AbilityConst.COMBAT_EVENT_ENTER_COMBAT = "onEnterCombat"
AbilityConst.COMBAT_EVENT_LEAVE_COMBAT = "onLeaveCombat"
AbilityConst.COMBAT_EVENT_CAST_ABILITY = "onCastAbility"
AbilityConst.COMBAT_EVENT_STUN_ON_COLLISION = "onStunOnCollision"
AbilityConst.COMBAT_EVENT_ON_ATTACK_HP_ZERO = "onAttackHpZero"
AbilityConst.COMBAT_EVENT_ON_SKILL_MOVE_PATH_ENCLOSED = "onSkillMovePathEnclosed"
AbilityConst.COMBAT_EVENT_ON_INTERACT_PROJ = "onInteractProj"
AbilityConst.COMBAT_EVENT_ON_SKILL_MOVE_BLOCKED = "onSkillMoveBlocked"
AbilityConst.COMBAT_EVENT_ON_SKILL_HOOK_FAIL = "onSkillHookFail"
AbilityConst.COMBAT_EVENT_ON_SKILL_HOOK_SUCCESS = "onSkillHookSuccess"
AbilityConst.COMBAT_EVENT_ON_SKILL_HOOK_BE_HIT = "onSkillHookBeHit"
AbilityConst.COMBAT_EVENT_ON_SKILL_HOOK_END = "onSkillHookEnd"
AbilityConst.COMBAT_EVENT_ON_SKILL_HOOK_EXIT = "onSkillHookExit"
AbilityConst.COMBAT_EVENT_ON_ASYNC_RANDOM_INT_GENNED = "onAsyncRandomIntGenned"
AbilityConst.COMBAT_EVENT_ON_RE_PRESS_SKILL_SLOT = "onRePressSkillSlot"
AbilityConst.COMBAT_EVENT_ON_SKILL_AUTO_AIM = "onSkillAutoAim"
AbilityConst.COMBAT_EVENT_ON_SKILL_MOTION_STATE_CHANGE = "onSkillMotionStateChange"
AbilityConst.COMBAT_EVENT_ON_MOVE_BY_INPUT = "onMoveByInput"
AbilityConst.COMBAT_EVENT_ON_PET_SUMMON = "onPetSummon"
AbilityConst.COMBAT_EVENT_ON_PET_UNSUMMON = "onPetUnSummon"
AbilityConst.COMBAT_EVENT_ON_OLD_PET_SWITCH = "onOldPetSwitch"
AbilityConst.COMBAT_EVENT_ON_NEW_PET_SWITCH = "onNewPetSwitch"
AbilityConst.COMBAT_EVENT_PUPPET_SKILL_HIT_DISTANCE = "onPuppetSkillHitDistance"
AbilityConst.COMBAT_EVENT_ON_BURROW_STATE_CHANGE = "onBurrowStateChange"
AbilityConst.COMBAT_EVENT_ON_TAKE_ROOT_STATE_CHANGE = "onTakeRootStateChange"
AbilityConst.COMBAT_EVENT_ON_LATERAL_ATTACK_STATE_CHANGE = "onLateralAttackStateChange"
AbilityConst.COMBAT_EVENT_ON_SERVER_CACHE_VAL_CHANGE = "onServerCacheValChange"
AbilityConst.COMBAT_EVENT_ON_ABILITY_END = "onAbilityEnd"
AbilityConst.COMBAT_EVENT_ON_ABILITY_DISABLE_RETURN = "onAbilityDisableReturn"
AbilityConst.COMBAT_EVENT_ON_POST_ATTACK = "onPostAttack"
AbilityConst.COMBAT_EVENT_ON_KILL = "onKill"
AbilityConst.COMBAT_EVENT_ON_BUFF_SERIES_CNT_CHANGE = "onBuffSeriesCntChange"
AbilityConst.COMBAT_EVENT_ON_CONDITIONAL_BUFF_OWNER_STATE_CHANGE = "onConditionalBuffOwnerStateChange"
AbilityConst.COMBAT_EVENT_ON_BUFF_TAG_CHANGE = "onBuffTagChange"
AbilityConst.COMBAT_EVENT_ON_SHIELD_CHANGE = "onShieldChange"
AbilityConst.COMBAT_EVENT_ON_OVER_HEAL = "onOverHeal"
AbilityConst.COMBAT_EVENT_ON_HEAL = "onHeal"
AbilityConst.COMBAT_EVENT_CREATE_PROJ_FROM_ANI_EVENT = "onCreateProjFromAniEvent"
AbilityConst.COMBAT_EVENT_ON_CACHE_VAL_CHANGE = "onCacheValChange"
AbilityConst.COMBAT_EVENT_ON_CLIENT_DATA_PREPARED = "onClientDataPrepared"
AbilityConst.COMBAT_EVENT_ON_ADD_ABILITY_IMPULSE = "onAddAbilityImpulse"
AbilityConst.COMBAT_EVENT_ON_ENTER_SPECIAL_RIDE_MODE = "onEnterSpecialRideMode"
AbilityConst.COMBAT_EVENT_ON_PLAYER_SWITCH_CONTROL = "onPlayerSwitchControl"
AbilityConst.COMBAT_EVENT_ON_PAWN_MOVED_DISTANCE_REACH_THRESHOLD = "onPawnMovedDistanceReachThreshold"
AbilityConst.COMBAT_EVENT_ON_PAWN_MOVE_INPUT_CHANGE = "onPawnMoveInputChange"
AbilityConst.COMBAT_EVENT_ON_OVER_DAMAGE = "onOverDamage"
AbilityConst.COMBAT_EVENT_ON_WATER_ABSORB_DATA_READY = "onWaterAbsorbDataReady"
AbilityConst.COMBAT_EVENT_ON_WATER_ABSORB = "onWaterAbsorb"
AbilityConst.COMBAT_EVENT_ON_FLY_STATE_CHANGE = "onFlyStateChange"
AbilityConst.COMBAT_EVENT_ON_INFLATE_STATE_CHANGE = "onInfalteStateChange"
AbilityConst.COMBAT_EVENT_ON_LOCKED_TARGET_CHANGE = "onLockedTargetChange"
AbilityConst.COMBAT_EVENT_ON_ENEMY_BREAK = "onEnemyBreak"
AbilityConst.COMBAT_EVENT_ON_SKILL_GLIDING_STATE_CHANGE = "onSkillGlidingStateChange"
AbilityConst.COMBAT_EVENT_ON_ADD_NEW_BUFF = "onAddNewBuff"
AbilityConst.COMBAT_EVENT_ON_MERGE_BUFF = "onMergeBuff"
AbilityConst.COMBAT_EVENT_ON_ADD_BUFF_ON_TARGET = "onAddBuffOnTarget"
AbilityConst.COMBAT_EVENT_ON_ADD_ECS_BUFF_ON_TARGET = "onAddEcsBuffOnTarget"
AbilityConst.COMBAT_EVENT_ON_SYNC_VOXEL_NUM = "onSyncVoxelNum"
AbilityConst.COMBAT_EVENT_ON_ROGUE_PERSIST_DATA_CHANGE = "onRoguePersistDataChange"
AbilityConst.COMBAT_EVENT_ON_CALL_CLIENT_CALLBACK = "onCallClientCallback"
AbilityConst.COMBAT_EVENT_POST_RECEIVE_DAMAGE = "onPostReceiveDamage"
AbilityConst.COMBAT_EVENT_ON_ROGUE_COIN_CHANGE = "onRogueCoinChange"
AbilityConst.COMBAT_EVENT_ON_CHARACTER_STATE_CHANGE = "onCharacterStateChange"
AbilityConst.COMBAT_EVENT_ON_IMMUNE_TO_DAMAGE = "onImmuneToDamage"
AbilityConst.COMBAT_EVENT_ON_RARITY_BUFF_LAYER_CHANGE = "onRarityBuffLayerChange"
AbilityConst.COMBAT_EVENT_ON_PET_LEAVE_CONTROL = "onPetLeaveControl"
AbilityConst.COMBAT_EVENT_ON_PET_ENTER_CONTROL = "onPetEnterControl"
AbilityConst.COMBAT_EVENT_TRANSFER_HEAL = "onTransferHeal"
AbilityConst.COMBAT_EVENT_TRANSFER_OVER_HEAL = "onTransferOverHeal"
AbilityConst.COMBAT_EVENT_ON_CASTER_OVER_HEAL = "onCasterOverHeal"
AbilityConst.COMBAT_EVENT_ON_TRIGGER_PERFECT_COUNTER = "onTriggerPerfectCounter"
AbilityConst.COMBAT_EVENT_BE_PERFECT_COUNTERED = "BePerfectCountered"
AbilityConst.COMBAT_EVENT_BE_NORMAL_COUNTERED = "BeNormalCountered"
AbilityConst.COMBAT_EVENT_ON_CUSTOM_HIT_BOX_BE_ATTACKED = "OnCustomHitBoxBeAttacked"
AbilityConst.COMBAT_EVENT_ON_ACTION_MASK_CHANGE = "OnActionMaskChange"
AbilityConst.COMBAT_EVENT_ON_ABILITY_STATE_CHANGE = "OnAbilityStateChange"
AbilityConst.COMBAT_EVENT_ON_CREATION_POST_ATTACK = "onCreationPostAttack"
AbilityConst.COMBAT_EVENT_ON_NOTIFY_FOLLOW_PHANTOM = "onNotifyFollowPhantom"
AbilityConst.COMBAT_EVENT_ON_CS_PROJECTILE_HIT = "onCSProjectileHit"
AbilityConst.COMBAT_EVENT_ON_COST_EP = "onCostEp"
AbilityConst.COMBAT_EVENT_ON_FIRST_ATTACK_ATTR_CALC = "onFirstAttackAttrCalc"
AbilityConst.COMBAT_EVENT_ON_ENTER_AIM_SENSE = "onEnterAimSense"
AbilityConst.COMBAT_EVENT_ON_ABILITY_BACK_SWING = "onAbilityBackSwing"
AbilityConst.COMBAT_EVENT_ON_PET_LIST_CHANGE = "onPetListChange"
AbilityConst.COMBAT_EVENT_ON_PLAYER_EGG_MODE_CHANGE = "onEggModeChange"
AbilityConst.COMBAT_EVENT_ON_BAG_WEIGHT_LEVEL_CHANGE = "onBagWeightLevelChange"
AbilityConst.COMBAT_EVENT_ON_ROB_EGG_BAG_ITEM_CHANGE = "onRobEggBagItemChange"
AbilityConst.COMBAT_EVENT_ON_MOVE_CHANGE = "onMoveChange"
AbilityConst.COMBAT_EVENT_ON_MODIFY_DAMAGE = "onModifyDamage"
AbilityConst.COMBAT_EVENT_ON_MERGE_ATTACK_CALC_RESULT = "onMergeAttackCalcResult"
AbilityConst.COMBAT_EVENT_ON_EGG_MAN_MODE_CHANGE = "onEggManModeChange"
AbilityConst.COMBAT_EVENT_ON_FREE_AIM_CONFIRM_BTN_CLICKED = "onFreeAimConfirmBtnClicked"
AbilityConst.COMBAT_EVENT_ON_FREE_AIM_CANCEL_BTN_CLICKED = "onFreeAimCancelBtnClicked"
AbilityConst.COMBAT_EVENT_ON_ENT_BE_CARRIED_STATE_CHANGE = "onEntBeCarriedStateChange"
AbilityConst.COMBAT_EVENT_ON_LIFE_STATE_CHANGE = "onLifeStateChange"
AbilityConst.COMBAT_EVENT_ON_SHAPE_SHIFT_MODEL_REFRESHED = "onShapeShiftModelRefreshed"
AbilityConst.COMBAT_EVENT_ON_BUFF_LIFE = "onBuffLife"
AbilityConst.ATTACK_FORCE_KNOCK_NONE = 100
AbilityConst.ATTACK_FORCE_KNOCK_SHAKE = 0
AbilityConst.ATTACK_FORCE_KNOCK_LIGHT = 1
AbilityConst.ATTACK_FORCE_KNOCK_HEAVY = 2
AbilityConst.ATTACK_FORCE_KNOCK_UP = 3
AbilityConst.ATTACK_FORCE_KNOCK_STAND = -2
AbilityConst.ATTACK_FORCE_TO_TIMELINE_NAME = {
	[AbilityConst.ATTACK_FORCE_KNOCK_NONE] = "hitTimelineIdNone",
	[AbilityConst.ATTACK_FORCE_KNOCK_SHAKE] = "hitTimelineIdHitShake",
	[AbilityConst.ATTACK_FORCE_KNOCK_LIGHT] = "hitTimelineIdHitL",
	[AbilityConst.ATTACK_FORCE_KNOCK_HEAVY] = "hitTimelineIdHitH",
	[AbilityConst.ATTACK_FORCE_KNOCK_STAND] = "hitTimelineIdHitStand",
	[AbilityConst.ATTACK_FORCE_KNOCK_UP] = "hitTimelineIdHitThrow"
}
AbilityConst.ATTACK_BREAK_FORCE_TO_TIMELINE_NAME = {
	[AbilityConst.ATTACK_FORCE_KNOCK_NONE] = "breakHitTimelineIdNone",
	[AbilityConst.ATTACK_FORCE_KNOCK_SHAKE] = "breakHitTimelineIdHitShake",
	[AbilityConst.ATTACK_FORCE_KNOCK_LIGHT] = "breakHitTimelineIdHitL",
	[AbilityConst.ATTACK_FORCE_KNOCK_HEAVY] = "breakHitTimelineIdHitH",
	[AbilityConst.ATTACK_FORCE_KNOCK_STAND] = "breakHitTimelineIdHitStand",
	[AbilityConst.ATTACK_FORCE_KNOCK_UP] = "breakHitTimelineIdHitThrow"
}
AbilityConst.ATTACK_FLY_FORCE_TO_TIMELINE_NAME = {
	[AbilityConst.ATTACK_FORCE_KNOCK_NONE] = "flyHitTimelineIdNone",
	[AbilityConst.ATTACK_FORCE_KNOCK_SHAKE] = "flyHitTimelineIdHitShake",
	[AbilityConst.ATTACK_FORCE_KNOCK_LIGHT] = "flyHitTimelineIdHitL",
	[AbilityConst.ATTACK_FORCE_KNOCK_HEAVY] = "flyHitTimelineIdHitH",
	[AbilityConst.ATTACK_FORCE_KNOCK_STAND] = "flyHitTimelineIdHitStand",
	[AbilityConst.ATTACK_FORCE_KNOCK_UP] = "flyHitTimelineIdHitThrow"
}
AbilityConst.ATTACK_FORCE_TYPE_TO_HIT_ANIM = {
	[AbilityConst.ATTACK_FORCE_KNOCK_SHAKE] = "Hit_Shake",
	[AbilityConst.ATTACK_FORCE_KNOCK_LIGHT] = "Hit_L",
	[AbilityConst.ATTACK_FORCE_KNOCK_HEAVY] = "Hit_H",
	[AbilityConst.ATTACK_FORCE_KNOCK_STAND] = "Hit_Stand"
}
AbilityConst.ATTACK_FORCE_TYPE_TO_COUNTER_ATTACK_TYPE = {
	[AbilityConst.ATTACK_FORCE_KNOCK_LIGHT] = "counterAttackTimelineIdsHitL",
	[AbilityConst.ATTACK_FORCE_KNOCK_HEAVY] = "counterAttackTimelineIdsHitH",
	[AbilityConst.ATTACK_FORCE_KNOCK_UP] = "counterAttackTimelineIdsHitThrow"
}
AbilityConst.ABILITY_TAG_EARTHQUAKE = 1
AbilityConst.ABILITY_TAG_REMOVE_CAMOUFLAGE = 2
AbilityConst.ABILITY_TAG_MAX = 32
AbilityConst.ATTACK_SPACE_TYPE = {
	UNDER_GROUND = 2,
	IN_AIR = 1,
	NORMAL = 0
}
AbilityConst.ABILITY_TAG_NAME = {
	[AbilityConst.ABILITY_TAG_EARTHQUAKE] = "earthquake",
	[AbilityConst.ABILITY_TAG_REMOVE_CAMOUFLAGE] = "removeCamouflage"
}
AbilityConst.PARAM_TAG_2_ABILITY_TAG = {
	[25] = AbilityConst.ABILITY_TAG_EARTHQUAKE
}
AbilityConst.BUFF_TAG_STR_2_INT = {
	Positive = 10,
	Negative = 11
}
AbilityConst.BUFF_TRANSFER_GROUP_TAG_DEFAULT = 1
AbilityConst.BUFF_TAG_GROUP_BE_CONTROL = "BE_CONTROL"
AbilityConst.BUFF_TAG_SUPER_ARMOR = 1
AbilityConst.BUFF_TAG_INVINCIBLE = 2
AbilityConst.BUFF_TAG_STUN = 3
AbilityConst.BUFF_TAG_BREAK = 4
AbilityConst.BUFF_TAG_CHARM = 5
AbilityConst.BUFF_TAG_BREAK_FALL = 6
AbilityConst.BUFF_TAG_FAVORABLE = 7
AbilityConst.BUFF_TAG_PALSY = 8
AbilityConst.BUFF_TAG_FROZEN = 9
AbilityConst.BUFF_TAG_POSITIVE = 10
AbilityConst.BUFF_TAG_NEGATIVE = 11
AbilityConst.BUFF_TAG_NEUTRAL = 12
AbilityConst.BUFF_TAG_TIMESCALE_NO_EFFECT = 13
AbilityConst.BUFF_TAG_ATK_DMG_ZERO = 14
AbilityConst.BUFF_TAG_FORBIDDEN_SWITCH_PET = 15
AbilityConst.BUFF_TAG_NO_DEATH = 16
AbilityConst.BUFF_TAG_SILENT = 17
AbilityConst.BUFF_TAG_CONVERT_DMG_TO_HEAL = 18
AbilityConst.BUFF_TAG_SLOW = 19
AbilityConst.BUFF_TAG_IMMUNE_DAMAGE = 20
AbilityConst.BUFF_TAG_SLEEP = 21
AbilityConst.BUFF_TAG_SUPER_ARMOR_FORCE_DISPLACEMENT = 22
AbilityConst.BUFF_TAG_NO_BREAK = 23
AbilityConst.BUFF_TAG_BURN = 24
AbilityConst.BUFF_TAG_CLOUD_CONFINE = 25
AbilityConst.BUFF_TAG_FOBID_CONTROL_PET = 26
AbilityConst.BUFF_TAG_DISABLE_LOCKED = 27
AbilityConst.BUFF_TAG_RESTRAINED = 28
AbilityConst.BUFF_TAG_MAX = 32
AbilityConst.COMBAT_TARGET_TYPE_NONE = ""
AbilityConst.COMBAT_TARGET_TYPE_CASTER = "CASTER"
AbilityConst.COMBAT_TARGET_TYPE_TARGET = "TARGET"
AbilityConst.COMBAT_TARGET_TYPE_POS_OR_TARGET = "POS_OR_TARGET"
AbilityConst.COMBAT_TARGET_TYPE_TARGET_HIT = "TARGET_HIT"
AbilityConst.COMBAT_TARGET_TYPE_OWNER = "OWNER"
AbilityConst.COMBAT_TARGET_TYPE_MASTER = "MASTER"
AbilityConst.COMBAT_TARGET_TYPE_CURPET = "CURPET"
AbilityConst.COMBAT_TARGET_TYPE_HIT = "HIT"
AbilityConst.COMBAT_TARGET_TYPE_RANDOM_POINT = "RANDOM_POINT"
AbilityConst.COMBAT_TARGET_TYPE_SRC = "SRC"
AbilityConst.COMBAT_TARGET_TYPE_HIT_BOX = "HIT_BOX"
AbilityConst.COMBAT_TARGET_TYPE_PROJECTILE = "PROJECTILE"
AbilityConst.COMBAT_TARGET_TYPE_CURPET_HIT = "CURPET_HIT"
AbilityConst.COMBAT_TARGET_TYPE_AIM_POS = "AIM_POS"
AbilityConst.COMBAT_TARGET_TYPE_TRAP_TARGET = "TrapTarget"
AbilityConst.COMBAT_TARGET_TYPE_CURPET_OR_TEAM_PET = "CURPET_OR_TEAM_PET"
AbilityConst.COMBAT_ROTATION_TYPE_NONE = ""
AbilityConst.COMBAT_ROTATION_TYPE_TO_TARGET = "ToTarget"
AbilityConst.COMBAT_ROTATION_TYPE_INV_CIRCLE_CENTER = "InvCircleCenter"
AbilityConst.COMBAT_ROTATION_TYPE_SAME_AS_CIRCLE_CENTER = "SameAsCircleCenter"
AbilityConst.COMBAT_ROTATION_TYPE_TO_AIM = "ToAim"
AbilityConst.COMBAT_ROTATION_TYPE_TO_POS = "ToPos"
AbilityConst.COMBAT_ROTATION_TYPE_Direct = "Direct"
AbilityConst.PARSE_ROTATION_TARGET_MAP = {
	[AbilityConst.COMBAT_ROTATION_TYPE_TO_TARGET] = AbilityConst.COMBAT_TARGET_TYPE_TARGET_HIT,
	[AbilityConst.COMBAT_ROTATION_TYPE_TO_AIM] = AbilityConst.COMBAT_TARGET_TYPE_AIM_POS
}
AbilityConst.PARSE_POSITION_MAP = {
	[AbilityConst.COMBAT_TARGET_TYPE_TARGET] = "parseTargetPos",
	[AbilityConst.COMBAT_TARGET_TYPE_TARGET_HIT] = "parseTargetHitPos",
	[AbilityConst.COMBAT_TARGET_TYPE_HIT] = "parseHitPos",
	[AbilityConst.COMBAT_TARGET_TYPE_RANDOM_POINT] = "parseRandomPoint",
	[AbilityConst.COMBAT_TARGET_TYPE_POS_OR_TARGET] = "parseAttackPosOrTarget",
	[AbilityConst.COMBAT_TARGET_TYPE_HIT_BOX] = "parseHitBoxPos",
	[AbilityConst.COMBAT_TARGET_TYPE_PROJECTILE] = "parseProjectilePos",
	[AbilityConst.COMBAT_TARGET_TYPE_CURPET_HIT] = "parseCurPetHitPos",
	[AbilityConst.COMBAT_TARGET_TYPE_AIM_POS] = "parseAimPos"
}
AbilityConst.PARSE_ACTOR_ID_MAP = {
	[AbilityConst.COMBAT_TARGET_TYPE_CASTER] = "parseActorIdCaster",
	[AbilityConst.COMBAT_TARGET_TYPE_TARGET] = "parseActorIdTarget",
	[AbilityConst.COMBAT_TARGET_TYPE_POS_OR_TARGET] = "parseActorIdPosOrTarget",
	[AbilityConst.COMBAT_TARGET_TYPE_OWNER] = "parseActorIdOwner",
	[AbilityConst.COMBAT_TARGET_TYPE_MASTER] = "parseActorIdMaster",
	[AbilityConst.COMBAT_TARGET_TYPE_CURPET] = "parseActorIdCurPet",
	[AbilityConst.COMBAT_TARGET_TYPE_SRC] = "parseActorIdSrc",
	[AbilityConst.COMBAT_TARGET_TYPE_TRAP_TARGET] = "parseActorIdTrapTarget",
	[AbilityConst.COMBAT_TARGET_TYPE_CURPET_OR_TEAM_PET] = "parseActorIdCurPetOrTeamPet"
}
AbilityConst.BUFF_TAG_TO_DAMAGE_UI_TAG = {
	[AbilityConst.BUFF_TAG_PALSY] = AbilityConst.DAMAGE_UI_TAG_PALSY,
	[AbilityConst.BUFF_TAG_FROZEN] = AbilityConst.DAMAGE_UI_TAG_FROZEN
}
AbilityConst.PLAYER_ABILITY_TYPE = {
	INITIATIVE = 1,
	NORMAL = 0,
	PASSIVE = 2
}
AbilityConst.PLAYER_INITIATIVE_TYPE = {
	INITIATIVE_T = 3,
	INITIATIVE_E = 2,
	INITIATIVE_Q = 1,
	INITIATIVE_NORMAL = 0,
	INITIATIVE_M = 4
}
AbilityConst.SKILL_TYPE = {
	EXPLORE = 3,
	COMBATS = 1,
	SPECIAL = 4,
	PASSIVE = 2
}
AbilityConst.PLAYER_ABILITY_HOTKEY = {
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_NORMAL] = "Hud/NormalAttack",
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_Q] = "Hud/SkillQ",
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_E] = "Hud/SkillE",
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_T] = "Hud/ExploreSkill",
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_M] = "Hud/RogueSkill"
}
AbilityConst.PET_ABILITY_HOTKEY = {
	[AbilityConst.WEAPON_NORMAL_ATK_ABILITY] = "Hud/NormalAttack",
	[AbilityConst.WEAPON_SKILL_ABILITY] = "Hud/SkillQ",
	[AbilityConst.WEAPON_SKILL_ABILITY2] = "Hud/SkillE",
	[AbilityConst.EXPLORE_ABILITY] = "Hud/ExploreSkill"
}
AbilityConst.ULTIMATE_ABILITY_HOTKEY = "Hud/SkillR"
AbilityConst.PLAYER_ABILITY_CUR_TO_UNLOCK = {
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_NORMAL] = AbilityConst.PLAYER_ABILITY_TYPE.NORMAL,
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_Q] = AbilityConst.PLAYER_ABILITY_TYPE.INITIATIVE,
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_E] = AbilityConst.PLAYER_ABILITY_TYPE.INITIATIVE
}
AbilityConst.PLAYER_ABILITY_UNLOCK_TO_CUR = {
	[AbilityConst.PLAYER_ABILITY_TYPE.NORMAL] = {
		AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_NORMAL
	},
	[AbilityConst.PLAYER_ABILITY_TYPE.INITIATIVE] = {
		AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_Q,
		AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_E,
		AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_T
	}
}
AbilityConst.KNOCK_STATE_NONE = 0
AbilityConst.KNOCK_STATE_BACK = 1
AbilityConst.KNOCK_STATE_UP_START = 2
AbilityConst.KNOCK_STATE_UP_LOOP = 3
AbilityConst.KNOCK_STATE_UP_END = 4
AbilityConst.KNOCK_STATE_ANI_NAMES = {
	"KnockStateBack",
	"HitFly",
	"HitFlyLoop",
	"HitFlyToGround"
}
AbilityConst.KNOCK_ACCELERATE_TIME = 0.16666666666666666
AbilityConst.FRAME_FREEZE_KEY_NORMAL = "normal"
AbilityConst.FRAME_FREEZE_KEY_HIT = "hit"
AbilityConst.FRAME_FREEZE_KEY_CHAIN_CHANCE = "chainChance"
AbilityConst.FRAME_FREEZE_KEY_SWAP_POS_WITH_VIRTUAL_ENT = "swapPosWithVirtualEntity"
AbilityConst.TIME_SCALE_KEY_DEFAULT = "default"
AbilityConst.TIME_SCALE_KEY_ABILITY = "ability"
AbilityConst.TIME_SCALE_KEY_FRAME_FREEZE = "frameFreeze"
AbilityConst.ATTR_CHANGE_TYPE = {
	ADD = 1,
	ANY = 0,
	MINUS = 2
}
AbilityConst.ATTR_CHANGE_TARGET = {
	CURPET = 1,
	SELF = 0
}
AbilityConst.CAST_SOURCE = {
	SUPPORT_PET = 6,
	DIALOGUE_GRAPH = 7,
	NORMAL = 0,
	LET_GO_ENV_OBJ = 5,
	CALL_FRIENDS = 4,
	ITEM = 3,
	SKILL = 2,
	APPEAR = 1
}
AbilityConst.QTE_TYPE = {
	NORMAL = 0,
	THINKING = 1
}
AbilityConst.QTE_MOBILE_TYPE = {
	NORMAL = 0,
	HIDE_SKILL = 1
}
AbilityConst.MATERIAL_PROPERTY_TYPE = {
	Float = "Float",
	Color = "Color"
}
AbilityConst.HIT_TIMELINE_STATE_CONFLICT_MAP = {
	[AbilityConst.ATTACK_FORCE_KNOCK_LIGHT] = "KNOCK_LIGHT",
	[AbilityConst.ATTACK_FORCE_KNOCK_HEAVY] = "KNOCK_HEAVY",
	[AbilityConst.ATTACK_FORCE_KNOCK_STAND] = "KNOCK_HEAVY",
	[AbilityConst.ATTACK_FORCE_KNOCK_UP] = "KNOCK_UP"
}
AbilityConst.BUFF_BREAK_ID_SET = {
	[AbilityConst.BUFF_BREAK_ID] = true,
	[AbilityConst.BUFF_BREAK_FALL_ID] = true
}
AbilityConst.LockState = {
	AutoLock = 1,
	None = 0,
	Lock = 2
}
AbilityConst.BREAK_HOLD_MAX_TIME = 5
AbilityConst.PLAYER_SKILL_TO_PET_SKILL_MAP = {
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_Q] = AbilityConst.WEAPON_SKILL_ABILITY,
	[AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_E] = AbilityConst.WEAPON_SKILL_ABILITY2
}
AbilityConst.PET_SKILL_TO_PLAYER_SKILL_MAP = {
	[AbilityConst.WEAPON_NORMAL_ATK_ABILITY] = AbilityConst.PLAYER_ABILITY_TYPE.NORMAL,
	[AbilityConst.WEAPON_SKILL_ABILITY] = AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_Q,
	[AbilityConst.WEAPON_SKILL_ABILITY2] = AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_E
}
AbilityConst.USE_PET_SKILL_IDS = {
	9300001,
	9300002,
	9300003
}
AbilityConst.CommonAbility = {
	Throw = 9000006,
	Catch = 9000005,
	Jump = 9000004,
	QuickCatch = 9000003,
	Interact = 9000002,
	Base = 9000000,
	Dash = 9000001,
	SummonStandinPet = 10000040,
	ExitDelayExplore = 9001009,
	ChainAttack = 9001005,
	PetJump = 9001004,
	PetInteract = 9001002,
	PetDash = 9001001,
	CancelCatch = 9000007
}
AbilityConst.CommonAbilityActionPath = {
	[AbilityConst.CommonAbility.Dash] = "Player/StartSprint",
	[AbilityConst.CommonAbility.Interact] = "Hud/Interact",
	[AbilityConst.CommonAbility.Jump] = "Player/Jump",
	[AbilityConst.CommonAbility.Throw] = "Catch/Throw",
	[AbilityConst.CommonAbility.CancelCatch] = "Catch/GamepadExitCatch",
	[AbilityConst.CommonAbility.PetDash] = "Player/StartSprint",
	[AbilityConst.CommonAbility.PetInteract] = "Hud/Interact",
	[AbilityConst.CommonAbility.PetJump] = "Player/Jump",
	[AbilityConst.CommonAbility.ChainAttack] = "Hud/SkillChainAttack",
	[AbilityConst.CommonAbility.ExitDelayExplore] = "Hud/ExitDelayExplore"
}
AbilityConst.ACTION_TYPE_NORMAL = 1
AbilityConst.ACTION_TYPE_EVENT = 2
AbilityConst.MAX_DELAY_TIME = 1
AbilityConst.DAMAGE_CHECK_MAX_OFFSET = 3
AbilityConst.PROJECTILE_CHECK_MAX_OFFSET = 5
AbilityConst.CAN_PRESET_ABILITY_TYPE = {
	[AbilityConst.WEAPON_SKILL_ABILITY] = true,
	[AbilityConst.WEAPON_SKILL_ABILITY2] = true
}
AbilityConst.STEAL_ABILITY_TYPE = {
	ULTIMATE = 2,
	RANDOM = 1,
	LAST_CAST = 3
}
AbilityConst.ABILITY_STATE_NONE = 0
AbilityConst.ABILITY_SKATEBOARD_STATE = 1
AbilityConst.ABILITY_DRUMMING_STATE = 2
AbilityConst.ABILITY_WALKING_ATTACK_STATE = 1000
AbilityConst.ABILITY_SPECIAL_RIDE_STATE = 101
AbilityConst.SPECIAL_ABILITY_ANIM_STATE_2_INDEX = {
	Skill_ShieldWave_Idle = AbilityConst.ABILITY_DRUMMING_STATE,
	Skill_Skate_End = AbilityConst.ABILITY_STATE_NONE
}
AbilityConst.SPECIAL_ABILITY_ANIM_INDEX_2_STATE = {
	[AbilityConst.ABILITY_SKATEBOARD_STATE] = "Skill_Skate_Move",
	[AbilityConst.ABILITY_DRUMMING_STATE] = "Skill_ShieldWave_Idle"
}
AbilityConst.SKILL_MOTION_ANIM_SUFFIX = "AnimId"
AbilityConst.SKILL_MOTION_ENTER_ACTION_SUFFIX = "EnterActionIds"
AbilityConst.SKILL_MOTION_EXIT_ACTION_SUFFIX = "ExitActionIds"
AbilityConst.INTERACT_EFFECT_TYPE = {
	ABSORB_PROJ = "Absorb_Proj",
	RECEIVE_ATK = "Receive_Atk"
}
AbilityConst.COMBAT_DATA_TYPE = {
	RECEIVE_DMG = 1
}
AbilityConst.EnumAbilityTypeName = {
	[AbilityConst.EnumAbilityType.Attack] = "Attack",
	[AbilityConst.EnumAbilityType.Skill] = "Skill",
	[AbilityConst.EnumAbilityType.Appear] = "Appear",
	[AbilityConst.EnumAbilityType.Ultimate] = "Ultimate",
	[AbilityConst.EnumAbilityType.Support] = "Support",
	[AbilityConst.EnumAbilityType.Item] = "Item Skill",
	[AbilityConst.EnumAbilityType.PASSIVE] = "Passive",
	[AbilityConst.EnumAbilityType.Explore] = "Explore"
}
AbilityConst.AgainstStateName = {
	Fly = "fly",
	Burrow = "burrow"
}
AbilityConst.ABILITY_CAST_FAILED_BY_IN_STATE = {
	FLY_ST = AbilityConst.ABILITY_CAST_FAILED_IN_FLY,
	BURROW_ST = AbilityConst.ABILITY_CAST_FAILED_IN_BURROW,
	TAKE_ROOT_ST = AbilityConst.ABILITY_CAST_FAILED_IN_TAKEROOT
}
AbilityConst.ABILITY_CAST_FAILED_BY_NOT_IN_STATE = {
	BURROW_ST = AbilityConst.ABILITY_CAST_FAILED_NOT_IN_BURROW,
	TAKE_ROOT_ST = AbilityConst.ABILITY_CAST_FAILED_NOT_IN_TAKEROOT
}
AbilityConst.RANDOM_VAL_INT = 1
AbilityConst.HIT_BOX_PART_TYPE = {
	Extra2 = 9,
	Extra1 = 8,
	Body = 7,
	Tail = 6,
	FootR = 5,
	FootL = 4,
	HandR = 3,
	HandL = 2,
	Head = 1,
	Extra4 = 11,
	Extra3 = 10
}
AbilityConst.KNOCK_UP_RECOVER_MAX_TIME = 3
AbilityConst.PLAYER_IMPULSE_CD = 0.1
AbilityConst.CHAIN_ATTACK_FOV = 20
AbilityConst.CHAIN_ATTACK_FOV_KEEP_TIME = 2
AbilityConst.CHAIN_ATTACK_FOV_BLEND_TIME = 0.5
AbilityConst.CHAIN_ATTACK_CAMERA_BLEND_TIME = 0.3
AbilityConst.ABILITY_ID_EMPTY = -1
AbilityConst.ABILITY_FLY_OVERRIDE_FLY_HEIGHT = "abilityFlyOverrideFlyHeight"
AbilityConst.CALC_PARAM_TYPES = {
	TIMELINE = 4,
	CHAIN_ATTACK = 3,
	ABILITY = 2,
	BUFF = 1
}
AbilityConst.MobileCastType = {
	Aim = 1,
	Default = 0,
	Charge = 2
}
AbilityConst.ABILITY_STORE_TYPE = {
	CALL_FRIENDS = 1,
	NORMAL = 0,
	STOLEN = 2
}
AbilityConst.ATTRIBUTE_ENTRY_TYPE = {
	ALL_PET = 3,
	SELF = 1,
	CUR_PET = 2,
	CONTROL_PET = 4
}
AbilityConst.ATTRIBUTE_CONDITION_TYPE_OWNER_STATE_CHANGE = 1
AbilityConst.ATTRIBUTE_CONDITION_TYPE_OWNER_ATTRIBUTE_CHANGE = 2
AbilityConst.ATTRIBUTE_CONDITION_TYPE_CALC_RESULT_ATTACK = 4
AbilityConst.ATTRIBUTE_CONDITION_TYPE_BE_ATTAKCED = 8
AbilityConst.ATTRIBUTE_CONDITION_TYPE_BUFF_TAG = 16
AbilityConst.ATTRIBUTE_CONDITION_TYPE_SHIELD_CHANGE = 32
AbilityConst.NEED_INIT_ATTRIBUTE_CONDITIONS = AbilityConst.ATTRIBUTE_CONDITION_TYPE_OWNER_STATE_CHANGE + AbilityConst.ATTRIBUTE_CONDITION_TYPE_OWNER_ATTRIBUTE_CHANGE + AbilityConst.ATTRIBUTE_CONDITION_TYPE_BUFF_TAG + AbilityConst.ATTRIBUTE_CONDITION_TYPE_SHIELD_CHANGE
AbilityConst.SHIELD_CHANGE_TYPE = {
	ADD = 1,
	CHANGE_POINT = 3,
	REMOVE = 2,
	INHERIT = 4
}
AbilityConst.SELECT_TARGET_TYPE = {
	MIN = 1,
	MAX = 2
}
AbilityConst.TOTAL_DELAY_DAMAGE_KEY = "totalDelayDamage"
AbilityConst.DELAY_DAMAGE_TIMER_NAME = "delayDamageTimer_"
AbilityConst.ON_HEAL_GET_HEAL_POINT = "onHealGetHealPoint"
AbilityConst.CAMOU_FLAGE_MODE = {
	ENEMY_DETECTED = 1,
	ENEMY = 0,
	FRIEND = 2
}
AbilityConst.CHANGE_ABILITY_MAP_REASON = {
	ResetTree = 6,
	SwitchAbility = 5,
	Gm = 4,
	EditAbility = 3,
	ChangeCustomIndex = 2,
	CombatChange = 1,
	Default = 0,
	SetTempAbility = 7
}
AbilityConst.HOOK_SPRINT_HIT_POS = "HookSprintHitPos"
AbilityConst.SPECIAL_RIDE_HOOK_BONE_NAME = "zuoqiguadian"
AbilityConst.SPECIAL_RIDE_SWITCH_SKILL_INFO = {
	[1002600] = {
		to = 10260004,
		from = 10260000
	}
}
AbilityConst.SPECIAL_BALL_DEFENSE_STATE_DATA = "SpecialBallDefenseStateData"
AbilityConst.PUSH_SKILL_MAPS = {
	[AbilityConst.WEAPON_NORMAL_ATK_ABILITY] = true
}
AbilityConst.SKILL_CANCELLABLE_IGNORE_STS = {
	CAST_ST = 1,
	ATTACK_ST = 1,
	SKILL_ST = 1
}
AbilityConst.SKILL_HIT_BACK_SWING_IGNORE_STS = {
	KNOCK_BACK_ST = 1,
	KNOCK_UP_END_ST = 1,
	KNOCK_UP_ST = 1,
	HIT_ST = 1
}
AbilityConst.AUTO_CAST_IGNORE_STS = {
	AUTO_CAST_ST = 1
}
AbilityConst.CONTROL_BUFF_STS = {
	STUN_ST = true,
	SLEEP_ST = true,
	PALSY_ST = true,
	FROZEN_ST = true,
	CHARM_ST = true,
	BREAK_ST = true
}
AbilityConst.SWIM_IGNORE_BUFF_CONTROL_ST = {
	CHARM_ST = true
}
AbilityConst.SCAR_DECAL_INVALID_TYPE = {
	[AbilityConst.COMBAT_CONTEXT_TYPE_PROJECTILE] = true,
	[AbilityConst.COMBAT_CONTEXT_TYPE_BUFF] = true,
	[AbilityConst.COMBAT_CONTEXT_TYPE_CHAIN_ATTACK] = true,
	[AbilityConst.COMBAT_CONTEXT_TYPE_TAG_REACTION] = true
}
AbilityConst.ABILITY_TICK_REASONS = {
	TIMELINE = 2,
	TEMP_BUFF = 8,
	BUFF_TAG = 7,
	SPECIAL_ATTACK_MODE = 6,
	SPREAD_ANNULAR_SECTOR = 5,
	BUFF_THINK = 4,
	SKILL_STATE = 3,
	ABILITY_ST = 1,
	FRAME_FREEZE = 9,
	FORCE_DISPLACEMENT = 16,
	CAPTURE = 15,
	BUFF_WAIT_DESTROY = 14,
	MOVE_CHECK = 13,
	GM_AUTO_CAST_ABILITY = 12,
	PROJ_AROUND_SELF = 11,
	ENTITY_TIMER = 10
}
AbilityConst.IntensitySkillTyle = {
	Tag = 3,
	ReduceEpCost = 2,
	Intensity = 1
}
AbilityConst.ATTRIBUTE_TICK_REASONS = {
	HP = 3,
	EP = 2,
	TP = 1
}
AbilityConst.EP_COST_REASON = {
	PASSIVE = 2,
	FORCE = 3,
	PROACTIVE = 1
}
AbilityConst.EP_RECOVER_REASON = {
	NORMAL = 1,
	RETURN_COST = 2
}
AbilityConst.NEED_TICK_BUFF_TAG = {
	[AbilityConst.BUFF_TAG_BREAK] = true,
	[AbilityConst.BUFF_TAG_BREAK_FALL] = true,
	[AbilityConst.BUFF_TAG_CHARM] = true
}
AbilityConst.FORBID_CONVERT_CONTROL_TARGET = {
	getPlayer = true,
	getPetByIdx = true,
	getServerCacheVal = true,
	getPlayerRealControlEnt = true
}
AbilityConst.ROGUE_BATTLE_DATA_KEY = {
	SKILL_EP = "rogueSkillEp",
	SKILL_EP_MAX = "rogueSkillEpMax",
	ACCUMULATED_COIN = "rogueAccumulatedCoin"
}
AbilityConst.ON_CHARACTER_STATE_CHANGE_OLD_STATE = "onCharacterStateChange_OldState"
AbilityConst.ON_CHARACTER_STATE_CHANGE_NEW_STATE = "onCharacterStateChange_NewState"
AbilityConst.ELEMENT_TYPE_2_CONDITION_TRANSFER = {
	[2] = AbilityConst.CONDITION_TYPE_FROZE,
	[3] = AbilityConst.CONDITION_TYPE_ACTION_WATER,
	[4] = AbilityConst.CONDITION_TYPE_CONDUCT,
	[5] = AbilityConst.CONDITION_TYPE_IGNITE,
	[9] = AbilityConst.CONDITION_TYPE_BLOW
}
AbilityConst.BUFF_SPECIAL_TYPES = {
	CORE_CARRY = 1,
	DEFAULT = 0,
	FORCE_REMOVE = -1
}
AbilityConst.BUFF_CATEGORY_TYPE_DEFAULT = 0
AbilityConst.BUFF_CATEGORY_TYPE_SOCIAL = 1
AbilityConst.BUFF_CATEGORY_TYPES_2_NUM = {
	[AbilityConst.BUFF_CATEGORY_TYPE_SOCIAL] = 3
}
AbilityConst.PET_ABILITY_KEY_STR_TO_TYPE = {
	Normal = AbilityConst.WEAPON_NORMAL_ATK_ABILITY,
	Q = AbilityConst.WEAPON_SKILL_ABILITY,
	E = AbilityConst.WEAPON_SKILL_ABILITY2,
	R = AbilityConst.ULTIMATE_ABILITY
}
AbilityConst.PLAYER_ABILITY_KEY_STR_TO_TYPE = {
	Normal = AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_NORMAL,
	Q = AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_Q,
	E = AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_E,
	T = AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_T,
	M = AbilityConst.PLAYER_INITIATIVE_TYPE.INITIATIVE_M
}
AbilityConst.ECS_ELEMENT_2_ABILITY = {
	[0] = 5,
	3,
	2,
	4,
	8,
	9
}
AbilityConst.ABILITY_ELEMENT_2_ECS = {
	[0] = 7,
	nil,
	2,
	1,
	3,
	0,
	nil,
	nil,
	nil,
	5
}
AbilityConst.HATE_MODE = {
	Team_Hate_Mode_Equal = 2,
	Team_Hate_Mode_Duty_First = 1,
	Team_Hate_Mode_Default = 0
}
AbilityConst.BACK_SKILL_ID = 10010006
AbilityConst.EXCEPT_EXTRA_ATTR_SRCTYPE = AbilityConst.ATTRIBUTE_SRC_TYPE_PET_PRIMARY_PROPERTY
AbilityConst.EXTRA_SRCTYPE_STRKEY_OTHER = "PET_PRIMARY_EXTRA_TIP_OTHER"
AbilityConst.EXTRA_SRCTYPE_STRKEYS = {
	PET_PRIMARY_EXTRA_TIP_BUFF = {
		AbilityConst.ATTRIBUTE_SRC_TYPE_BUFF,
		AbilityConst.ATTRIBUTE_SRC_TYPE_BUFF_DYNAMIC,
		AbilityConst.ATTRIBUTE_SRC_TYPE_BUFF_LAYER,
		AbilityConst.ATTRIBUTE_SRC_TYPE_BUFF_SERIES_CNT,
		AbilityConst.ATTRIBUTE_SRC_TYPE_CORE_CARRY,
		AbilityConst.ATTRIBUTE_SRC_TYPE_CORE_CARRY_EX
	},
	PET_PRIMARY_EXTRA_TIP_STARUP = {
		AbilityConst.ATTRIBUTE_SRC_TYPE_PET_RESONANCE
	},
	PET_PRIMARY_EXTRA_TIP_DECORATIONS = {
		AbilityConst.ATTRIBUTE_SRC_TYPE_PET_JERELRY
	}
}
AbilityConst.WAIT_CLIENT_HIT_EVENT_CNT = 20
AbilityConst.ABILITY_PARAM_TAG_COMBO = 27
AbilityConst.ABILITY_PARAM_TAG_COMBO2 = 47
AbilityConst.EXTRA_SRCTYPE_STRKEYS_SORT = {
	PET_PRIMARY_EXTRA_TIP_DECORATIONS = 3,
	PET_PRIMARY_EXTRA_TIP_STARUP = 2,
	PET_PRIMARY_EXTRA_TIP_BUFF = 1,
	PET_PRIMARY_EXTRA_TIP_OTHER = 4
}
AbilityConst.MUTE_LOOK_AT_BUFF = {
	[AbilityConst.BUFF_TAG_FROZEN] = 1
}
AbilityConst.FORBID_SWITCH_PET_BUFF_TAGS = {
	[AbilityConst.BUFF_TAG_CHARM] = true,
	[AbilityConst.BUFF_TAG_FROZEN] = true,
	[AbilityConst.BUFF_TAG_STUN] = true,
	[AbilityConst.BUFF_TAG_SLEEP] = true,
	[AbilityConst.BUFF_TAG_BREAK] = true,
	[AbilityConst.BUFF_TAG_BREAK_FALL] = true,
	[AbilityConst.BUFF_TAG_FORBIDDEN_SWITCH_PET] = true
}
AbilityConst.FORBID_ABILITY_BUFF_TAGS = {
	[AbilityConst.BUFF_TAG_CHARM] = true,
	[AbilityConst.BUFF_TAG_FROZEN] = true,
	[AbilityConst.BUFF_TAG_STUN] = true,
	[AbilityConst.BUFF_TAG_SLEEP] = true,
	[AbilityConst.BUFF_TAG_BREAK] = true,
	[AbilityConst.BUFF_TAG_BREAK_FALL] = true,
	[AbilityConst.BUFF_TAG_SILENT] = true
}
AbilityConst.DEFAULT_NULL_TABLE = {}
AbilityConst.DURATION_IGNORE_IDS = {
	[10451401] = true,
	[104516] = true,
	[102702] = true,
	[101305] = true,
	[10451601] = true,
	[104514] = true
}
AbilityConst.CREATION_DURATION_MAX = 300
AbilityConst.BUFF_LIFE_EVENT_TYPE = {
	START = "start",
	LAYER_DECREASE = "layerDecrease",
	DESTROY = "destroy",
	LAYER_INCREASE = "layerIncrease"
}
AbilityConst.INVALID_TARGET_REASONS = {
	IS_TRANSPARENT = 5,
	IN_INVINCIBLE = 4,
	SKILL_CAMERA_ANIM_INVINCIBLE = 3,
	NO_SPACE = 2,
	SYNC_ENTITY_ROLE = 1,
	CYLINDER_TRAP_EMPTY = 13,
	LIFE_NEAR_DEAD = 12,
	GROUP_DROP_END = 11,
	IS_TRAPPED = 10,
	KNOCK_UP_INVINCIBLE = 7,
	IS_IN_CAPTURE = 6
}
AbilityConst.INVALID_LOCK_REASONS = {
	IS_TRANSPARENT = 1,
	BUFF_TAG_DISABLE_LOCKED = 3,
	IS_IN_CAPTURE = 2
}

return AbilityConst
