-- chunkname: @C:\\dev\\jkroot\\ws\\workspace\\XWinPublish\\proj\\p4dir\\client\\LuaScripts\\Common\\Const\\Const.lua

local Const = {
	SPAWN_TYPE_SANDBOX_INIT = 11,
	SPAWN_TYPE_TIME = 10,
	SPAWN_TYPE_PRODUCTION = 9,
	SPAWN_TYPE_CATCH = 8,
	SPAWN_TYPE_TASK = 6,
	SPAWN_TYPE_PLENTY = 5,
	SPAWN_TYPE_INDIVIDUAL = 4,
	SPAWN_TYPE_PERIOD = 3,
	SPAWN_TYPE_MANUAL = 2,
	SPAWN_TYPE_DIE = 1,
	SPAWN_TYPE_INIT = 0,
	SPACE_TILE_UNLOAD_DELAY = 10,
	DAMAGE_SHOW_ENUM_POWER_BREAK = 4,
	DAMAGE_SHOW_ENUM_EXCELLENT = 3,
	DAMAGE_SHOW_ENUM_NORMAL = 2,
	DAMAGE_SHOW_ENUM_WEAK = 1,
	DAMAGE_SHOW_ENUM_USELESS = 0,
	AOI_CACHE_TIME_DEFAULT = 1,
	ACTOR_TYPE_PET_GHOST = 21,
	ACTOR_TYPE_SIMPLEMOVENPC = 20,
	ACTOR_TYPE_SPELLFIELD = 19,
	ACTOR_TYPE_CAMPCAR = 18,
	ACTOR_TYPE_PLAYER_GHOST = 17,
	ACTOR_TYPE_HOME_OBJECT = 16,
	ACTOR_TYPE_VEHICLE = 14,
	ACTOR_TYPE_RESPOINT = 13,
	ACTOR_TYPE_MMOITEM = 12,
	ACTOR_TYPE_STATICNPC = 11,
	ACTOR_TYPE_ENVOBJ = 10,
	ACTOR_TYPE_SpaceSpawner = 9,
	ACTOR_TYPE_BOTPLAYER = 8,
	PERCENT_HUNDRED = 100,
	NETWORK_SMOOTH_RTT_ALPHA = 0.8,
	MONTH_ONE_YEAR = 12,
	SECONDS_HALF_DAY = 43200,
	ACTOR_TYPE_TrapBall = 7,
	ACTOR_TYPE_VIRTUAL = 6,
	ACTOR_TYPE_INTERACTOR = 5,
	ACTOR_TYPE_CREATION = 4,
	ACTOR_TYPE_PUPPET = 3,
	ACTOR_TYPE_PET = 2,
	ACTOR_TYPE_PLAYER = 1,
	ACTOR_TYPE_NONE = 0,
	COMBAT_STATUS_IN_COMBAT = 1,
	COMBAT_STATUS_NORMAL = 0,
	SEARCH_USR_TYPE_PLAYER_GHOST = 16384,
	QUEST_TYPE_ULTRA = 21,
	QUEST_TYPE_WEDDING = 22,
	PLAYER_INIT_STATUS_CTOR = 1,
	CLEN_USR_TYPE_VIRTUAL_AI = 9,
	CLEN_USR_TYPE_BOT_PLAYER = 7,
	CLEN_USR_TYPE_OTHER = 5,
	CLEN_USR_TYPE_MONSTER = 3,
	CLEN_USR_TYPE_PLAYER = 1,
	WEATHER_NONE = "None",
	ELEMENT_FIELD_SHAPE_BOX = 2,
	ELEMENT_FIELD_SHAPE_SPHERE = 1,
	TAG_INTERACT_ATTACK = 5,
	TAG_INTERACT_PROJ = 4,
	TAG_PROJECTILE = 2,
	TAG_ACTOR = 1,
	AUTHORITY_SIMULATED_PROXY = 3,
	AUTHORITY_AUTONOMOUS_PROXY = 2,
	AUTHORITY_MASTER = 1,
	PLAYER_INIT_STATUS_STOP = 6,
	DAYS_365 = 365,
	MAX_SECONDS_ONE_MONTH = 2678400,
	SECONDS_ONE_DAY = 86400,
	SECONDS_ONE_HOUR = 3600,
	SECONDS_HALF_HOUR = 1800,
	SECONDS_ONE_MINUTE = 60,
	MILLISECOND_ONE_SECOND = 1000,
	WORLD_PAIRS_CAMP_ARBITRARY = 4,
	WORLD_PAIRS_CAMP_NEUTRAL = 3,
	WORLD_PAIRS_CAMP_ENEMY = 2,
	WORLD_PAIRS_CAMP_PARTNER = 1,
	EXTRACT_MODE_PROPORTION_OVERFLOW = 2,
	EXTRACT_MODE_PROPORTION = 1,
	EXTRACT_MODE_PROBABILITY = 0,
	ITEM_LOCKED_NOT = 2,
	ITEM_LOCKED_YES = 1,
	INV_BOUND_TYPE_INSENSITIVE = 3,
	INV_BOUND_TYPE_UNBOUND = 2,
	INV_BOUND_TYPE_BOUND = 1,
	MAX_FORMATION_COUNT = 8,
	PROCESS_ACTOR_VOXEL_INTERVAL = 0.2,
	SWITCH_INTERVAL = 0.5,
	SWITCH_PET_COST_EP = 0,
	SWITCH_PET_COST_AP_IN_CONTROL = 0,
	SWITCH_PET_COST_EP_IN_CONTROL = 0,
	SWITCH_PET_CD_MODE_SINGLE = 0,
	SWITCH_PET_CD_MODE_PUBLIC = 1,
	LIFE_DEAD_BY_ALL_PET_DIE = 32,
	LIFE_DEAD_BY_AI_STATE = 64,
	LIFE_DEAD_BLACK_SCREEN_TYPE = 26,
	RESET_POS_TYPE_INCLUDE_CUR_POS = 1,
	RESET_POS_TYPE_MARK_POINT = 3,
	REVIVE_TYPE_NORMAL = 1,
	REVIVE_TYPE_ITEM = 2,
	REVIVE_TYPE_HELP = 3,
	REVIVE_TYPE_TOWER = 4,
	PET_REVIVE_TYPE_DEFAULT = 0,
	PET_REVIVE_TYPE_DISABLE = 1,
	PET_REVIVE_TYPE_TIME = 2,
	REVIVE_BOSS_OFF = 1,
	REVIVE_BOSS_ON = 2,
	PET_RELEASE_HISTORY_MAX_COUNT = 50,
	PET_RELEASE_HISTORY_TTL_SECONDS = 604800,
	ITEM_DECOMPOSE_HISTORY_TTL_SECONDS = 604800,
	NEARBY_RANGE = 32,
	TRAP_EVENT_ID_TOPLOGO_OTHER = 23,
	TRAP_EVENT_ID_TOPLOGO_PLAYER = 22,
	TRAP_EVENT_ID_AI_PERCEPTIBILITY = 21,
	TRAP_EVENT_ID_GRAB_EGG_DANGER_BGM = 20,
	TRAP_EVENT_ID_GRAB_EGG_LOOT_REACTION = 19,
	TRAP_EVENT_PLAYER_AOI4 = 18,
	TRAP_EVENT_PLAYER_AOI3 = 17,
	TRAP_EVENT_PLAYER_AOI2 = 16,
	TRAP_EVENT_PLAYER_AOI1 = 15,
	TRAP_EVENT_ID_NPC_AI_REACTION = 14,
	TRAP_EVENT_ID_CYLINDER_ITEM = 13,
	TRAP_EVENT_ID_CHEST_RANGE = 12,
	SEARCH_USR_TYPE_LOCKABLE = 2462,
	SEARCH_USR_TYPE_SENSOR = 130,
	SEARCH_USR_TYPE_ALL_RESPOINT = 1294,
	SEARCH_USR_TYPE_RESPOINT = 1024,
	SEARCH_USR_TYPE_VIRTUAL_AI = 512,
	SEARCH_USR_TYPE_ENVOBJ = 256,
	SEARCH_USR_TYPE_INTERACTOR = 64,
	SEARCH_USR_TYPE_ACTOR_CREATION = 158,
	SEARCH_USR_TYPE_OTHER = 32,
	SEARCH_USR_TYPE_CREATION = 16,
	SEARCH_USR_TYPE_ACTOR = 14,
	SEARCH_USR_TYPE_PARMON = 12,
	SEARCH_USR_TYPE_MONSTER = 8,
	SEARCH_USR_TYPE_PET = 4,
	SEARCH_USR_TYPE_PLAYER = 2,
	SEARCH_USR_TYPE_NONE = 1,
	CLEN_USR_TYPE_GAMEPLAY = 20,
	CLEN_USR_TYPE_PLAYER_GHOST = 14,
	CLEN_USR_TYPE_SPELLFIELD = 13,
	CLEN_USE_TYPE_HOME = 12,
	CLEN_USR_TYPE_VIRTUAL_TARGET = 11,
	CLEN_USR_TYPE_RESPOINT = 10,
	SERVER_STATUS_CLOSE = "Close",
	CLEN_USR_TYPE_ENVOBJ = 8,
	SERVER_STATUS_FLUENT = "Fluent",
	CLEN_USR_TYPE_INTERACTOR = 6,
	SERVER_STATUS_BUSY = "Busy",
	CLEN_USR_TYPE_CREATION = 4,
	SERVER_STATUS_FULL = "Full",
	CLEN_USR_TYPE_PET = 2,
	CLEN_USR_TYPE_NONE = 0,
	RESET_POS_TYPE_EXCLUDE_CUR_POS = 2,
	WEATHER_RAIN = "Rain",
	LIFE_ALIVE_BY_RECOVER = 1,
	LOGIN_DUMMY_CLUSTERID = -1,
	LOGIN_LOCAL_CLUSTERID = 0,
	TPCT_COURSE = 1,
	TPCT_DEBUG_COPY_PLAYER = 0,
	TAG_ELEMENT = 3,
	ARK_STATE_NAME = "METAVERSE_ST",
	PET_EVOLVE_ITEM_COND_POS_STATE = 4,
	PET_EVOLVE_ITEM_COND_POS_DESC = 3,
	PET_EVOLVE_ITEM_COND_POS_CLUE = 2,
	PET_EVOLVE_ITEM_COND_POS_ITEM = 1,
	PET_EVOLVE_NORMAL_COND_POS_STATE = 4,
	PET_EVOLVE_NORMAL_COND_POS_DESC = 3,
	PET_EVOLVE_NORMAL_COND_POS_CLUE = 2,
	PET_EVOLVE_NORMAL_COND_POS_COND = 1,
	CALL_FRIEND_TYPE_SAME_STAGE = 2,
	CALL_FRIEND_TYPE_HIGH_STAGE = 1,
	CALL_FRIEND_TYPE_ALL = 0,
	CALL_FRIEND_BEHAVIOR_ID = 1,
	IACT_IP_COLLECT_ITEM = 6,
	IACT_TP_HOME_PET = 5,
	IACT_TP_NPC_SPECIAL = 4,
	IACT_TP_ENVOBJ = 3,
	IACT_TP_NPC = 2,
	IACT_TP_CHEST = 1,
	CT_INTERACT = 1,
	CP_VALUE_HP_DIVISOR = 10,
	NPC_FUNC_CFG_POS_EVENT = 4,
	SEARCH_USR_TYPE_SPELLFIELD = 8192,
	SEARCH_USR_TYPE_AI_INTERACT = 336,
	INTERACT_DISTANCE_DEFAULT = 3,
	DIT_KILL_OR_CAPTURE_PUPPET = 4,
	DIT_USEITEM_CLIENT_ARGS = 3,
	DIT_REPORT_CATCH_PET = 2,
	DIT_HANDBOOK_PET_TEMPLATE = 1,
	INVINCIBLE_BUFF = 230307,
	INVINCIBLE_SILENCE_BUFF = 10061,
	NO_DAMAGE_BUFF = 10015,
	SUPER_ARMOR_BUFF = 10011,
	ARRIVE_TYPE_SPHERE = 1,
	BOX_TEMP_LOCKED = 2,
	BOX_TEMP_OK = 1,
	EXPLORE_SKILL_SWIMMING = 3,
	EXPLORE_SKILL_GLIDING = 2,
	EXPLORE_SKILL_CLIMBING = 1,
	LIMIT_SCENE = 4,
	LIMIT_MONTH = 3,
	LIMIT_WEEK = 2,
	LIMIT_DAY = 1,
	PET_ABILITY_PRESET_COUNT = 4,
	EVENT_CARRY_OUT = 25,
	EVENT_EXPLORE_LEAVE_PLAYER = 24,
	EVENT_EXPLORE_PLAYER = 23,
	EVENT_LEAVE_EXPLORE_PET = 22,
	EVENT_EXPLORE_PET = 21,
	EVENT_RESET = 20,
	EVENT_PET_DEFAULT = 10,
	EVENT_LEAVE_PET = 4,
	EVENT_ENTER_PET = 3,
	EVENT_HIDE_PET = 2,
	EVENT_SHOW_PET = 1,
	CONTROL_STATE_RIDE = 4,
	CONTROL_STATE_CONTROL = 3,
	CONTROL_STATE_FOLLOW = 2,
	CONTROL_STATE_SINGLE = 1,
	PET_HBMSK_RAINBOW_CATCHED = 512,
	PET_HBMSK_RAINBOW_KNOWN = 256,
	PET_HBMSK_EVOLVE_GET = 128,
	PET_HBMSK_ELITE_CATCHED = 64,
	PET_HBMSK_ELITE_KNOWN = 32,
	PET_HBMSK_RESEARCHED = 16,
	PET_HBMSK_SHINY_CATCHED = 8,
	PET_HBMSK_SHINY_KNOWN = 4,
	PET_HBMSK_CATCHED = 2,
	PET_HBMSK_KNOWN = 1,
	PET_RESEARCH_REWARD_LEVEL_MAX = 4,
	PET_RESEARCH_REWARD_LEVEL_SHOW_MAX = 4,
	PET_RESEARCH_REWARD_LEVEL_MIN = 1,
	REWARD_STATUS_DONE = 2,
	REWARD_STATUS_CANREWARD = 1,
	REWARD_STATUS_INIT = 0,
	TRAP_EVENT_ID_SYNC_FPS_RANGE = 11,
	CUSTOM_MAP_MARK_DEFAULT_NAME = "CustomMark",
	CUSTOM_MAP_MARK_MAX_COUNT = 1000,
	NPC_DUEL_PRO = 10511,
	NPC_DUEL = 10510,
	MAP_MARK_LEYLINETREE_TRANSMIT = 10406,
	MAP_MARK_LEYLINETREE_BASE = 10301,
	TRAP_EVENT_ID_ENGAGE_AND_DISENGAGE_VIEW = 3,
	MAP_MARK_SOURCE_REFRESH_CLOSED = "refresh_closed",
	TRAP_EVENT_ID_ENGAGE_VIEW = 1,
	MAP_MARK_SOURCE_LEYLINE_AREA = "leyline_area",
	TRAP_EVENT_ID_ABILITY_D = 8,
	MAP_MARK_SOURCE_AREA_UNLOCK = "area_unlock",
	TRAP_EVENT_ID_ABILITY_C = 7,
	MAP_MARK_SOURCE_NPC_DUEL = "npc_duel",
	TRAP_EVENT_ID_ABILITY_B = 6,
	TRAP_EVENT_ID_ABILITY_A = 5,
	TRAP_EVENT_ID_ALERT = 4,
	ITEM_DECOMPOSE_HISTORY_MAX_COUNT = 50,
	TRAP_EVENT_ID_DISENGAGE_VIEW = 2,
	TRAP_EVENT_ID_GHOST_EYE = 9,
	REVIVE_AUTO_ON = 10,
	TRAP_EVENT_ID_AI_HELPER = 10,
	EVENT_CARRY_RST = 26,
	EVENT_SHOW_PET_BY_REVIVE = 30,
	EVENT_SHOW_PET_BY_SKILL = 31,
	EVENT_SHOW_PET_BY_EVENT = 32,
	EVENT_SHOW_PET_QTE = 33,
	EVENT_SHOW_PET_BY_PVP = 34,
	EVENT_ENTER_PET_BY_REVIVE = 40,
	EVENT_ENTER_PET_BY_EVENT = 41,
	EVENT_ENTER_PET_BY_PVP = 42,
	EVENT_LEAVE_PET_BY_EVENT = 50,
	SWITCH_PET_COST_AP = 0,
	CAPTURE_FAIL_RECOVER_HP_PERCENT = 0.1,
	EXPLOREPET_REVIVE_HP_INTERVAL = 1,
	EXPLOREPET_RECOVER_HP_INTERVAL = 2,
	REVIVE_HP_PERCENT = 0.1,
	CAMP_PEACE = 7001,
	CAMP_NPC_DEFAULT = 4001,
	CAMP_MONSTER_DEFAULT = 3001,
	CAMP_NPC_PARTNER = 2002,
	CAMP_NPC_NEUTRAL = 2001,
	CAMP_PLAYER_TEAM_4 = 1005,
	CAMP_PLAYER_TEAM_3 = 1004,
	CAMP_PLAYER_TEAM_2 = 1003,
	CAMP_PLAYER_TEAM_1 = 1002,
	CAMP_PLAYER_DEFAULT = 1001,
	SKILL_FIRE_DURATION = 1,
	LEVEL_CONDITION_ON = 1,
	LEVEL_CONDITION_OFF = 0,
	GHOST_EYE_STATE_DETECT_ALL = 5,
	GHOST_EYE_STATE_NIGHT_VISION = 4,
	PLAYER_INIT_STATUS_PREINIT = 2,
	PLAYER_INIT_STATUS_INIT = 3,
	PLAYER_INIT_STATUS_POSTINIT = 4,
	PLAYER_INIT_STATUS_START = 5,
	EVENT_LEAVE_PET_CLIENT_FORCE = 51,
	EVENT_PET_DIE = 60,
	EVENT_CLIENT_PRE_EXPLORE = 101,
	EVENT_ENTER_SCENE = 102,
	EVENT_RESET_SCENE = 103,
	PET_STATE_BACK = 1,
	PET_STATE_GO = 2,
	PET_STATE_STOP = 3,
	GHOST_EYE_STATE_OFF = 0,
	GHOST_EYE_STATE_BOTH_SIDE = 1,
	GHOST_EYE_STATE_DETECT_TAG = 2,
	PET_BI_ADD_NORMAL_HATCH = 10,
	PET_BI_DEL_CHANGE_FORM = 9,
	PET_BI_ADD_CHANGE_FORM = 8,
	PET_BI_DEL_GM = 7,
	PET_BI_DEL_EVOLVE = 6,
	PET_BI_DEL_RECYCLE = 5,
	PET_BI_ADD_GM = 4,
	PET_BI_ADD_EVOLVE = 3,
	PET_BI_ADD_HATCH = 2,
	PET_BI_ADD_CAPTURE = 1,
	CHANGE_CONTROL_COMBAT_CD = 0.5,
	CHANGE_CONTROL_CD = 0.5,
	LEAVE_CONTROL_COST_EP = 0,
	LEAVE_CONTROL_COST_AP = 0,
	ENTER_CONTROL_COST_EP = 0,
	ENTER_CONTROL_COST_AP = 0,
	GHOST_EYE_STATE_DETECT_CAMOUFLAGE = 3,
	MSEC_ONE_MINUTE = 60000,
	MSEC_ONE_DAY = 86400000,
	SECONDS_ONE_WEEK = 604800,
	MINUTES_ONE_DAY = 1440,
	MINUTES_ONE_HOUR = 60,
	HOURS_ONE_DAY = 24,
	PERCENT_THOUSAND = 1000,
	NUMBER_MAX = 1e+308,
	NUMBER_MIN = -1e+308,
	INT_MAX = 2147483647,
	INT_MIN = -2147483648,
	UINT_MAX = 4294967295,
	SPECIAL_TRAIN_TYPE_REWARD = 0,
	SPECIAL_TRAIN_BADGE_REWARD = 1,
	QUEST_TYPE_MAIN = 1,
	QUEST_TYPE_NORMAL = 2,
	QUEST_TYPE_FESTIVAL = 3,
	QUEST_TYPE_GUIDE_SIDE = 4,
	QUEST_TYPE_STORY_SIDE = 5,
	QUEST_TYPE_OTHER = 6,
	QUEST_TYPE_TRADE = 7,
	QUEST_TYPE_TRADE_SUB = 8,
	QUEST_TYPE_TEACH_EXPLORE = 9,
	QUEST_TYPE_EXPLORE = 10,
	QUEST_TYPE_TRIVIAL_DAILY = 12,
	QUEST_TYPE_TOUR = 13,
	QUEST_TYPE_MYSTICAL = 14,
	QUEST_TYPE_FUGITIVE_ISLAND = 15,
	QUEST_TYPE_PET = 16,
	QUEST_TYPE_CLASS = 17,
	QUEST_TYPE_STORY = 18,
	QUEST_TYPE_SHURA = 19,
	QUEST_TYPE_RACE = 20,
	INTERACT_DISTANCE_TOLERANCE = 10,
	NPC_FUNC_CFG_POS_CONDITION = 3,
	GROUP_DROP_HIDE_PLAYER_LEAVE = 5,
	NIL = "defnil",
	LINE_INIT = 1,
	LINE_NORMAL = 2,
	LINE_BELOW_DESTROY_THD = 3,
	LINE_BEFORE_DESTROY = 4,
	LINE_KICK_FOR_DESTROY = 5,
	EPBI_REPLY = 2,
	EPBI_QUIT = 3,
	EPBI_SETTLE = 4,
	EPQR_CLIENT_QUIT = 1,
	EPQR_SERVER_CHECK_ERROR = 500,
	EPRR_PET_IN_TEAM = 1,
	EPRR_FRIENDSHIP_LOW = 2,
	EPRR_EXCHANGE_CD = 3,
	EPRR_PET_TYPE_FORBID = 4,
	EPRR_LIMIT_EXCEED = 5,
	EPRR_PET_IN_HOME = 6,
	EPRR_ITEM_BAG_FULL = 7,
	EPRR_PET_IN_DISPATCH = 8,
	EPAR_COST_LACK = 1,
	EPAR_FRIENDSHIP_LOW = 2,
	EPAR_EXCHANGE_CD = 3,
	EPAR_PET_TYPE_FORBID = 4,
	EPAR_LIMIT_EXCEED = 5,
	EPAR_ADD_PET_FORBID = 6,
	EXCHNAGE_INVITE_CD_TIME = 10,
	EXCHNAGE_INVITE_TIMEOUT = 30,
	EXCHANGE_DISTANCE = 10,
	GROUP_TYPE_SELF = 0,
	GROUP_TYPE_BASE = 1,
	PROP_ENHANCE_ADJUST_MAIL = 13,
	INHERITANCE_IDX_RESONANCE = 1,
	INHERITANCE_IDX_LEARN = 2,
	INHERITANCE_IDX_LEVEL = 3,
	INHERITANCE_INHERIT = 0,
	INHERITANCE_SWAP = 1,
	INHERITANCE_FRUIT_KEEP = 0,
	INHERITANCE_FRUIT_SWAP = 1,
	PRL_BI_REFRESH = 1,
	PRL_BI_REPORT = 2,
	PRL_BI_REWARD = 3,
	PRS_BI_REFRESH = 1,
	PRS_BI_REPORT = 2,
	PRS_BI_REWARD = 3,
	PROP_TYPE_BASE = 1,
	PROP_TYPE_ADVANCED = 2,
	PROP_PREVIEW_MAX_LEVEL = 1,
	PROP_PREVIEW_EXCHANGE = 2,
	PROP_PREVIEW_EXCHANGE_SEND = 3,
	ISSM_OFFLINE_SIMULATE = 1,
	ISSM_HOMECAMP_LOAD_LINE_INFO = 2,
	ISSM_GET_HOME_BASIC_INFO = 4,
	ROB_EGG_TEAM_NUM = 3,
	ROB_EGG_SCENE_ID = 3004,
	ROB_EGG_SCENE_CLIP_ID = 3005,
	ROB_EGG_MATCH_NUM = 2,
	ROB_EGG_PLAYER_DEATH_BOX_TEMPLATE_ID = 100000,
	ORNAMENT_SWITCH_MAX_NUM = 200,
	CREATE_ALL_PUPPET_DEFAULT = 0,
	CREATE_ALL_PUPPET_MULTIFORM = 1,
	CARRY_REQ_FROM_POPUP = 1,
	CARRY_REQ_FROM_PET_MANAGEMENT = 2,
	CARRY_REQ_FROM_INTERACTION = 3,
	HUG_TARGET_MODE_PLAYER = 1,
	HUG_TARGET_MODE_PET = 2,
	NPC_DUEL_SCENE_ID = 30001,
	ROB_LOOT_ITEM_FINISH_DISCOVERY = 999999,
	DOUYIN_OFFLINE_SCENE_ID = 3007,
	LIFE_DEAD_BY_CLIFF = 16,
	LIFE_DEAD_BY_ROLL_OVER = 8,
	LIFE_DEAD_BY_FALL_TO_GROUND = 4,
	LIFE_DEAD_BY_WATER = 2,
	LIFE_DEAD_BY_COMBAT = 1,
	COMBAT_TYPE_TWO_PET = 2,
	COMBAT_TYPE_ONE_PET = 1,
	COMBAT_TYPE_DEFAULT = 0,
	PET_TEM_TYPE_TMP_BOT_NPCDUEL = 9,
	PET_TEM_TYPE_TMP_BOT_BOSSRUSH = 8,
	PET_TEAM_TYPE_TMP_ROBEGG = 7,
	PET_TEAM_TYPE_TMP_CATCH_ROGUE = 6,
	PET_TEAM_TYPE_TMP_BOSS_CHALLENGE = 5,
	PET_TEAM_TYPE_TMP_STANDARD = 4,
	PET_TEAM_TYPE_TMP_EVENT = 3,
	PET_TEAM_TYPE_TMP_UNFAIR_PVP = 2,
	PET_TEAM_TYPE_TMP_FAIR_PVP = 1,
	PET_TEAM_TYPE_DEFAULT = 0,
	SWITCH_PET_TYPE_EVENT = 2,
	SWITCH_PET_TYPE_CONFIG = 1,
	SWITCH_PET_TYPE_DEFAULT = 0,
	PHASE_BI_LEAVE = 2,
	PHASE_BI_ENTER = 1,
	ClientSeamlessQuitPortalId = -1000,
	SeamlessPortalId = -999,
	DynamicPhasePortId = -998,
	AREA_POLYGON = 2,
	AREA_RECTANGLE = 1,
	AREA_CIRCLE = 0,
	STATIC_RECTANGLE = 3,
	STATIC_CIRCLE = 2,
	DYNAMIC_CIRCLE = 1,
	PET_TYPE_CUR = 1,
	PET_TYPE_ANY = 0,
	LIFE_FAKE_DEAD_CAN_HIT = 6,
	LIFE_NEAR_DEAD = 5,
	LIFE_FALLEN = 4,
	LIFE_DEAD = 3,
	LIFE_FAKE_DEAD = 2,
	LIFE_ALIVE = 1,
	SPACE_TYPE_DUNGEON_OVER = 201,
	SPACE_TYPE_WEEKLY_DUNGEON = 104,
	SPACE_TYPE_TEAM_PVE_DUNGEON = 103,
	SPACE_TYPE_NPC_DUEL = 102,
	SPACE_TYPE_FISHING_CAPTURE_DUNGEON = 101,
	SPACE_TYPE_ROBEGG_UNDERGROUND = 100,
	SPACE_TYPE_DUNGEON_START = 100,
	SPACE_TYPE_HOMECAMP = 18,
	SPACE_TYPE_HOMELAND = 16,
	SPACE_TYPE_DUNGEON_END = 15,
	SPACE_TYPE_CATCH_ROGUE_DUNGEON = 14,
	SPACE_TYPE_BOSS_RUSH = 13,
	SPACE_TYPE_ROBEGG = 12,
	SPACE_TYPE_DITTO_DUNGEON = 11,
	SPACE_TYPE_SOUDACHE_PVP_DUNGEON = 10,
	SPACE_TYPE_BOSS_DUNGEON = 9,
	SPACE_TYPE_PVE_DUNGEON = 8,
	SPACE_TYPE_ROGUE_DUNGEON = 7,
	SPACE_TYPE_PVP_DUNGEON = 6,
	SPACE_TYPE_PHASE = 5,
	SPACE_TYPE_DUNGEON = 4,
	SPACE_TYPE_LINE = 3,
	SPACE_TYPE_SINGLEWORLD = 2,
	SPACE_TYPE_TOWN = 1,
	SPACE_TYPE_NONE = 0,
	COUNTRY_OF_TIME = 300001,
	MAX_EXP_TIMES_WHEN_STAGE_LIMIT = 1,
	PET_EXPLORE_PREPARE_NUM_LIMIT = 3,
	PET_PREPARE_NUM_LIMIT = 4,
	PCTR_SHAPE_SHIFT = 3,
	PCTR_CHANGE_FORM = 2,
	PCTR_EVOLVE = 1,
	EXPLORE_FORMATION_INDEX = 1,
	FOR_LOOP_MAX_100000 = 100000,
	FOR_LOOP_MAX_10000 = 10000,
	FOR_LOOP_MAX_1000 = 1000,
	FOR_LOOP_MAX_100 = 100,
	MERGE_TYPE_SUM = 4,
	MERGE_TYPE_MAX = 3,
	MERGE_TYPE_MIN = 2,
	MERGE_TYPE_BASE = 1,
	MERGE_TYPE_SELF = 0,
	GROUP_TYPE_ALL = 3,
	GROUP_TYPE_ANY = 2,
	CATCH_REPORT_HIGH_CP = 4,
	CATCH_REPORT_SHINY = 3,
	CATCH_REPORT_SHINING_STAR = 2,
	CATCH_REPORT_BEHIND = 2,
	CATCH_REPORT_COUNT = 1,
	COPY_PLAYER_REGION_SYNC = 5,
	COPY_PLAYER_GM = 4,
	COPY_PLAYER_GUIDANCE = 3,
	COPY_PLAYER_TEMPLATE = 2,
	COPY_PLAYER_PYTHON = 1,
	VIRTUAL_PUPPET_PLAYER_NOT_CHOOSE = 2,
	VIRTUAL_PUPPET_PLAYER_CHOOSE = 1,
	ESM_INTERACT = 8,
	ESM_USE_ITEM = 4,
	ESM_CUSTOM_CONDITION = 2,
	ESM_QUEST = 1,
	ESM_ANY = 0,
	PET_EXP_BI_TASK = 4,
	PET_EXP_BI_USE_ITEM = 3,
	PET_EXP_BI_CAPTURE = 2,
	PET_EXP_BI_KILL = 1,
	SERVER_POS_CHECK_TOLERANCE = 1,
	SERVER_DRIVEN_DUNGEON_FOG = true,
	EPBI_INVITE = 1,
	LINE_KICK_FOR_DESTROY_TIME = 5,
	LINE_DESTROY_TIME = 60,
	LINE_DESTROYING = 6,
	MAP_FOG_INC_SERVER_PUSH = 4,
	MAP_FOG_INC_UPLOAD = 3,
	MAP_FOG_FIRST_CREATE = 2,
	MAP_FOG_FULL_DOWNLOAD = 1,
	LOCAL_SERVER_QUERY_STATUS_PORT = 23000,
	DIRECTOYR_CLIENT_PULL_INTERVAL = 5,
	DIRECTOYR_SERVER_PUSH_INTERVAL = 30,
	GROUP_DROP_HIDE_PUPPET_DESTROY = 4,
	GROUP_DROP_HIDE_GIVEUP = 3,
	GROUP_DROP_HIDE_CAPTURE_FAILED = 2,
	GROUP_DROP_HIDE_CAPTURE_SUCCESS = 1,
	GROUP_DROP_NOTIFY_CHEST_CREATED = 3,
	GROUP_DROP_NOTIFY_HIDE_BOSS = 2,
	GROUP_DROP_NOTIFY_ENDTS = 1,
	GROUP_DROP_CHOICE_GIVEUP = 2,
	GROUP_DROP_CHOICE_CAPTURE = 1,
	TALENT_PROP_IDX_MAX = 5,
	TALENT_PROP_IDX_PROPID = 1,
	RESEARCH_REPORT_TARGET_MIN = 11,
	RESEARCH_REPORT_AVATAR_RAINBOW = 4,
	RESEARCH_REPORT_TRAIT = 3,
	RESEARCH_REPORT_AVATAR_SHINY = 2,
	RESEARCH_REPORT_AVATAR_NORMAL = 1,
	CATCH_REPORT_PLENTY = 7,
	CATCH_REPORT_ONCE = 6,
	CATCH_REPORT_RAINBOW = 5,
	CATCH_REPORT_RARE_SKILL = 5,
	CATCH_REPORT_ELITE = 4,
	MAP_MARK_SOURCE_INTERACT = "interact",
	MAP_MARK_SOURCE_ROB_EGG = "rob_egg",
	MAP_MARK_SOURCE_ACTIVITY = "activity",
	MAP_MARK_SOURCE_GM = "gm",
	MAP_MARK_SOURCE_QUEST = "quest",
	MAP_MARK_SOURCE_CLIENT_RPC = "client_rpc",
	MAP_MARK_SOURCE_SANDBOX = "sandbox",
	MAP_MARK_SOURCE_GRAPH = "graph",
	MAP_MARK_SOURCE_UNKNOWN = "unknown",
	MAP_MARK_STATUS_MAX = 3,
	MAP_MARK_STATUS_CLOSED = 3,
	MAP_MARK_STATUS_UNLOCKED = 2,
	MAP_MARK_STATUS_LOCKED = 1,
	MAP_MARK_STATUS_HIDE = 0,
	MAP_MARK_GRAB_EGG = 123,
	MAP_MARK_GOLD_MONSTER = 121,
	MAP_MARK_FAST_TARGET = 120,
	MAP_MARK_AFFILIATED_CAMP = 115,
	MAP_MARK_CLUE = 109,
	MAP_MARK_LEYLINETREE = 107,
	MAP_MARK_SHARE = 104,
	MAP_MARK_INFO_STAMP = 103,
	MAP_MARK_CUSTOM = 101,
	MAP_MARK_QUEST = 100,
	MAP_MARK_NAV_TRANSIT = 80,
	MAP_MARK_DYNAMIC = 66,
	MAP_MARK_HOME_CAMP = 32,
	MAP_MARK_EcoTrace_Search = 31,
	MAP_MARK_COUSTOM_TRACE = 29,
	MAP_MARK_TRACE = 27,
	MAP_MARK_LeylineFlower_Create = 26,
	MAP_MARK_LeylineTree_Create = 26,
	MAP_MARK_ALLY = 21,
	MAP_MARK_Decryption = 17,
	MAP_MARK_ZONE = 13,
	MAP_MARK_BONFIRE = 12,
	MAP_MARK_CAMP = 11,
	MAP_MARK_CHEST = 5,
	BADGE_SHOW_COUNT = 4,
	RESET_ALL_PETS_BASE = 5,
	RESET_ALL_PETS_FORM = 4,
	RESET_ALL_PETS_CLEAR = 3,
	RESET_ALL_PETS_SUPER = 2,
	RESET_ALL_PETS_HANDBOOK = 1,
	RESET_ALL_PETS_DEFAULT = 0,
	OBSERVE_MODE = 3,
	SHOW_GM_PANEL = 2,
	NO_COST_MODE = 1,
	NORMAL_MODE = 0,
	GENDER_TYPE_WINTER = 6,
	GENDER_TYPE_AUTUMN = 5,
	GENDER_TYPE_SUMMER = 4,
	GENDER_TYPE_SPRING = 3,
	GENDER_TYPE_FEMALE = 2,
	GENDER_TYPE_MALE = 1,
	GENDER_TYPE_NONE = 0,
	SPAWN_STATE_OPEN = 1,
	SPAWN_STATE_CLOSE = 0,
	SPAWN_STATE_DISABLE = -1,
	SPAWN_CATCH_SUB_TYPE_CATCH = 2,
	SPAWN_CATCH_SUB_TYPE_DESTROY = 1,
	SPAWN_TYPE_CONDITION = 17,
	SPAWN_TYPE_CAROUSEL = 16,
	SPAWN_TYPE_RESET = 15,
	SPAWN_TYPE_ITEM = 14,
	SPAWN_TYPE_OVERRIDE = 13,
	SPAWN_TYPE_LOOP = 12,
	VIEW_TYPE = {
		FAN = 2,
		CIRCLE = 1
	},
	PET_RELEASE_SNAPSHOT_EXCLUDE_FIELDS = {
		"id",
		"uuid",
		"time",
		"countId",
		"firstCreate",
		"removePetOperating",
		"battleTimeMap",
		"controlKillPuppetNum",
		"homelandPutInTime",
		"triggerMap",
		"eventMap",
		"unlockedAbilityMap",
		"curAbilityMap",
		"coreCarryPos",
		"appliedCarryRecommendType",
		"petBallId",
		"isPutInHomeCamp",
		"putInHomelandBegTm",
		"exchangeTs",
		"exchangeFromUid",
		"giveFromUid",
		"gotInFollowed",
		"isTwinChoice",
		"isTrial",
		"breedSource",
		"breedCount",
		"activityDispatching",
		"tmpTemplateId",
		"customName",
		"favoriteType",
		"label",
		"isFavorite",
		"individuationIds",
		"fetter"
	},
	PET_RELEASE_RESTORE_WHITELIST = {
		"templateId",
		"level",
		"exp",
		"expFromItem",
		"nature",
		"propertyScoreStage",
		"basePropertyList",
		"propertyEnhancedCount",
		"characterInfo",
		"resonanceInfo",
		"talentList",
		"gender",
		"shinyStyle",
		"bornScale",
		"height",
		"weight",
		"transmogUnlockSolts",
		"transmogProgress",
		"currTransmogScheme",
		"selectTransmogScheme",
		"tempTransmogSchemes",
		"customTransmogSchemes"
	},
	PET_SPAWN_YAW = {
		120,
		240
	},
	PET_SPAWN_DISTANCE = {
		1.5,
		2.5
	},
	MAP_INFO_BOSS_PANEL = {
		[10304] = true,
		[10404] = true
	},
	REPR_MAP_PET_HBMSK = {
		"1-known",
		"2-catched",
		nil,
		"3-shiny-known",
		nil,
		nil,
		nil,
		"4-shiny-catched",
		nil,
		nil,
		nil,
		nil,
		nil,
		nil,
		nil,
		"5-researched",
		[64] = "7-elite-catched",
		[32] = "6-elite-known",
		[256] = "9-rainbow-known",
		[512] = "10-rainbow-catched",
		[128] = "8-evolve-get"
	},
	PET_ORIGIN = {
		LEYLINE_TREE = 2,
		LEYLINE_FLOWER = 1,
		UNKNOWN = 0
	},
	LOGIN_SERVER_TYPE = {
		LOCAL = 1,
		DUMMY = 0,
		SHARED = 3,
		PUBLIC = 2
	},
	LOGIN_SERVER_NAME_PREFIX = {
		[0] = "",
		"",
		"",
		"[shared]"
	},
	MAP_FOG_LOG_STR = {
		"FullDownload",
		"FirstCreate",
		"IncUpload",
		"IncServerPush"
	},
	TWIN_PET_CHOICE_MAP = {
		[1] = 2,
		[2] = 1
	}
}

Const.TRACK_TYPE = {
	PVP = 1,
	NORMAL = 0
}
Const.TRACK_SHARE_TYPE = {
	SHARE_TYPE_NONE = 0,
	SHARE_TYPE_TEAM = 1
}
Const.ROB_EGG_TYPE = {
	BIG = 2,
	SMALL = 1,
	SUPER_BIG = 3
}
Const.ROB_EGG_SMALL_EGG_NUM = 9
Const.ROB_EGG_SMALL_EGG_INDEX_BASE = 5010000
Const.ROB_EGG_ATTACH_CONFIG_ID = 11021
Const.ROB_EGG_STRUGGLE_QTE_GROUP_ID = "QTE_Become_Egg_Free"
Const.ROB_EGG_SHAKE_AMPLITUDE_LIGHT = {
	4,
	4,
	4
}
Const.ROB_EGG_SHAKE_AMPLITUDE_HEAVY = {
	8,
	8,
	8
}
Const.ROB_EGG_EXTRACT_TYPE = {
	RANDOM = 1,
	NORMAL = 0
}
Const.PhotoCheckScene = {
	HeadImage = "headImage",
	Report = "report",
	CampMap = "campmap",
	MediaMarker = "MediaMarker",
	CityName = "cityname",
	OSS = "OSS",
	CityMap = "citymap",
	Share = "share"
}
Const.COMBAT_PROPERTY = {
	maxBp = "maxBp",
	curBp = "curBp",
	forceLock = "forceLock",
	combatStatus = "combatStatus",
	maxStamina = "maxStamina",
	maxEp = "maxEp",
	curEp = "curEp",
	maxHp = "maxHp",
	curHp = "curHp",
	maxSp = "maxSp",
	curSp = "curSp",
	isPauseBt = "isPauseBt",
	gmMode = "gmMode",
	aiState = "aiState",
	isTransparent = "isTransparent",
	lastSurvivalTime = "lastSurvivalTime",
	bornTime = "bornTime",
	life = "life"
}
Const.ROGUE_BUFF_SOURCE = {
	STAGE_CHANGE = 0,
	EXTRA_BUFF = 100,
	SERIES_INIT_BUFF = 3,
	TALENT_INIT_BUFF = 2,
	STAGE_CHANGE_EXTRA = 1
}
Const.ROGUE_BUFF_RANDOM_NUM = 3
Const.ROGUE_BUFF_SELECT_NUM = 1
Const.ROGUE_INIT_SERIES_CONSTANT_RANDOM_NUM = 3
Const.ROGUE_SERIES_SELECT_DELAY_VALUE = 99
Const.ROGUE_SERIES_SELECT_DELAY_SHOW_ITEMS = {
	2902000,
	2902001,
	2902002
}
Const.RogueDiceMachineType = {
	Buff = 2,
	Npc = 1
}
Const.ROGUE_TALENT = {
	ATTR_ADD = 1,
	ATTR_REMOVE = 2
}
Const.InviteWorldType = {
	SOCIAL_FLUTE = 4,
	NORMAL_INVITE = 3,
	SOCIAL_HORN = 2,
	EXCHANGE_PET = 1
}
Const.InviteWorldNeedMoveToInvitor = {
	[Const.InviteWorldType.EXCHANGE_PET] = true,
	[Const.InviteWorldType.SOCIAL_HORN] = true,
	[Const.InviteWorldType.NORMAL_INVITE] = true,
	[Const.InviteWorldType.SOCIAL_FLUTE] = true
}
Const.CLEN_USR_TYPE_MAP = {
	Player = Const.CLEN_USR_TYPE_PLAYER,
	PvpBotPlayer = Const.CLEN_USR_TYPE_BOT_PLAYER,
	GuidancePlayer = Const.CLEN_USR_TYPE_PLAYER,
	RegionMirrorPlayer = Const.CLEN_USR_TYPE_PLAYER,
	PlayerGhost = Const.CLEN_USR_TYPE_PLAYER_GHOST,
	Pet = Const.CLEN_USR_TYPE_PET,
	Creation = Const.CLEN_USR_TYPE_CREATION,
	TrapBall = Const.CLEN_USR_TYPE_OTHER,
	Puppet = Const.CLEN_USR_TYPE_MONSTER,
	ServerPuppet = Const.CLEN_USR_TYPE_MONSTER,
	Chest = Const.CLEN_USR_TYPE_INTERACTOR,
	ArkChest = Const.CLEN_USR_TYPE_INTERACTOR,
	CollectItem = Const.CLEN_USR_TYPE_INTERACTOR,
	EnvObject = Const.CLEN_USR_TYPE_ENVOBJ,
	BattleField = Const.CLEN_USR_TYPE_OTHER,
	InteractorPetEgg = Const.CLEN_USR_TYPE_INTERACTOR,
	CylinderTrapItem = Const.CLEN_USR_TYPE_OTHER,
	ResPointEntity = Const.CLEN_USR_TYPE_RESPOINT,
	BotPet = Const.CLEN_USR_TYPE_PET,
	CampCar = Const.CLEN_USR_TYPE_OTHER,
	ResourceBox = Const.CLEN_USR_TYPE_INTERACTOR,
	SpellField = Const.CLEN_USR_TYPE_SPELLFIELD,
	DungeonBotPet = Const.CLEN_USR_TYPE_PET,
	DungeonBotPlayer = Const.CLEN_USR_TYPE_BOT_PLAYER
}
Const.ROBEGG_DEATH_REASON = {
	INVALID = 0,
	TIME_OUT = 4,
	ACCIDENGTAL_DEATH = 3,
	KILLED_BY_PUPPET = 2,
	KILLED_BY_PLAYER = 1
}
Const.CLEN_USR_TYPE_CLIENT_MAP = {
	ClientTempPlayer = -1,
	ClientVirtualAIEntity = Const.CLEN_USR_TYPE_VIRTUAL_AI,
	ClientPetBallEntity = Const.CLEN_USR_TYPE_VIRTUAL_AI,
	ClientVirtualTarget = Const.CLEN_USR_TYPE_VIRTUAL_TARGET,
	ClientEnvObject = Const.CLEN_USR_TYPE_ENVOBJ
}
Const.SPACE_TYPE_TO_NAME = {
	[Const.SPACE_TYPE_SINGLEWORLD] = "SingleWorld",
	[Const.SPACE_TYPE_LINE] = "Line",
	[Const.SPACE_TYPE_DUNGEON] = "Dungeon",
	[Const.SPACE_TYPE_PVP_DUNGEON] = "PvpDungeon",
	[Const.SPACE_TYPE_PVE_DUNGEON] = "PveDungeon",
	[Const.SPACE_TYPE_DITTO_DUNGEON] = "DittoDungeon",
	[Const.SPACE_TYPE_ROGUE_DUNGEON] = "RogueDungeon",
	[Const.SPACE_TYPE_BOSS_DUNGEON] = "BossChallengeDungeon",
	[Const.SPACE_TYPE_HOMELAND] = "Homeland",
	[Const.SPACE_TYPE_HOMECAMP] = "HomeCamp",
	[Const.SPACE_TYPE_SOUDACHE_PVP_DUNGEON] = "SoudachePvpDungeon",
	[Const.SPACE_TYPE_ROBEGG] = "RobEggDungeon",
	[Const.SPACE_TYPE_BOSS_RUSH] = "BossRushDungeon",
	[Const.SPACE_TYPE_CATCH_ROGUE_DUNGEON] = "CatchRogueDungeon",
	[Const.SPACE_TYPE_ROBEGG_UNDERGROUND] = "RobEggUnderGroundPlace",
	[Const.SPACE_TYPE_FISHING_CAPTURE_DUNGEON] = "FishingCaptureDungeon",
	[Const.SPACE_TYPE_NPC_DUEL] = "NpcDuelDungeon",
	[Const.SPACE_TYPE_TEAM_PVE_DUNGEON] = "TeamPveDungeon",
	[Const.SPACE_TYPE_WEEKLY_DUNGEON] = "WeeklyDungeon"
}
Const.NPC_FIGHT_NODE_STATE = {
	LOCKED = 0,
	FAILED = 4,
	CLEARED = 3,
	IN_BATTLE = 2,
	READY = 1
}
Const.NPC_FIGHT_RESULT = {
	FAILED = 2,
	UNKNOWN = 0,
	SUCCESS = 1
}
Const.NPC_FIGHT_CLOSE_REASON = {
	PLAYER_LEAVE = 2,
	NODE_FAILED = 4,
	NORMAL = 1,
	UNKNOWN = 0,
	CONFIG_ERROR = 3
}
Const.ROBEGG_SCENEID_TO_NAME = {
	[3004] = "RobEggPvpDungeon",
	[3005] = "RobEggPveDungeon"
}
Const.STAGE_TO_RATING_STR = {
	"INTERFACE_DISPLAY_RATING_1",
	"INTERFACE_DISPLAY_RATING_2",
	"INTERFACE_DISPLAY_RATING_3",
	"INTERFACE_DISPLAY_RATING_4"
}
Const.ACTOR_TYPE_NAME = {
	[Const.ACTOR_TYPE_PLAYER] = "player",
	[Const.ACTOR_TYPE_PET] = "pet",
	[Const.ACTOR_TYPE_PUPPET] = "puppet",
	[Const.ACTOR_TYPE_CREATION] = "creation",
	[Const.ACTOR_TYPE_INTERACTOR] = "interactor",
	[Const.ACTOR_TYPE_VIRTUAL] = "virtual",
	[Const.ACTOR_TYPE_TrapBall] = "trapBall",
	[Const.ACTOR_TYPE_BOTPLAYER] = "botPlayer",
	[Const.ACTOR_TYPE_SpaceSpawner] = "spaceSpawner",
	[Const.ACTOR_TYPE_ENVOBJ] = "envObj",
	[Const.ACTOR_TYPE_STATICNPC] = "staticNpc",
	[Const.ACTOR_TYPE_MMOITEM] = "mmoItem",
	[Const.ACTOR_TYPE_RESPOINT] = "resPoint",
	[Const.ACTOR_TYPE_VEHICLE] = "vehicle",
	[Const.ACTOR_TYPE_CAMPCAR] = "campCar",
	[Const.ACTOR_TYPE_SPELLFIELD] = "spellField"
}
Const.DAY_LOGIC_START = 0
Const.DAY_LOGIC_END = 1440

local ACTOR_ORDER_TYPE = {}

ACTOR_ORDER_TYPE.MOVE_START = 0
ACTOR_ORDER_TYPE.MOVE_STOP = 1
ACTOR_ORDER_TYPE.TURN = 2
ACTOR_ORDER_TYPE.JUMP = 3
ACTOR_ORDER_TYPE.DASH = 4
ACTOR_ORDER_TYPE.DRAW_BOW = 5
ACTOR_ORDER_TYPE.ABILITY = 6
Const.ACTOR_ORDER_TYPE = ACTOR_ORDER_TYPE
Const.ACTOR_TYPE_TO_CAMP = {
	[Const.ACTOR_TYPE_NONE] = Const.CAMP_PEACE,
	[Const.ACTOR_TYPE_PLAYER] = Const.CAMP_PLAYER_DEFAULT,
	[Const.ACTOR_TYPE_PET] = Const.CAMP_PLAYER_DEFAULT,
	[Const.ACTOR_TYPE_PUPPET] = Const.CAMP_MONSTER_DEFAULT,
	[Const.ACTOR_TYPE_CREATION] = Const.CAMP_PEACE,
	[Const.ACTOR_TYPE_INTERACTOR] = Const.CAMP_PEACE,
	[Const.ACTOR_TYPE_BOTPLAYER] = Const.CAMP_PLAYER_DEFAULT
}
Const.SCENE_ID = {
	ARK = 501,
	BEGINNER = 3002,
	COT = 3000
}
Const.WEAPON_STATE_HANGUP = 0
Const.WEAPON_STATE_ATTACH = 1
Const.COMMON_BASIC_ATTRIBS = {
	"hp_max_v",
	"sp_max_v",
	"ep_max_v"
}
Const.COMMON_BASIC_ATTRIBS_EXTRA = {
	"turn_speed"
}
Const.BASE_ATTRS_FIXED_RATE_MAP = {
	ep_regen_force_v = "fixed_ep_regen_force_v_rate",
	atk_mag_v = "fixed_atk_mag_rate",
	hp_max_v = "fixed_hp_rate",
	atk_v = "fixed_atk_rate",
	def_mag_v = "fixed_def_mag_v_rate",
	def_v = "fixed_def_v_rate"
}
Const.BOSS_GRADE_ATTRIBUTE_MAP = {
	def_v = true,
	def_mag_v = true,
	atk_v = true
}
Const.BASE_TALENT_POINT_RANDOM_MAX = 50
Const.BASE_SPECIES_POINT_MAX = 100000
Const.BASE_SPECIES_POINT_MIN = 0
Const.BASE_PROPERTY_HP_IDX = 1
Const.BASE_PROPERTY_ATK_IDX = 2
Const.BASE_PROPERTY_DEF_IDX = 3
Const.BASE_PROPERTY_EP_REGEN_FORCE_IDX = 4
Const.BASE_PROPERTY_DEF_MAG_IDX = 5
Const.BASE_PROPERTY_ATK_MAG_IDX = 6
Const.BASE_PROPERTY_CNT = 6
Const.NEW_BASE_PRO_CNT = 6
Const.NEW_BASE_PRO_VIT = 1
Const.NEW_BASE_PRO_STR = 2
Const.NEW_BASE_PRO_STA = 3
Const.NEW_BASE_PRO_HST = 4
Const.NEW_BASE_PRO_SPI = 5
Const.NEW_BASE_PRO_IMP = 6
Const.NEW_BASE_PROP_IDX2ATTR_MAP = {
	"primary_convert_vit",
	"primary_convert_str",
	"primary_convert_sta",
	"primary_convert_hst",
	"primary_convert_spi",
	"primary_convert_imp"
}
Const.NEW_BASE_PROP_ATTR2REFID_MAP = {
	primary_convert_imp = 116,
	primary_convert_spi = 114,
	primary_convert_hst = 115,
	primary_convert_sta = 113,
	primary_convert_str = 111,
	primary_convert_vit = 112
}
Const.PET_CONVERT_VALTYPE = {
	Direct = 0,
	Ratio = 1
}
Const.NEW_PROP_SPECIAL_LV = 10
Const.ATTRIBUTE_NAME_LIST = {
	"ATTRIBUTE_HP",
	"ATTRIBUTE_ATTACK",
	"ATTRIBUTE_DEFINE",
	"ATTRIBUTE_RECOVER",
	"ATTRIBUTE_SP_DEFINE",
	"ATTRIBUTE_SP_ATTACK"
}
Const.NEW_BASE_PRO_INIT_TYPE = {
	CubeRandom = 2,
	Direct = 0,
	Random = 1
}
Const.BASE_PRO_INIT_SOURCE = {
	Egg = 1,
	Self = 3,
	Cube = 2
}
Const.SPAWN_COUNT_IN_BATCH = 10
Const.NPC_STATUS = {
	MONSTER = 1,
	NPC = 0
}
Const.NPC_TYPE = {
	Human = 0,
	None = -1,
	LeylineFlower = 6,
	RobEggLimitPillar = 7,
	Pet = 1,
	GrabEggTransfer = 4,
	LeylineTree = 3,
	EnvObj = 2
}
Const.NPC_CONTROL_TYPE = {
	SimpleMove = 2,
	Static = 1
}
Const.NPC_TYPE_TO_CLASS = {
	[Const.NPC_TYPE.Human] = "Puppet",
	[Const.NPC_TYPE.Pet] = "Pet",
	[Const.NPC_TYPE.EnvObj] = "EnvObject",
	[Const.NPC_TYPE.LeylineTree] = "LeylineTree",
	[Const.NPC_TYPE.GrabEggTransfer] = "GrabEggTransfer",
	[Const.NPC_TYPE.LeylineFlower] = "LeylineFlower"
}
Const.INTERACT_LIMIT = {
	CHEST = 1,
	COMMON = 999
}
Const.INTERACTOR_STATUS = {
	ENVOBJ_OPENED = 2,
	CHEST_OPENED = 1,
	INIT = 0,
	COLLECT_ITEM_OPENED = 3
}
Const.PET_LABEL_MASK = {
	MAGIC = 16,
	DARK = 16,
	VARIANT = 8,
	NORMAL = 0,
	BOSS = 2,
	SHINY = 1,
	ELITE = 4,
	RAINBOW = 32
}
Const.PET_SKILL_UPGRADE_SOURCE = {
	GM = 16,
	CONDITIONAL = 8,
	EVENT = 4,
	ELITE_BOSS = 2,
	CORE_CARRY = 1,
	NONE = 0
}
Const.PET_SHINY_STYLE = {
	WHITE = 11,
	BLACK = 12
}
Const.PET_BODY_SIZE_TYPE = {
	MINI = 1,
	NORMAL = 0
}
Const.REPR_PET_LABEL_MASK = {
	[0] = "0-normal",
	"1-shiny",
	"2-boss",
	nil,
	"3-elite",
	nil,
	nil,
	nil,
	"4-variant",
	nil,
	nil,
	nil,
	nil,
	nil,
	nil,
	nil,
	"5-magic",
	[32] = "6-rainbow"
}
Const.FormName2Id = {
	highland = 2,
	basic = 1,
	blackrainbow = 18,
	cloud = 17,
	plateau = 16,
	grassland = 15,
	forest = 14,
	flowersea = 13,
	mountain = 12,
	snow = 11,
	night = 10,
	bay = 9,
	beach = 8,
	tidalflat = 7,
	rainbow = 5,
	thunderstorm = 4,
	mountainforests = 3
}
Const.FormId2Name = {
	"basic",
	"highland",
	"mountainforests",
	"thunderstorm",
	"rainbow",
	nil,
	"tidalflat",
	"beach",
	"bay",
	"night",
	"snow",
	"mountain",
	"flowersea",
	"forest",
	"grassland",
	"plateau",
	"cloud",
	"blackrainbow"
}
Const.MONSTER_TYPE = {
	ELITE = 2,
	NORMAL = 1
}
Const.PUPPET_LEVEL_TYPE = {
	STARLEVEL = 7,
	MAPAREA = 6,
	RANDOM = 3,
	TEAMPETSAVG = 4,
	PLAYER = 2,
	FIXED = 1,
	TEAMPETSMAX = 5
}
Const.PUPPET_MIN_LEVEL_FORMULAID = 4002
Const.CatchThrowTimeout = 20
Const.CatchResultTimeout = 7.5
Const.CatchBigBallResultTimeout = 15
Const.PARAM_DEFINE_LEN = 4
Const.PET_BOX_SORT = {
	RATING = 4,
	TIME = 0,
	NUMBER = 2,
	SCORE = 1,
	LEVEL = 3,
	COMPACT = 6,
	FAMILY = 5
}
Const.SERVER_VISIBLE_KEY = {
	Skill = 4,
	Rob_Egg_Settlement = 3,
	Level = 2,
	Spawn = 1,
	Default = 0,
	Gm_Observe = 6,
	ControlEgg = 5
}
Const.LOD_TICK_KEY = {
	GAME_PLAY = 4,
	VIRTUAL_ENT = 3,
	DIALOGUE_GRAPH = 2,
	BOSS_COMBAT = 1,
	DEFAULT = 0,
	TEAMMATEVIEW = 5
}
Const.PET_RESEARCH = {
	KEY_EVOLVE_NORMAL_CONDITION = 8,
	KEY_EVOLVE = 7,
	KEY_TRAIT = 6,
	KEY_BODY_ENTRY = 5,
	KEY_BATTLE_SKILL = 4,
	KEY_AVATAR_FEMALE = 3,
	KEY_AVATAR_MALE = 2,
	KEY_AVATAR_NONE = 1,
	REWARD_TYPE_SLOT = 2,
	REWARD_TYPE_DROP = 1,
	BI_SOURCE_TARGET = 3,
	STATUS_SHOW = 2,
	STATUS_CLUE = 1,
	STATUS_HIDE = 0,
	NORMAL_DOWNLOAD_BIG = 3,
	NORMAL_DOWNLOAD_SMALL = 2,
	NORMAL_DOWNLOAD_DIRECT = 1,
	STATUS_DONE = 2,
	STATUS_COUNTING = 1,
	STATUS_INIT = 0,
	BI_SOURCE_TRAIT = 2,
	BI_SOURCE_AVATAR = 1,
	COMP_TARGET_IDX_ITEM_REWARD = 4,
	COMP_TARGET_IDX_REWARD = 3,
	KEY_MAX = 10,
	KEY_POINTS = 10,
	KEY_EVOLVE_ITEM_CONDITION = 9,
	REPR_STATUS = {
		[0] = "0-init",
		"1-counting",
		"2-done"
	},
	REPR_STATUS_EX = {
		[0] = "0-hide",
		"1-clue",
		"2-show"
	},
	REPR_KEY = {
		"1-avatarNone",
		"2-avatarMale",
		"3-avatarFemale",
		"4-battleSkill",
		"5-bodyEntry",
		"6-trait",
		"7-evolve",
		"8-evolveNormalCondition",
		"9-evolveItemCondition",
		"10-points"
	}
}
Const.DUNGEON_REWARD = {
	MULTIBOSS = 5,
	ACTIVE = 4,
	CHALLENGE = 3,
	WEEK = 2,
	DAILY = 1
}
Const.MULTIBOSS_REWARD = {
	FIRST_NORMAL = 0,
	RARE = 2,
	HELP = 3,
	NORMAL = 1
}
Const.ActivityType = {
	BOSS_DUNGEON = 1
}
Const.PRM_PROPERTY = 1
Const.PRM_RESULTKEY = 2
Const.PRM_TARGETCNT = 3
Const.PET_RESEARCHKEY_MAP = {
	[Const.PET_RESEARCH.KEY_AVATAR_NONE] = {
		"avatarNoneResearch",
		"avatar"
	},
	[Const.PET_RESEARCH.KEY_AVATAR_MALE] = {
		"avatarMaleResearch",
		"avatar"
	},
	[Const.PET_RESEARCH.KEY_AVATAR_FEMALE] = {
		"avatarFemaleResearch",
		"avatar"
	},
	[Const.PET_RESEARCH.KEY_BATTLE_SKILL] = {
		"battleResearch",
		"battleSkill"
	},
	[Const.PET_RESEARCH.KEY_BODY_ENTRY] = {
		"bodyEntryResearch"
	},
	[Const.PET_RESEARCH.KEY_TRAIT] = {
		"traitResearchMap"
	},
	[Const.PET_RESEARCH.KEY_EVOLVE] = {
		"evolveResearchMap"
	},
	[Const.PET_RESEARCH.KEY_POINTS] = {
		"researchPointMap"
	}
}
Const.PET_RESEARCH_DUMP_LABEL_KEY_MAP = {
	[Const.PET_RESEARCH.KEY_AVATAR_NONE] = true,
	[Const.PET_RESEARCH.KEY_AVATAR_MALE] = true,
	[Const.PET_RESEARCH.KEY_AVATAR_FEMALE] = true
}
Const.PET_RESEARCH_CLIENT_FIELD_MAP = {
	[Const.PET_RESEARCH.KEY_AVATAR_NONE] = "avatarNoneResearch",
	[Const.PET_RESEARCH.KEY_AVATAR_MALE] = "avatarMaleResearch",
	[Const.PET_RESEARCH.KEY_AVATAR_FEMALE] = "avatarFemaleResearch",
	[Const.PET_RESEARCH.KEY_BATTLE_SKILL] = "battleResearch",
	[Const.PET_RESEARCH.KEY_TRAIT] = "traitResearchMap",
	[Const.PET_RESEARCH.KEY_EVOLVE] = "evolveResearchMap",
	[Const.PET_RESEARCH.KEY_BODY_ENTRY] = "bodyEntryResearch",
	[Const.PET_RESEARCH.KEY_POINTS] = "researchPointMap"
}
Const.PET_RESEARCH_CLIENT_EVOLVE_CONDITION_FIELD_MAP = {
	[Const.PET_RESEARCH.KEY_EVOLVE_NORMAL_CONDITION] = "normalConditionStatus",
	[Const.PET_RESEARCH.KEY_EVOLVE_ITEM_CONDITION] = "itemConditionStatus"
}
Const.PlAYER_ACTIVE = {
	ST_PLAYER_DEAD = 3,
	ST_IN_BATTLE = 2,
	ST_IN_TEAM = 1,
	ST_IN_DIALOGUEPRO = 5,
	ST_PLAYER_OFFLINE = 4
}
Const.FORBID_POSITION_REASON = {
	SOCIAL = 4,
	VEHICLE_DROP = 3,
	LEVEL_ITEM_INTERACT = 2,
	DIALOGUEGROUP = 1,
	DIALOGUEGRAPH = 0
}
Const.TEAM_STATUS = {
	S_IN_DUN = 6,
	S_ALLOCATE_DUN = 5,
	S_DUN_PREPARE = 4,
	S_APPLY_DUN_COMFIRM = 3,
	S_DESTROY = 2,
	S_NORMAL = 1
}
Const.TEAM_STATE = {
	S_IN_DUN = 8,
	S_ALLOCATE_DUN = 7,
	S_DUN_PREPARE = 2,
	S_NORMAL = 1,
	S_DISBANDING = 9,
	S_DUNGEON_CONFIRM = 6,
	S_DUNGEON_MATCH = 5,
	S_COMPOSE_MATCH = 4,
	S_DUN_CHECK = 3
}
Const.TEAM_BASE = {
	TICK_WAIT_ENTER_QUEUE_TIME = 1,
	DESTROY_DUNGEON_TIMEOUT = 30,
	MATCH_CONFIRM_RESPONSE_TIME = 2,
	MATCH_STATE_RECOVER_RETRY_COUNT = 3,
	MATCH_STATE_RECOVER_RETRY_INTERVAL = 1,
	START_MATCH_TEAM_CHECK_TIMEOUT = 2,
	MAX_INFO_NUM = 10,
	MAX_PLAYER_NUM = 4,
	MAX_WAIT_ENTER_DUN_CONFIRM_TIME = 30,
	TEAM_ALLOCATE_DUN_TIMEOUT = 10,
	MATCH_READY_CONFIRM_TIMEOUT = 30,
	MAX_WAIT_ENTER_QUEUE_TIME = 10
}
Const.TEAM_MATCH_STATUS = {
	IDLE = 0,
	MATCHED = 2,
	MATCHING = 1
}
Const.PLAYER_MATCH_STATUS = {
	MATCH_TEAM = 1,
	IDLE = 0,
	MATCHED = 3,
	MATCH_DUNGEON = 2
}
Const.DUNGEON_MATCH_STAGE = {
	IDLE = 0,
	MATCH_ROB_EGG = 1,
	AGREE_ENTER = 2
}
Const.TEAM_OPERATE_TYPE = {
	CHANGE_TEAM_INFO = 1,
	TRY_START_MATCH = 2
}
Const.TEAM_DUNGEON_CONFIRM = {
	NONE = 0,
	AGREE = 2,
	REFUSE = 1
}
Const.TEAM_CONTEXT_OPT_TYPE = {
	OPT_CONFIRM_DUNGEON = 1
}
Const.MATCH_CONFIG_TYPE = {
	TEAM = 1,
	DUNGEON = 2
}
Const.TEAM_TYPE = {
	DUNGEON = 2,
	NORMAL = 1
}
Const.ENTER_DUNGEON_TYPE = {
	MATCH_TEAM = 1,
	DIRECTLY_ENTER = 3,
	MATCH_DUNGEON = 2
}
Const.CUR_DUNGEON_TYPE = {
	BOSSRush = 2,
	Egg = 3,
	Dungeon = 1,
	Weekly = 4
}
Const.DUNGEON_CHANGE_STATUS = {
	WaitChange = 1,
	PASS = 0,
	Error = 2
}
Const.CHAT_TYPE = {
	GROUP = "GROUP",
	PRIVATE = "PRIVATE",
	INTERACTION = "INTERACTION",
	MULTICAST = "MULTICAST",
	FRIEND = "FRIEND",
	NEARBY = "NEARBY",
	WORLD = "WORLD",
	CLUSTER = "CLUSTER"
}
Const.CHAT_EXTRA_TYPE = {
	IsFriend = "isFriend",
	Pet = "pet",
	Emoji = "emoji",
	TeamInvite = "teamInvite",
	Reply = "reply",
	ChatType = "chatType",
	FriendCard = "friendCard",
	Language = "language",
	Item = "item",
	HomeCampInvite = "homeCampInvite",
	PositionCard = "positionCard",
	PhotographyStudioInvite = "photographyStudioInvite",
	Picture = "picture",
	HomeSeasonMutationGift = "homeSeasonMutationGift",
	Voice = "voice",
	HomeSeasonCelebrationInvite = "homeSeasonCelebrationInvite"
}
Const.NOT_INTIMACY_CHAT_EXTRA_TYPE = {
	Const.CHAT_EXTRA_TYPE.PhotographyStudioInvite,
	Const.CHAT_EXTRA_TYPE.HomeSeasonMutationGift,
	Const.CHAT_EXTRA_TYPE.HomeSeasonCelebrationInvite
}
Const.CHAT_LIKE_SOURCE_TYPE = {
	Picture = 1,
	Pet = 2
}
Const.SPARK_SOURCE = {
	EXCHANGE_PET = 4,
	SEND_GIFT = 3,
	VISIT_HOMELAND = 5,
	TEAM = 2,
	CHAT = 1
}
Const.SPARK_INTERACTION_STATE = {
	BITS_PER_SOURCE = 2,
	BOTH = 3,
	OTHER = 2,
	SELF = 1,
	SELF_BITS_MASK = 341
}
Const.CHAT_MESSAGE_TYPE = {
	Self = 1,
	System = 2
}
Const.CHAT = {
	CHAT_BLACK_LIST_GROUP_ID = -1,
	CHAT_DEFAULT_LIST_GROUP_ID = 0,
	CHAT_POSITION_CARD_DISTANCE = 5,
	CHAT_POSITION_CARD_TIMEOUT = 60,
	NEARBY_RADIUS = 80,
	CHAT_GROUP_MAX_MEMBER_COUNT = 30,
	CHAT_CHAT_GROUP_MAX_NUMBER = 5,
	CHAT_GROUP_MAX_NUMBER = 6
}
Const.CHAT_CHANNEL_TYPE = {
	LANGUAGE = "LANGUAGE",
	WORLD = "WORLD",
	CLASS = "CLASS"
}
Const.CHAT_ATTR_WORLD = {
	group_base = "world_chat",
	group_capacity = 9999
}
Const.CHAT_ATTR_CLASS = {
	group_base = "class_chat",
	group_capacity = 9999
}
Const.CHAT_ATTR_LANGUAGE = {
	group_base = "language_chat",
	group_capacity = 9999
}
Const.TEXT_CHECK_TYPE = {
	PERMANENT = "permanent",
	EXAMINE = "examine",
	INSTANT = "instant",
	REPORT = "report"
}
Const.ACCUSATION_TYPE = {
	PLAYER_NAME = 5,
	PLAYER_HOMECAMP = 11,
	PLAYER_HOME_NAME = 10,
	PLAYER_HOMELAND = 9,
	PLAYER_TITLE = 8,
	PLAYER_SIGNATURE = 7
}
Const.ACCUSATION_TYPE_MAX_COUNT = 11
Const.RISK_LEVEL = {
	SHIELD = "SHIELD",
	PASS = "PASS",
	MUTE = "MUTE"
}
Const.MAIL = {
	MAIL_CAPACITY = 200,
	PAGE_LIMIT = 0,
	PARAMS = {
		LANGUAGE = "mailLanguage",
		BANNER_FRAME = "bannerFrame"
	}
}
Const.MAIL_ID = {
	SHOPMALL_BUY_BPCARD_BACK = 41,
	MONTHCARD_EXPIRE_STOREWARD_MAIL = 39,
	HOMELAND_ZONE_MAIL = 17,
	OPR_ACTIVITY_PET_RESEARCH_REWARD = 15,
	LEYLINE_TREE_REWARD = 14,
	ACTIVITY_MAIL = 11,
	FRIEND_GIFT = 12,
	SHOPMALL_BUY_MONTHCARD_BACK = 42,
	REPORT_NICKNAME_VIOLATION = 50,
	REPORT_AVATAR_VIOLATION = 49,
	CAMP_DISSOLVE_PRIVATE = 44,
	FOLLOW_REWARD = 45,
	BADGE_MEDAL_OVERFLOW_COMPENSATE = 46,
	REPORT_SUCCESS = 47,
	REPORT_FAIL = 48,
	ROB_EGG_HATCH_SUCCESS = 18,
	ROB_EGG_TRANSFER_SUCCESS = 18,
	REPORT_CHAT_VIOLATION = 51,
	REPORT_CHAT_VIOLATION_EU = 52,
	FISHING_CAPTURE_OFFLINE_COMPENSATE = 53,
	FISHING_CAPTURE_OFFLINE_ENEGY = 60,
	ACTIVITY_BIND_AWARD = 86,
	ROB_EGG_HANGUP_PUNISH = 87,
	CAPTURE_ABNORMAL_RECYCLE_NOTICE = 92,
	FOLLOW_REWARD_LIMIT_MAIL_ID = 134,
	REPORT_TITLE_VIOLATION = 97,
	REPORT_SIGNATURE_VIOLATION = 81,
	LEYLINE_FLOWER_REWARD = 38,
	SHOPMALL_GIVE_MAIL = 36,
	ROB_EGG_ITEM_BACK_TO_OWNER = 35,
	ROB_EGG_ITEM_ALLBACK = 33,
	ROB_EGG_ITEM_BACK_TO_MATES = 32,
	EXCHANGE_GITFCODE = 31,
	ROB_EGG_SUPER_TRANSFER_SUCCESS = 28,
	PLANT_GIVE = 27,
	BADGE_COLLECTION_REWARD = 26,
	ACT_ARK_CARN = 25,
	ACT_AREA_ACT = 24,
	ACT_WEEKPARAY_REWARD = 22,
	ECO_TRACE_REWARD = 21,
	ENERGYMATCH_AWARD = 20,
	ROB_EGG_HELP_HATCH = 19
}
Const.Friend = {
	TID_MS_FRIEND_ACCEPT_FRIEND_FULL_OTHER = "TID_MS_FRIEND_ACCEPT_FRIEND_FULL_OTHER",
	TID_MS_FRIEND_ACCEPT_FRIEND_FULL_SELF = "TID_MS_FRIEND_ACCEPT_FRIEND_FULL_SELF",
	GROUP_NAME_MAX_LENGTH = 7,
	REMARK_MAX_LENGTH = 7,
	RECENT_DUNGEON_PLAYMATE_MAX_COUNT = 100,
	RECOMMEND_KEEP_DAYS = 3,
	ACCEPT_ALL_CD = 3,
	RECOMMEND_SCORE_MAX_COUNT = 100,
	RECOMMEND_MAX_COUNT = 100,
	RECOMMEND_PAGE_LIMIT = 20,
	RECOMMEND_PLAYER_CD = 3,
	QUERY_PLAYER_CD = 3,
	PAGE_LIMIT = 0,
	TID_MS_FRIEND_APPLY_ALREADY_IN_APPLICATIONS = "TID_MS_FRIEND_APPLY_ALREADY_IN_APPLICATIONS",
	TID_MS_CHAT_SERVICE_CHATCONTENT_LENGTH = "TID_MS_CHAT_SERVICE_CHATCONTENT_LENGTH",
	TID_MS_FRIEND_APPLY_TOO_FREQUENTLY = "TID_MS_FRIEND_APPLY_TOO_FREQUENTLY",
	TID_MS_FRIEND_APPLY_COUNT_LIMIT = "TID_MS_FRIEND_APPLY_COUNT_LIMIT",
	TID_MS_FRIEND_APPLY_COOLDOWN = "TID_MS_FRIEND_APPLY_COOLDOWN",
	TID_MS_FRIEND_APPLY_FRIEND_FULL = "TID_MS_FRIEND_APPLY_FRIEND_FULL",
	RECENT_DUNGEON_PLAYMATE_KEEP_SECONDS = 7 * Const.SECONDS_ONE_DAY
}
Const.FriendIntimacyFuncType = {
	SendGift = 1,
	SendPet = 3,
	ExchangePet = 2
}
Const.PlayerActionState = {
	FuncMenu = 1,
	None = 0,
	AFK = 3,
	CommonPanel = 2
}
Const.FriendRecommendScoreType = {
	Gender = 1,
	Parking = 3,
	Team = 2
}
Const.FriendStatus = {
	Online = "Online",
	Offline = "Offline"
}
Const.FriendPermission = {
	AutoEnterWorld = 2,
	TeamNoInvite = 1,
	PlayerTakeUp = 3
}
Const.FriendPermissionSet = {
	[Const.FriendPermission.TeamNoInvite] = true,
	[Const.FriendPermission.AutoEnterWorld] = true,
	[Const.FriendPermission.PlayerTakeUp] = true
}
Const.FriendshipPermissionType = {
	SpecialFriend = 6,
	OnlineReminder = 5,
	EnterWorldAutoAccept = 4,
	TravelTogether = 2,
	Action = 1,
	FriendNamePrefix = 7,
	TeamAutoAccept = 8,
	ExchangePet = 3
}
Const.APPEARANCE_SIMPLE_TYPE = {
	DesignWork = 2,
	Action = 1,
	BackGround = 3
}
Const.APPEARANCE_ACTION_TYPE = {
	Double = 2,
	Single = 1,
	Appearance = 7,
	Vehicle = 6,
	Furniture = 5,
	Emotion = 4,
	Multi = 3
}
Const.SHOW_TITLE_TYPE = {
	Suffix = 2,
	Prefix = 1,
	None = 0,
	Background = 4,
	Whole = 3
}
Const.APPEARANCE_BACKGROUND_TYPE = {
	Pet = 2,
	None = 0,
	Player = 1
}
Const.SKILL_FUNCTYPE = {
	PetControl = 4,
	ATTRENTRY = 3,
	BUFF = 2,
	SKILL = 1
}
Const.BADGE_STATUS = {
	Complete = 3,
	Show = 2,
	Secret = 1,
	None = -1,
	Hide = 0
}
Const.SHOP_PLAYER_TYPE = {
	LEVEL_2 = 2,
	LEVLE_1 = 1,
	LEVEL_0 = 0,
	LEVEL_3 = 3
}
Const.SHOP_ID = {
	ROBEGG_SHOP = 49,
	JourneyOfLegends = 40
}
Const.JewelryInfoType = {
	SCALE = 3,
	ROT = 2,
	POS = 1,
	ALL = 4
}
Const.PET_BALL = {
	HATCH_STATUS_START = 1,
	HATCH_STATUS_INIT = 0,
	MUTATION_MASK_FLASH = 2,
	MUTATION_MASK_TALENT = 1,
	PRODUCTION_FETER = 6,
	PRODUCTION_EGG = 5,
	PRODUCTION_STRENGTH = 4,
	PRODUCTION_TALENT = 3,
	PRODUCTION_EXP_SUB = 2,
	PRODUCTION_EXP = 1,
	ACTION_BREED = 5,
	ACTION_EXERCISE = 4,
	ACTION_FEED = 3,
	ACTION_EXP_SUB = 2,
	ACTION_EXP = 1,
	TIME_TO_SECOND = 3600,
	EGG_ITEMID = 130900,
	PET_BREED_LIMIT = 100,
	BI_HATCH_GET = 3,
	BI_HATCH_QUIT = 2,
	BI_HATCH_START = 1,
	BI_FLOW_CANCEL_FEED = 3,
	BI_FLOW_FEED = 2,
	BI_FLOW_CHANGE_PET = 1,
	EXP_STATUS_PAUSE = 2,
	EXP_STATUS_START = 1,
	EXP_STATUS_INIT = 0,
	TEMP_SLOT_LOCKED = 2,
	TEMP_SLOT_OK = 1,
	HATCH_STATUS_SUCC = 3,
	HATCH_STATUS_PAUSE = 2
}
Const.PET_RELEASE_CONTENT_TYPE = {
	TALENT = 1,
	REWARD = 0,
	SKILL = 3,
	CHARACTER = 4,
	STRENGTHEN = 2
}
Const.PET_RELEASE_RESOURCE_TYPE = {
	ADD = 2,
	NONE = 0,
	SELF = 1
}
Const.PET_HUNGRY_STATE = {
	EatHungry = 3,
	Hungry = 2,
	FirstHungry = 1
}
Const.LEYLINE_PUPPET_EFFECT_TYPE = {
	Shiny = 1,
	Talent = 2
}
Const.ECO_TRACE_PROJECT = {
	Shiny = 3,
	Perfect = 2,
	Maturity = 1
}
Const.FUNCTION_UNLOCK_STATE = {
	SHIELDED = -1,
	UNLOCK = 1,
	LOCK = 0
}
Const.FUNCTION_IDS = {
	BOOSRUSH = 193,
	HOMELAND = 185,
	GRABEGGMODE = 192,
	SCHOOLGUIDE = 194,
	ACTIVITYCENTER = 189,
	SURVEY = 184,
	SPECIALTRAIN = 183,
	ALBUM = 181,
	ROGUE = 171,
	COURSE = 161,
	ANNOUNCEMENT = 14,
	UNKNOWN = 0,
	AVATAR = 152,
	APPEARANCE = 151,
	TIMETRAIN = 141,
	CONFIG = 131,
	CASHSHOP = 202,
	SHOP = 121,
	TAKEPHOTO = 101,
	MAP = 81,
	PETBALL = 61,
	QUEST = 51,
	BAG = 41,
	PETENTRY = 31,
	PLAYERENHANCEMENT = 21,
	VIP = 15,
	PVP = 71,
	PETRESEARCH = 11,
	SERVICE = 9,
	MAIL = 13,
	BATTLEPASS = 205,
	FISSURE = 207,
	FRIEND = 187,
	WORLD = 143,
	ARK = 142,
	FEEDBACK = 10002,
	MONTH_CARD_PREORDER = 601,
	HOME_BOOK = 197,
	SEASON = 211,
	HELP = 91,
	CHAT = 186
}
Const.FUNCTION_TYPE = {
	FUNC_MENU = 1,
	FUNC_COMMON = 2
}
Const.FUNCTION_NAME = {
	HOMELAND_PET = "HOMELAND_PET",
	HOMECAR_MANAGEMENT = "HOMECAR_MANAGEMENT",
	TAKEPHOTO = "TAKEPHOTO",
	MAP = "MAP",
	FRIEND = "FRIEND",
	PETEQUIPMENT = "PETEQUIPMENT",
	TEAM = "TEAM",
	CHAT = "CHAT"
}
Const.BILogName = {
	SURVEY = "survey",
	EVENT_COMMON_GUIDE = "event_guide",
	SCHOOL_GUIDE_BOSS = "school_guide_aniimo",
	EVENT_MOCK = "train",
	SCHOOL_GUIDE_MOCK = "school_guide_sim",
	EVENT_FRACTION = "group",
	SHOPPING_MALL_START_PAY = "shopping_mall_start_pay",
	CUTSCENE = "cutscene",
	SHOPPING_MALL_PRIME_STAY = "shopping_prime_stay",
	OPTION = "option",
	SHOPPING_MALL_SEC_STAY = "shopping_sec_stay",
	DIALOGUE = "dialogue",
	SHOPPING_MALL_MAIN_PAGE = "shopping_mall_main_page",
	SCHOOL_GUIDE_CRAFT = "school_guide_craft",
	SHOPPING_MALL_ITEM_DISPLAY = "shopping_mall_single_item_display",
	TEAM_SPEECH = "teamSpeech",
	PAYMENT_FAIL = "payment_fail",
	SETTING = "setting",
	AD_PAYMENT = "ad_payment",
	PHOTO_POINT = "photo_point",
	STUDIO_EDIT = "studio_edit",
	CREATE_ROLE_SUCCESS = "create_role_success",
	STUDIO_SHARE = "studio_share",
	EVENT_RACING_TEMPLE = "RacingTemple",
	STUDIO_CODE = "studio_code",
	FIND_ELITE_OR_BOSS = "find_elite_or_boss",
	DIALOGUE_GRAPH = "dialoguegraph",
	GUIDANCE_FLOW = "guidance_flow",
	EVENT_PROFILE_PAGE = "profilepage",
	EVENT_PLAYER_CARD = "socialfunction"
}
Const.AFLogName = {
	PAYMENT_START = "af_initiated_checkout"
}
Const.AFLogTaskIdMapName = {
	[3707063] = "af_tutorial_completion_ark",
	[2602113] = "af_tutorial_completion",
	[3502007] = "af_tutorial_completion_tree",
	[2602226] = "af_tutorial_completion_xy"
}
Const.FBLogTaskIdMapName = {
	[2602113] = "ad_tutorial_completion"
}
Const.AFLogRetentionName = {
	nil,
	"af_d1_retention",
	nil,
	"af_d3_retention",
	nil,
	nil,
	nil,
	"af_d7_retention",
	[31] = "af_d30_retention"
}
Const.FBLogRetentionName = {
	nil,
	"ad_d1_retention",
	nil,
	"ad_d3_retention",
	nil,
	nil,
	nil,
	"ad_d7_retention",
	[31] = "ad_d30_retention"
}
Const.AFLogReportOnceTable = {
	af_tutorial_completion_xy = 1,
	af_tutorial_completion_tree = 1,
	af_tutorial_completion_ark = 1,
	af_tutorial_completion = 1,
	af_success_nickname_set = 1,
	af_create_role = 1,
	af_capture_first_prismana_pet = 1,
	af_d30_retention = 1,
	af_d7_retention = 1,
	af_d3_retention = 1,
	af_d1_retention = 1,
	af_capture_first_shiny_pet = 1
}
Const.FbLogReportOnceTable = {
	ad_d3_retention = 1,
	ad_d7_retention = 1,
	ad_d30_retention = 1,
	ad_create_role = 1,
	ad_tutorial_completion = 1,
	ad_d1_retention = 1
}
Const.PKG_CHANNEL_TO_PLATFORM = {
	["Funplus-PC.Funplus-PC.Aik0jo"] = "playstation",
	["Funplus-PC.Funplus-PC.A3oj8a"] = "steam",
	["Funplus-PC.Funplus-PC.Aebr16"] = "xbox",
	["Funplus-PC.Funplus-PC.Apfozx"] = "nativepc",
	["Funplus-PC.Funplus-PC.Aw8jtt"] = "xbox",
	["Funplus-PC.Funplus-PC.A4l9qs"] = "epic",
	["Funplus-PC.Funplus-PC.A07n19"] = "steam"
}
Const.SOCIAL_MEDIA_TYPE = {
	DISCORD = "discord"
}
Const.SOCIAL_MEDIA_TYPE_SET = {
	[Const.SOCIAL_MEDIA_TYPE.DISCORD] = true
}
Const.RANK_ID_TYPE = {
	ROB_EGG_RANK_ID = "RobEggRank"
}
Const.DISCORD_GAME_STATS_HTTP_STATUS = {
	SERVER_ERROR_MAX = 599,
	SERVER_ERROR_MIN = 500,
	TOO_MANY_REQUESTS = 429,
	FORBIDDEN = 403,
	BAD_REQUEST = 400,
	NO_CONTENT = 204,
	CREATED = 201
}
Const.BILogCutsceneAction = {
	END = "end",
	START_SKIP = "startSkip",
	STRAT = "start",
	CONFIRM_SKIP = "confirmSkip"
}
Const.GUIDANCE_TYPE_ALL = 0
Const.GUIDANCE_TYPE_SYSTEM = 1
Const.GUIDANCE_TYPE_PROGRESSION = 2
Const.GUIDANCE_TYPE_COMBAT = 3
Const.GUIDANCE_TYPE_EXPLORE = 4
Const.GUIDANCE_TYPE_MAX = 5
Const.GUIDANCE_TYPE = {
	[Const.GUIDANCE_TYPE_ALL] = 0,
	[Const.GUIDANCE_TYPE_SYSTEM] = 1,
	[Const.GUIDANCE_TYPE_PROGRESSION] = 2,
	[Const.GUIDANCE_TYPE_COMBAT] = 3,
	[Const.GUIDANCE_TYPE_EXPLORE] = 4
}
Const.HELP_UNLOCK_LEVEL = {
	UNAPPEAR = 0,
	UNLOCK = 2,
	LOCK = 1
}
Const.RECHARGE_TYPE = {
	PAYTEST = 5,
	Other = 4,
	BP = 3,
	MONTHCAR = 2,
	RECHARGE = 1
}
Const.TOD_TIME_KEY = {
	ROGUE = "rogue",
	SERVER_TIME = "serverTime",
	DIALOGUE = "dialogue",
	DITTO = "ditto",
	PHOTO = "PHOTO"
}
Const.TOD_TIME_KEY_PRIORITY = {
	[Const.TOD_TIME_KEY.SERVER_TIME] = 100,
	[Const.TOD_TIME_KEY.DIALOGUE] = 200,
	[Const.TOD_TIME_KEY.ROGUE] = 300,
	[Const.TOD_TIME_KEY.PHOTO] = 400,
	[Const.TOD_TIME_KEY.DITTO] = 500
}
Const.CLIENT_SWITCH_REASON = {
	BotAI = 11,
	Horn = 10,
	Nourish = 9,
	ShopPoster = 8,
	Default = 0,
	Dialogue = 5,
	Dying = 3,
	Catch = 2,
	ManualSwitch = 1,
	FuncMenu = 4,
	Vehicle = 6,
	DialogueGraph = 7,
	NpcDuel = 12
}
Const.GUIDE_TYPE = {
	GT_SPECIFIC_HIGHLIGHT = 6,
	GT_POPUP_PANEL = 5,
	GT_FLOATING_AI = 4,
	GT_FLOATING_DRAG = 3,
	GT_FLOATING_AUTO = 2,
	GT_FOCUS = 1
}
Const.GUIDE_STEP_END = {
	GSC_INPUT_DRAG = 7,
	GSC_INPUT_TRIGGERED = 6,
	GSC_FINISH_COND = 5,
	GSC_OPEN_UI = 4,
	GSC_CLICK_BTN = 3,
	GSC_CLOSE_UI = 2,
	GSC_COUNT_DOWN = 1
}
Const.GUIDE_DIRECTION_TYPE = {
	GUIDE_PORINT_TYPE_CONTROL = 1,
	GUIDE_PORINT_TYPE_ITEM = 2
}
Const.GUIDE_STEP_FINISH_REASON = {
	CLOSE_UI = 5,
	OPEN_UI = 4,
	EVENT = 2,
	TIME_LIMIT = 1,
	TRIGGER_MEET = 3,
	CLICK_VIRTUAL_BTN = 8,
	CLICK_BTN = 7,
	ACTION_TRIGGERED = 6
}
Const.GUIDE_FINISH_REASON = {
	COND_CHECK_FAILED = "CondCheckFailed",
	SKIP = "Skip",
	FLOATING_COND_FAILED = "FloatingCondFailed",
	SUCESS = "Sucsee",
	FOCUS_TARGET_LOSE = "FocusTargetLose",
	SERVER_FINISH = "ServerFinish",
	SKIP_MANUAL = "SkipManual"
}
Const.EnvCreateType = {
	Client = 0,
	Server = 1
}
Const.GAME_PLAY_DEFAULT = 0
Const.GAME_PLAY_DITTO = 6
Const.GAME_PLAY_PET_CHALLENGE = 7
Const.GAME_PLAY_COMMON_CHALLENGE = 8
Const.GAME_PLAY_RACING_TEMPLE = 9
Const.GAME_PLAY_TARGET_COMMON_CHALLENGE = 10
Const.GAME_PLAY_RIFT = 11
Const.GAME_PLAY_TYPE_TO_ENT_NAME = {
	[Const.GAME_PLAY_DEFAULT] = "GamePlay",
	[Const.GAME_PLAY_DITTO] = "GamePlayDittoDungeon",
	[Const.GAME_PLAY_PET_CHALLENGE] = "GamePlayPetChallenge",
	[Const.GAME_PLAY_COMMON_CHALLENGE] = "GamePlayCommonChallenge",
	[Const.GAME_PLAY_RACING_TEMPLE] = "GamePlayRacingTemple",
	[Const.GAME_PLAY_TARGET_COMMON_CHALLENGE] = "GameTargetCommonChallenge",
	[Const.GAME_PLAY_RIFT] = "GamePlayRift"
}
Const.RIFT_SANDBOX_TYPE = {
	GUARD = 3,
	DEFEAT = 1,
	SURVIVE = 2
}
Const.GamePlay = {
	RESULT_FAILED = 2,
	RESULT_SUCCESS = 1,
	RESULT_UNKNOWN = 0,
	EXIT_MODE_KICK_OUT = 4,
	EXIT_MODE_QUIT_HALF_WAY = 3,
	EXIT_MODE_FAILED = 2,
	EXIT_MODE_NORMAL = 1,
	EXIT_MODE_UNKNOWN = 0,
	ST_CLOSED = 6,
	ST_REWARD = 5,
	ST_ING = 4,
	ST_PRE_COUNTING = 3,
	ST_PLAYER_READY = 2,
	ST_INIT = 1,
	ST_CREATING = 0,
	ClientInfoDef = {
		isRestart = {
			"boolean",
			false
		}
	},
	DisplayInfoDef = {
		uid = {
			"string",
			""
		},
		name = {
			"string",
			""
		},
		pets = {
			"table"
		}
	}
}
Const.RogueStage = {
	RogueStage_Battle = 2,
	RogueStage_Select = 1,
	RogueStage_Init = 0
}
Const.ROGUE_SKILL_EP_COST = 100
Const.RogueBuffQuality = {
	High = 1,
	Normal = 0,
	Boss = 3,
	Equipment = 2
}
Const.ServerSetRigidBodyKey = {
	MechanismBallFeature = 1,
	Default = 4,
	Level = 3,
	WaitLift = 2
}
Const.RigidBodyState = {
	NoneKinematic = 2,
	None = 0,
	Kinematic = 1
}
Const.EmptyMap = {
	_ = ""
}
Const.EmptyList = {}

function Const.EMPTY_ERROR_FUNC()
	error("Cannot modify a cached empty table")
end

Const.CACHED_EMPTY_TABLE = setmetatable({}, {
	__index = {},
	__newindex = Const.EMPTY_ERROR_FUNC
})
Const.EmptyString = ""
Const.LimitType2TextKeyMap = {
	[Const.LIMIT_DAY] = "THIS_DAY",
	[Const.LIMIT_WEEK] = "THIS_WEEK",
	[Const.LIMIT_MONTH] = "THIS_MONTH"
}
Const.CustomGraphVariable = {
	SET = 1,
	ADD = 2,
	DIV = 5,
	MUL = 4,
	SUB = 3
}
Const.CustomVariableOpt = {
	MOD = 5,
	ADD = 1,
	DIV = 4,
	MUL = 3,
	SUB = 2
}
Const.NpcBehaviorOpt = {
	ADD = 1,
	REMOVE = 0
}
Const.DoTweenEaseType = {
	InOutQuad = 7,
	OutQuad = 6,
	InQuad = 5,
	InOutSine = 4,
	OutSine = 3,
	InSine = 2,
	Linear = 1,
	Unset = 0,
	INTERNAL_Custom = 37,
	INTERNAL_Zero = 36,
	InOutFlash = 35,
	OutFlash = 34,
	InFlash = 33,
	Flash = 32,
	InOutBounce = 31,
	OutBounce = 30,
	InBounce = 29,
	InOutBack = 28,
	OutBack = 27,
	InBack = 26,
	InOutElastic = 25,
	OutElastic = 24,
	InElastic = 23,
	InOutCirc = 22,
	OutCirc = 21,
	InCirc = 20,
	InOutExpo = 19,
	OutExpo = 18,
	InExpo = 17,
	InOutQuint = 16,
	OutQuint = 15,
	InQuint = 14,
	InOutQuart = 13,
	OutQuart = 12,
	InQuart = 11,
	InOutCubic = 10,
	OutCubic = 9,
	InCubic = 8
}
Const.VideoType = {
	PV = 1,
	BlackTransition = 3,
	NormalVideo = 2
}
Const.TimePeriod = {
	Morning = 1,
	Night = 4,
	Dusk = 3,
	Day = 2
}
Const.LiftReason = {
	Dead = 4,
	Default = 0,
	LeaveSpace = 3,
	LoseControl = 2,
	PlantSeed = 1
}
Const.TreeState = {
	NoPlant = 1,
	Normal = 0,
	InValid = -1
}
Const.TreeDropType = {
	Single = 1,
	Index = 2,
	All = 0
}
Const.NurseryState = {
	Plant = 1,
	NoPlant = 0
}
Const.TotemPuzzleState = {
	Triggering = 2,
	Enable = 1,
	Disable = 0,
	Finish = 4,
	Triggered = 3
}
Const.SpurtItemState = {
	Default = 0,
	Disable = 1
}
Const.RefChestPuzzleState = {
	Default = 0,
	Finish = 1,
	WaitPickChest = 2
}
Const.StunMushroomState = {
	Triggered = 1,
	Normal = 0
}
Const.PetExchangeItemState = {
	Ready = 0,
	Borrowed = 1
}
Const.ZoomingState = {
	ZoomingOut = 2,
	None = 0,
	ZoomingIn = 1
}
Const.SkillNameShowType = {
	Virtual = 2,
	Explore = 1,
	NormalAttack = 0,
	Normal = 3,
	ChainAttack = 5,
	FinalSkill = 4
}
Const.PetActionMode = {
	Peace = 1,
	Invade = 2,
	Catch = 0
}
Const.PVPMode = {
	UnFair = 2,
	Fair = 1
}
Const.PvpProcess = {
	Ready = 1,
	Reward = 2
}
Const.SpaceSupportPetMode = {
	AdditiveSummon = 1,
	None = 0,
	RealControl = 2
}
Const.SpaceBattleMode = {
	TwoPlusTwo = 2,
	Normal = 0,
	OnePlusThree = 1
}
Const.SkillType = {
	Skill = 3,
	Explore = 1,
	Virtual = 2,
	Chain = 5,
	Normal = 0,
	Ultimate = 4
}
Const.ChestType = {
	WhoOpenAndWhoGet = 3,
	EveryoneOpenAndOwnerGet = 2,
	DungeonChest = 1,
	OwnerOpenAndOwnerGet = 0,
	ArkChest = 4,
	HomeSeasonCelebration = 11,
	HomeTillGift = 10,
	SpaceFollowShare = 9,
	DistanceAllGet = 8,
	EmptyAction = 7,
	AllOpenAndAllGet = 6,
	HomeGift = 5
}
Const.HomeSeasonCelebrationEventType = {
	WaveExpired = 5,
	WaveExpireWarning = 4,
	WaveSpawned = 3,
	LastWavePreview = 2,
	WavePreview = 1
}
Const.ChestVisibleType = {
	Owner = 1,
	All = 0
}
Const.RewardAttractMode = {
	EnableDelayShow = 2,
	EnableNoDelay = 1,
	Disabled = 0
}
Const.CollectItemType = {
	WhoOpenAndWhoGet = 0,
	SpaceFollowShare = 1
}
Const.CollectItemVisibleType = {
	Owner = 1,
	All = 0
}
Const.TimeTravel = {
	Past = 1,
	Now = 0
}
Const.Retrospect = {
	Past = 1,
	Now = 0
}
Const.VehicleAccessType = {
	PUBLIC = 2,
	PRIVATE = 1
}
Const.VehicleState = {
	UNLOCKED = 1,
	LOCKED = 0,
	OWNED = 2
}
Const.ModelPartId = {
	Spine = 1,
	Unknown = -1,
	Head = 0,
	Tail = 4,
	Foot = 3,
	Hand = 2
}
Const.TravelState = "HelmonBoxValue"
Const.MAP_CONST = {
	TYPE = {
		NONE = 99,
		DYNAMIC = 66,
		GRAB_EGG = 19,
		DUEL = 18,
		GOLD = 17,
		FAST_TARGET = 16,
		ECO_TRACE = 15,
		MARK_SHARE = 14,
		LEYLINE_TREE_CREATE = 13,
		TYPE_12 = 12,
		TYPE_11 = 11,
		DISTRIBUTION_AREA = 10,
		ALLY = 8,
		CUSTOM = 7,
		AREA = 6,
		SINGLE_PUPPET = 1,
		NPC = 4,
		QUEST = 5,
		NORMAL = 0,
		BOSS = 2
	}
}
Const.MediaMarkerType = {
	_MinTextNum = 0,
	_MaxTextNum = 3,
	NormalText = 2,
	SystemText = 1
}
Const.SHAPE_TYPE = {
	CUSTOM = 2,
	BOX = 1,
	CAPSULE = 0
}
Const.PET_TALENT = {
	GROUP_IDX_POOLID = 1,
	EXTRACT_NORMAL = 0,
	GROUP_IDX_MAX = 4,
	GROUP_IDX_LIMIT_NUM = 4,
	GROUP_IDX_WEIGHT = 3,
	GROUP_IDX_EXTRACT_WAY = 2
}
Const.BATTLE_REPORT_REASON = {
	COMBAT_MODE_CHANGE = 1,
	PET_TEAM_BAT_CHANGE = 0,
	PET_TEAM_DISC_CHANGE = 7,
	EXIT_DUNGEON = 6,
	ENTER_DUNGEON = 5,
	BATTLE_CATCH = 4,
	BEAT = 3,
	ENTER_COMBAT = 2
}
Const.DESTROY_REASON = {
	CAPTURE_SUCCESS = 1,
	INTERACT_FINISH = 4,
	SEAMLESS_CROSS = 11,
	RESET = 6,
	HOMEPET_REFRESH = 5,
	NONE = 0,
	PET_CHALLENGE = 3,
	CAPTURE_FAIL = 2
}
Const.SPECIAL_TRAIN = {
	QUEST_REWARD = 1,
	RECOMMEND_LIST_MAX_NUM = 3,
	CHAPTER_REWARD = 4,
	FINAL_REWARD = 3,
	BADGE_REWARD = 2
}
Const.SPECIAL_TRAIN_LOGNAME = {
	"special_train_mission_award",
	"special_train_stage_award",
	"special_train_final_award",
	"special_train_chapter_award"
}
Const.InterpolateFunc = {
	EaseOut = 2,
	EaseIn = 1,
	Linear = 0,
	EaseInOut = 3
}
Const.ClientPerformancePlatform = {
	Mobile = 2,
	PC = 1
}
Const.ClientPerformanceLevel = {
	High = 3,
	Normal = 2,
	Low = 1,
	Super = 4
}
Const.ClientPerformanceLevelDefault = 2
Const.ClientPerformanceLevelThreshold = {
	30,
	40,
	60,
	1000
}
Const.ClientPerformanceLevelLowScoreLimit = 27
Const.ClientPerformanceLevelScoreForbidden = 23
Const.ENTITY_DISTANCE_TICKINTERVAL = {
	[Const.ACTOR_TYPE_ENVOBJ] = {
		{
			70,
			50,
			30,
			0
		},
		{
			1,
			0.5,
			0.3,
			0.2
		}
	},
	[Const.ACTOR_TYPE_PUPPET] = {
		{
			70,
			50,
			30,
			0
		},
		{
			1,
			0.5,
			0.3,
			0.2
		}
	}
}
Const.ENTITY_DISTANCE_TICKINTERVAL_DEFAULT = {
	{
		70,
		50,
		30,
		0
	},
	{
		1,
		0.5,
		0.3,
		0.2
	}
}
Const.SCENE_POINT_ENTITY_TYPE = {
	PLAYER = 1,
	ENVOBJ = 16,
	VIRTUAL = 8,
	PUPPET = 4,
	PET = 2
}
Const.AREA_LAYER = {
	SANDBOX_PLAYER = 1,
	SANDBOX_ENVOBJ = 5,
	MAX = 7,
	RENDER_VOLUME = 6,
	DEFAULT = 0,
	SANDBOX_VIRTUAL = 4,
	SANDBOX_PUPPET = 3,
	SANDBOX_PET = 2
}
Const.AREA_LOAD_TYPE = {
	SCENE_LOAD = 1,
	PHASE_LOAD = 2,
	MAPPING_REGION = 3,
	NORMAL = 0
}
Const.ENTITY_TYPE_2_AREA_LAYER = {
	[Const.SCENE_POINT_ENTITY_TYPE.PLAYER] = Const.AREA_LAYER.SANDBOX_PLAYER,
	[Const.SCENE_POINT_ENTITY_TYPE.PET] = Const.AREA_LAYER.SANDBOX_PET,
	[Const.SCENE_POINT_ENTITY_TYPE.PUPPET] = Const.AREA_LAYER.SANDBOX_PUPPET,
	[Const.SCENE_POINT_ENTITY_TYPE.VIRTUAL] = Const.AREA_LAYER.SANDBOX_VIRTUAL,
	[Const.SCENE_POINT_ENTITY_TYPE.ENVOBJ] = Const.AREA_LAYER.SANDBOX_ENVOBJ
}
Const.CLIENT_KEY = {
	CLIENT_CACHE_META = 34,
	FRIEND_FUNC_AUTO_CONSENT = 33,
	PHOTO_ASSET_RED_DOT = 32,
	PHOTOGRAPHY_STUDIO_RED_DOT = 31,
	CHAT_BUBBLE_RED_DOT = 30,
	PET_WATER = 29,
	HOME_BOOK_RED_DOT = 28,
	HOME_ORDER_RED_DOT = 27,
	EVENT_VITALITY_JOIN_RED_DOT = 26,
	PET_DISPATCH_EVENT_TABLE = 25,
	PET_DISPATCH_MAPBLOCK = 24,
	PET_RECORD_APPLIED_RECOMMEND = 23,
	PET_TAG_ANIM_RECORD = 12,
	PET_EVOLVE_RED_DOT = 11,
	PET_NEW_RED_DOT = 10,
	PET_RESEARCH_RED_DOT = 9,
	PLAYER_ENHANCE_RED_DOT = 8,
	APPEARANCE_PET_RED_DOT = 7,
	APPEARANCE_RED_DOT = 6,
	MAP = 1,
	PLAYER_CARD_BACKGROUND_RED_DOT = 15,
	ROGUE = 4,
	EVENT_RED_DOT = 17,
	BOSS_RUSH = 19,
	GRAB_EGG_MODE = 20,
	PET_CULTIVATE_FREE_FIRST_RESET_PPOINT = 22,
	AVATAR_ICON_RED_DOT = 14,
	SMALL_AREA_FIRST_IN = 3,
	PLAYER_SHOW_TITLES_RED_DOT = 16,
	CHAT_RED_DOT = 13,
	DYNAMIC_MARK_INFO = 21,
	HOMELAND_FURNITURE_RED_DOT = 40,
	FRIEND = 5,
	SETTING = 2,
	DIALOGUE_GRAPH = 18,
	HOME_CAR_UPGRADE = 39,
	HOME_SEASON_PREPARE_ANIM_RECORD = 38,
	HOMELAND_MUSIC_PLAYER_RED_DOT = 37,
	HOMELAND_PET_MANAGE_RED_DOT = 36,
	QUEST_COURSE_RED_DOT = 35
}
Const.CLINET_KEY_STR = {
	DYNAMIC_MARK_INFO = "dynamic_mark_info",
	PET_RECORD_APPLIED_RECOMMEND = "recordAppliedRecommend"
}
Const.CLIENT_DEF_RED_DOT = {
	red_dot_record = {
		"table",
		{}
	}
}
Const.CLIENT_DEF = {
	[Const.CLIENT_KEY.MAP] = {
		sceneLastFloor = {
			"table",
			{}
		},
		mapLayerData = {
			"table",
			{}
		},
		mapLayerUnlockData = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.SETTING] = {
		common = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.SMALL_AREA_FIRST_IN] = {
		first_in = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.ROGUE] = {
		pet_team = {
			"table",
			{}
		},
		talent = {
			"number",
			0
		},
		red_dot_record = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.FRIEND] = {
		friendship_pop = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.APPEARANCE_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.APPEARANCE_PET_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PLAYER_ENHANCE_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PET_RESEARCH_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PET_NEW_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PET_EVOLVE_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PET_TAG_ANIM_RECORD] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.CHAT_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.AVATAR_ICON_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.CHAT_BUBBLE_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PHOTOGRAPHY_STUDIO_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PHOTO_ASSET_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.QUEST_COURSE_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.HOMELAND_PET_MANAGE_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.HOMELAND_FURNITURE_RED_DOT] = {
		read_snapshot = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.HOMELAND_MUSIC_PLAYER_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.HOME_SEASON_PREPARE_ANIM_RECORD] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PLAYER_CARD_BACKGROUND_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PLAYER_SHOW_TITLES_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.EVENT_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.BOSS_RUSH] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.DIALOGUE_GRAPH] = {
		playSpeed = {
			"number",
			1
		},
		autoPlay = {
			"boolean",
			false
		}
	},
	[Const.CLIENT_KEY.GRAB_EGG_MODE] = {
		red_dot_record = {
			"table",
			{}
		},
		calcination_read_snapshot = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.DYNAMIC_MARK_INFO] = {
		[Const.CLINET_KEY_STR.DYNAMIC_MARK_INFO] = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.PET_CULTIVATE_FREE_FIRST_RESET_PPOINT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PET_RECORD_APPLIED_RECOMMEND] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PET_DISPATCH_MAPBLOCK] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.PET_DISPATCH_EVENT_TABLE] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.EVENT_VITALITY_JOIN_RED_DOT] = Const.CLIENT_DEF_RED_DOT,
	[Const.CLIENT_KEY.HOME_ORDER_RED_DOT] = {
		read_snapshot = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.HOME_BOOK_RED_DOT] = {
		unread_snapshot = {
			"table",
			{}
		},
		snapshot_version = {
			"number",
			0
		}
	},
	[Const.CLIENT_KEY.PET_WATER] = {
		pet_water = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.FRIEND_FUNC_AUTO_CONSENT] = {
		settings = {
			"table",
			{}
		}
	},
	[Const.CLIENT_KEY.HOME_CAR_UPGRADE] = {
		pending_result_level = {
			"number",
			0
		},
		pending_ai_notice_level = {
			"number",
			0
		}
	},
	[Const.CLIENT_KEY.CLIENT_CACHE_META] = {
		versions = {
			"table",
			{}
		}
	}
}
Const.CLIENT_CACHE_PHYSICAL_KEY = "client_info_bin"
Const.DROP_REWARD = {
	TYPE_DAMAGE_THRESHOLD = 6,
	TYPE_FINAL_HIT = 5,
	TYPE_MAX_DAMAGE = 4,
	TYPE_HATE_LIST = 3,
	TYPE_FIRST_HIT = 2,
	TYPE_OWNER = 1,
	EXTEND_FAMILY = 2,
	EXTEND_TEAM = 1
}
Const.HOMELAND_BGM_ITEM_ID_SCENE_DEFAULT = 0
Const.HOMELAND_AREA_TYPE = {
	MINE = 5,
	LAKE = 4,
	BUILD = 1,
	PRODUCE = 0,
	SEASON = 2,
	PUBLIC = 3
}
Const.HOME_PET_BOX_SUPPORTED_AREA_SET = {
	[Const.HOMELAND_AREA_TYPE.PRODUCE] = true,
	[Const.HOMELAND_AREA_TYPE.BUILD] = true
}
Const.HOMELAND_ORNAMENT_OP_TYPE = {
	ADD = 1,
	REMOVE = 2,
	UPDATE = 3
}
Const.HOMELAND_ORNAMENT_OP_RETURN_CODE = {
	ERROR_ORNAMENT_CANT_UPGRADE = 12,
	ERROR_MONEY_NOT_ENOUGH = 11,
	ERROR_MONEY_NOT_VALID = 10,
	ERROR_ITEM_NOT_ENOUGH = 9,
	ERROR_NOT_TRASH = 8,
	ERROR_NOT_EDITABLE = 7,
	ERROR_ORNAMENT_COUNT_MAX = 6,
	ERROR_ITEM_NOT_VALID = 5,
	ERROR_ORNAMENT_NOT_EXIST = 4,
	ERROR_PARAM = 3,
	ERROR_NOT_HOME = 2,
	ERROR_CHECK_FAIL = 1,
	SUCCESS = 0,
	ERROR_AREA_LOAD_LIMIT = 18,
	ERROR_HOMECAR_ORNAMENT_COUNT_MAX = 17,
	ERROR_NOT_FIND_CAR = 16,
	ERROR_NOT_HOME_CAR = 15,
	ERROR_ORNAMENT_BUY_BAG_FULL = 14,
	ERROR_ORNAMENT_BUY_COUNT_MAX = 13
}
Const.HOME_BLUEPRINT_OP_RETURN_CODE = {
	ERROR_LIMIT_REACHED = 3,
	ERROR_ORNAMENT_COUNT_MAX = 9,
	SUCCESS = 0,
	ERROR_ITEM_NOT_ENOUGH = 8,
	ERROR_SERVICE = 11,
	ERROR_NOT_EDITABLE = 6,
	ERROR_EXTERNAL_LINK = 7,
	ERROR_CODE_INVALID = 4,
	ERROR_ORNAMENT_NOT_EXIST = 5,
	ERROR_PARAM = 1,
	ERROR_NOT_HOME = 2,
	ERROR_SYSTEM_BLUEPRINT_INVALID = 10,
	ERROR_TEXT_SENSITIVE = 12,
	ERROR_AREA_LOAD_LIMIT = 13,
	ERROR_SELF_BULEPRINT = 14
}
Const.HOMELAND_PET_OP_RETURN_CODE = {
	ERROR_PET_NOT_EXIST = 4,
	SUCCESS = 0,
	ERROR_PARAM = 3,
	ERROR_NOT_HOME = 2,
	ERROR_CHECK_FAIL = 1,
	ERROR_AREA_LOCKED = 8,
	ERROR_AREA_NOT_SUPPORTED = 7,
	ERROR_BOX_FULL = 6,
	ERROR_PET_COUNT_MAX = 5
}
Const.HOMELAND_ZONE_OP_RETURN_CODE = {
	ERROR_ZONE_UNLOCK_CONDITION_NOT_MET = 4,
	ERROR_ZONE_ALREADY_UNLOCK = 3,
	ERROR_ZONE_NOT_EXIST = 2,
	SUCCESS = 0,
	ERROR_NOT_HOME = 1,
	ERROR_AREA_NOT_UNLOCK = 6,
	ERROR_AREA_NOT_OPEN = 5
}
Const.HOMELAND_GRID_SIZE = 0.25
Const.HOME_CAMP_LIKE_INTERACT_ID = 413
Const.HOME_CAMP_VIEW_PLAYER_INTERACT_ID = 414
Const.HOME_CAMP_BUILD_INTERACT_ID = 415
Const.HOME_CAMP_MANAGE_INTERACT_ID = 416
Const.HOME_CAMP_GO_HOMELAND_INTERACT_ID = 417
Const.HOME_CAMP_CUSTOMIZE_CAR_INTERACT_ID = 418
Const.HOME_CAMP_VIEW_CAMP_BUFF = 456
Const.HOME_CAMP_CAR_INTERACT_OFFSET = {
	6.5,
	0,
	0
}
Const.HOME_WORKLOAD_ATK = {
	120,
	150,
	180,
	210
}
Const.HOME_WORKLOAD_DEF = {
	60,
	75,
	90,
	105
}
Const.HOMELAND_ORDER_OP_RETURN_CODE = {
	ERROR_ORDER_NOT_EXIST = 3,
	ERROR_DATA_VERSION = 2,
	SUCCESS = 0,
	ERROR_NOT_HOME = 1,
	ERROR_PARAM = 4,
	ERROR_MATERIAL_NOT_ENOUGH = 5
}
Const.HOMELAND_PRODUCE_OP_RETURN_CODE = {
	ERROR_PRODUCE_OPERATE = 7,
	ERROR_PRODUCE_MATERIAL_NOT_ENOUGH = 6,
	ERROR_PRODUCE_FULL = 5,
	ERROR_PRODUCE_ALREADY_START = 4,
	ERROR_PRODUCE_FORMULA_NOT_EXIST = 3,
	ERROR_PRODUCE_FACILITY_NOT_EXIST = 2,
	SUCCESS = 0,
	ERROR_NOT_HOME = 1,
	ERROR_PRODUCE_ACCELERATE_NOT_SUPPORTED = 11,
	ERROR_PRODUCE_FORMULA_LOCKED = 10,
	ERROR_HOME_LEVEL_NOT_ENOUGH = 9,
	ERROR_PRODUCE_OPERATE_EXCEPT = 8
}
Const.HOMELAND_WAREHOUSE_OP_RETURN_CODE = {
	ERROR_ITEM_BAG_FULL = 6,
	ERROR_WAREHOUSE = 5,
	ERROR_NOT_HOME = 1,
	ERROR_ITEM_NOT_ENOUGH = 3,
	SUCCESS = 0,
	ERROR_WAREHOUSE_NOT_EXIST = 2,
	ERROR_ADD_ITEM = 7,
	ERROR_ITEM_NOT_VALID = 4
}
Const.CHANGE_NAME_RETURN_CODE = {
	ERROR_NAME_NULL = 7,
	ERROR_NAME_REPEAT = 6,
	SUCCESS = 0,
	ERROR_ITEM_NOT_ENOUGH = 2,
	ERROR_NAME_CHECK_FAIL = 3,
	ERROR_NAME_FAIL = 1,
	ERROR_EXCEPTION = 5,
	ERROR_OP_TIMEOUT = 4
}
Const.HOMELAND_FACILITY_TYPE = {
	Light = 7,
	LowTemperate = 6,
	HighTemperate = 5,
	EnvRequire = 4,
	ElectricReq = 3,
	ElectricLink = 2,
	Electric = 1,
	ElectricReqSwitch = 8
}
Const.HOMELAND_ORNAMENT_LAYER = {
	Default = 1,
	None = 0,
	Ground = 2,
	Reserved = 4
}
Const.HOMELAND_MULTIPLE_MODE = {
	SpeedUp = 3,
	Normal = 0,
	Formula = 1,
	LevelUp = 2
}
Const.HOMELAND_ENV_ORNAMENT_TYPES = {
	[Const.HOMELAND_FACILITY_TYPE.ElectricReq] = true,
	[Const.HOMELAND_FACILITY_TYPE.EnvRequire] = true,
	[Const.HOMELAND_FACILITY_TYPE.ElectricReqSwitch] = true
}
Const.HOMELAND_ENV_FACILITY_TYPES = {
	[Const.HOMELAND_FACILITY_TYPE.Electric] = true,
	[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = true,
	[Const.HOMELAND_FACILITY_TYPE.HighTemperate] = true,
	[Const.HOMELAND_FACILITY_TYPE.LowTemperate] = true,
	[Const.HOMELAND_FACILITY_TYPE.Light] = true
}
Const.HOMELAND_ENV_FACILITY_RELATED_INFO = {
	[Const.HOMELAND_FACILITY_TYPE.Electric] = {
		[Const.HOMELAND_FACILITY_TYPE.ElectricReq] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricReqSwitch] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = {
		[Const.HOMELAND_FACILITY_TYPE.ElectricReq] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricReqSwitch] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.HighTemperate] = {
		[Const.HOMELAND_FACILITY_TYPE.EnvRequire] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.LowTemperate] = {
		[Const.HOMELAND_FACILITY_TYPE.EnvRequire] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.Light] = {
		[Const.HOMELAND_FACILITY_TYPE.EnvRequire] = true
	}
}
Const.HOMELAND_ENV_ORNAMENT_RELATED_INFO = {
	[Const.HOMELAND_FACILITY_TYPE.ElectricReq] = {
		[Const.HOMELAND_FACILITY_TYPE.Electric] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.ElectricReqSwitch] = {
		[Const.HOMELAND_FACILITY_TYPE.Electric] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.EnvRequire] = {
		[Const.HOMELAND_FACILITY_TYPE.HighTemperate] = true,
		[Const.HOMELAND_FACILITY_TYPE.LowTemperate] = true,
		[Const.HOMELAND_FACILITY_TYPE.Light] = true
	}
}
Const.HOMELAND_ENV_ORNAMENT_LINK_INFO = {
	[Const.HOMELAND_FACILITY_TYPE.Electric] = {
		[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = true,
		[Const.HOMELAND_FACILITY_TYPE.Electric] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricReq] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricReqSwitch] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = {
		[Const.HOMELAND_FACILITY_TYPE.Electric] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricReq] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricReqSwitch] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.ElectricReq] = {
		[Const.HOMELAND_FACILITY_TYPE.Electric] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = true
	},
	[Const.HOMELAND_FACILITY_TYPE.ElectricReqSwitch] = {
		[Const.HOMELAND_FACILITY_TYPE.Electric] = true,
		[Const.HOMELAND_FACILITY_TYPE.ElectricLink] = true
	}
}
Const.HOMELAND_FACILITY_OP_TYPE = {
	WELLCOME = 1004,
	CLEAN = 5001,
	MAX_OPER_STATE = 5000,
	SPECIAL_AI_ACTION = 1010,
	NONE = 0,
	TRANSPORT_TO_STORE = 1003,
	GOTO_TRANSPORT = 1002,
	TRANSPORT = 1001,
	MOVING = 1000
}
Const.SPECIAL_AI_ACTION_AI_EVENT_NAME = "NvidiaReviewDemoTrigger"
Const.HOME_LEISURE_TYPE = {
	PETTING = 3,
	RIDE = 2,
	WANDER = 1,
	PURE_WANDER = 4
}
Const.HOME_LEISURE_TIMEOUT = 360
Const.HOME_LEISURE_MAX_REVISION = Const.INT_MAX - 1
Const.HOMELAND_DEMO_PET_STEP_HEIGHT_UP = 2
Const.HOMELAND_DEMO_TARGET_IDS = {
	300101,
	300102,
	300103,
	300104,
	300105
}
Const.HOMELAND_DEMO_TARGET_GROUP = 3001
Const.HOMELAND_DEMO_TARGET_START = 300101
Const.HOMELAND_DEMO_TARGET_CHAT = 300102
Const.HOMELAND_DEMO_TARGET_MINE_WAIT = 300103
Const.HOMELAND_DEMO_TARGET_SHELL = 300104
Const.HOMELAND_DEMO_TARGET_END = 300105
Const.HOMELAND_DEMO_SHELL_ITEM_ID = 4001051
Const.HOMELAND_DEMO_SHELL_BUY_ORNAMENT_IDS = {
	[40600067] = true
}
Const.HOMELAND_DEMO_SHELL_BUY_ORNAMENT_PRICE = 100
Const.HOMELAND_DEMO_MINING_TIP_DIALOGUE = 7000000
Const.STORE_ORNAMENT_ID = 10400001
Const.NO_WORK_ORNAMENT_ID = -1
Const.HOMELAND_PET_ACTION_WORK_TYPE_MAP = {
	[Const.HOMELAND_FACILITY_OP_TYPE.SPECIAL_AI_ACTION] = true
}
Const.HOMELAND_IGNORE_WORK_TYPE = {
	[Const.HOMELAND_FACILITY_OP_TYPE.NONE] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.TRANSPORT] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.GOTO_TRANSPORT] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.TRANSPORT_TO_STORE] = true
}
Const.HOMELAND_NO_BREAK_WORK_TYPE = {
	[Const.HOMELAND_FACILITY_OP_TYPE.NONE] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.MOVING] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.GOTO_TRANSPORT] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.TRANSPORT] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.TRANSPORT_TO_STORE] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.WELLCOME] = true
}
Const.HOMELAND_NO_CHECK_OPERS = {
	[Const.HOMELAND_FACILITY_OP_TYPE.NONE] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.MOVING] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.GOTO_TRANSPORT] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.TRANSPORT_TO_STORE] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.WELLCOME] = true,
	[Const.HOMELAND_FACILITY_OP_TYPE.SPECIAL_AI_ACTION] = true
}
Const.HOMELAND_EXTRA_STATES = {
	OUTPUT_LIMIT = 3,
	UNDER_CONSUME = 2
}
Const.HOMELAND_KEEP_STATES = {
	Const.HOMELAND_EXTRA_STATES.OUTPUT_LIMIT
}
Const.HOMELAND_FOOD_LACK_EVENT_ID = 6
Const.HOME_MUTATION_MODE = {
	FIRST = 1,
	AUTO = 3,
	SWITCH = 2
}
Const.HOMELAND_ORNAMENT_GET_WAY = {
	BUY = 1,
	OTHER = 4,
	ACTIVITY = 3,
	REDEEM = 2
}
Const.HOMELAND_ORNAMENT_DEFAULT_MAX_PLACE_NUM = 50
Const.HOMELAND_EDITOR_CAMERA_HEIGHT_MAX_INDEX = 30
Const.HOME_OPER_REQUIRE_TYPE = {
	HomeAbility = 2,
	None = 0,
	Element = 1
}
Const.HOMELAND_CHECK_VALID_STATES = {
	Const.HOMELAND_EXTRA_STATES.UNDER_CONSUME,
	Const.HOMELAND_EXTRA_STATES.OUTPUT_LIMIT
}
Const.HOMELAND_FORMULA_TYPE = {
	SKIP_PRE_OPERATE = 2,
	Normal = 1
}
Const.HOMELAND_PRODUCE_TYPE = {
	WORKLOAD = 2,
	TIME = 1,
	ENV = 3
}
Const.HOMELAND_OPERATE_TYPE = {
	OPERATE_WORKLOAD = 2,
	FORMULA_WORKLOAD = 1,
	TIME = 3,
	ENV = 4
}
Const.HOME_EVENT_TYPE = {
	LOOSEN_GIFT = 13,
	MUTATION = 11,
	PRODUCTION = 10,
	HELP_LOOSEN = 12
}
Const.HOME_EVENT_TEXT_ID = {
	PRODUCTION = 76,
	MUTATION = 77
}
Const.HOMELAND_EDITOR_MODE = {
	PLACEMENT = 3,
	MULTIPLE = 2,
	EDITOR = 1
}
Const.HOMELAND_OPERATE_OBJECT_PLAYER_ID = 1
Const.HOMELAND_SEASON_MODULE_TYPE = {
	PARTY = 7,
	PREPARE_QUEST = 6,
	PROGRESS = 5,
	SEASON_FORMULA = 4,
	ITEM_COLLECT = 3,
	ORDER = 2,
	DAILY_QUEST = 1,
	SHOP = 8
}
Const.VIDEO_QUALITY = {
	HIGH = 3,
	MID = 2,
	LOW = 1,
	TOP = 4
}
Const.MOBILE_VIDEO_QUALITY_BASE_HEIGHT = {
	[Const.VIDEO_QUALITY.LOW] = 512,
	[Const.VIDEO_QUALITY.MID] = 580,
	[Const.VIDEO_QUALITY.HIGH] = 648,
	[Const.VIDEO_QUALITY.TOP] = 720
}
Const.MOBILE_UI_VIDEO_QUALITY_BASE_HEIGHT = {
	[Const.VIDEO_QUALITY.LOW] = 720,
	[Const.VIDEO_QUALITY.MID] = 840,
	[Const.VIDEO_QUALITY.HIGH] = 960,
	[Const.VIDEO_QUALITY.TOP] = 1080
}
Const.MOBILE_LARGE_SCREEN_VIDEO_QUALITY_BASE_HEIGHT = {
	[Const.VIDEO_QUALITY.LOW] = 720,
	[Const.VIDEO_QUALITY.MID] = 840,
	[Const.VIDEO_QUALITY.HIGH] = 960,
	[Const.VIDEO_QUALITY.TOP] = 1080
}
Const.MOBILE_LARGE_SCREEN_UI_VIDEO_QUALITY_BASE_HEIGHT = {
	[Const.VIDEO_QUALITY.LOW] = 960,
	[Const.VIDEO_QUALITY.MID] = 1080,
	[Const.VIDEO_QUALITY.HIGH] = 1248,
	[Const.VIDEO_QUALITY.TOP] = 1400
}
Const.MOBILE_RESOLUTION_SCALE = {
	[0] = 0.9,
	1,
	1.1,
	1.2
}
Const.PC_4K_WIDTH = 3840
Const.PC_4K_HEIGHT = 2160
Const.PC_2K_WIDTH = 2560
Const.PC_2K_HEIGHT = 1440
Const.HomelandEntType = {
	Pet = 2,
	Ornament = 1,
	Trash = 3
}
Const.HomeEditorErrorType = {
	Normal = 1,
	None = 4,
	OverLoad = 6,
	OverCameraHeight = 5,
	Overlap = 3,
	CrossBoundary = 2
}
Const.HomeEditorMultiSelectErrorType = {
	OverCount = 1,
	None = 0,
	OverBounds = 2
}
Const.HomelandEntSubType = {
	Normal = 1,
	FacilityVehicle = 5,
	HatchBox = 6,
	Vehicle = 3,
	Npc = 4,
	EnvObj = 2
}
Const.HomeCoinItemId = 1010
Const.HomeDecCoinItemId = 1011
Const.HomelandTrashState = {
	Recycled = 1,
	None = 0
}
Const.HomelandZoneWidth = 20
Const.HomelandZoneHeight = 15
Const.HomeEventTarget = {
	Pet = 1,
	Friend = 2
}
Const.HomeEventPetState = {
	Fight = 4,
	Sick = 3,
	Lazy = 2,
	Strike = 1
}
Const.HomeTransportThreshold = 0.6
Const.SOCIAL_TYPE = {
	FLUTE = 2,
	HORN = 1
}
Const.CATCH_OWNER_TYPE = {
	OWNER = 2,
	NONE = 1
}
Const.AOI_DISABLE_REASON = {
	SPACE_LOADING = 1,
	HIDE_SHOW_ENTITY_DIC = 2
}
Const.TEMP_POS_SYNC_REASON = {
	DEFAULT = 1,
	RIGIDBODY_NONE_KINEMATIC = 3,
	DIALOGUE_GRAPH = 2
}
Const.RESET_POS_TYPE = {
	BLACK_SCREEN = 4,
	FLOOR_HEIGHT = 3,
	ESCAPE = 2,
	REVIVE = 1,
	UNKNOWN = 0
}
Const.APPEARANCE_ACTION_PLAY_TYPE = {
	FACE_TARGET = 1,
	IN_DISTANCE = 2
}
Const.ACTIVITY_STAGE_TYPE = {
	TAB = 1
}
Const.FOLLOW_ENTER_TYPE = {
	ENTER_SINGLEWORLD_QUITE_NOT = 2,
	ENTER_LINE = 1,
	ENTER_SINGLEWORLD_DYC_NOT = 4,
	ENTER_SINGLEWORLD_NOT = 3
}
Const.CommonEnergyType_Stamina = 1009
Const.ITEM_TYPE = {
	Carry = 7,
	Currency = 99
}
Const.SHOP_LIMIT_TYPE = {
	DAY = 1,
	NONE = 0,
	WEEK = 2,
	MONTH = 3
}
Const.INTERACT_GESTURE_QUEST_ID = 3502090
Const.AIM_TARGET_QUEST_ID = 2602082
Const.Legal_App_Tip = "https://beian.miit.gov.cn/#/Integrated/recordQuery"
Const.RegionMirrorIdSuffix = "region-mirror"
Const.TOPLOGO_SHOW_TYPE = {
	NORMAL = 1,
	AFTER_HIT = 2,
	FORBID = 0
}
Const.ARK_SCREEN_TYPE = {
	MAIN = 1,
	SUB = 2
}
Const.ARK_SCREEN_CONTENT_TYPE = {
	VEDIO_ALL = 3,
	VEDIO = 2,
	PICTURE = 1,
	VEDIO_3D = 4
}
Const.TWIN_CHOICE_CUSTOM_VARIABLE_ID = 1121
Const.SPECIAL_TRAIN_BUTTERFLY_CUSTOM_VARIABLE_ID = 1165
Const.TARGET_TIMER_TYPE = {
	COUNT_DOWN = 2,
	COUNT_UP = 1
}
Const.DIALOGUE_STATE = {
	START = 0,
	COMPLETED = 2,
	IN_PROGRESS = 1
}
Const.DIALOGUE_PAUSE_NPC_INVINCIBLE_TIME = 4
Const.QTE_SRC = {
	DigEgg = 3,
	Interact = 2,
	Ability = 1
}
Const.HUD_TARGET_TYPE = {
	CHALLENGE = 72507155,
	DUNGEON = 2027,
	COURSE = 8001,
	DUNGEON_QAQ = 421
}
Const.HUD_TARGET_ADD_TYPE = {
	CATCH_PETS = 7,
	COMMON_CHALLENGE = 5,
	SCENETYPE = 4,
	TRIGGER_ID = 3,
	SANDBOX = 2,
	SCENE = 1,
	TEMP = 99
}
Const.HUD_SPECIAL_TARGET_PUPPET_HP = 1000100
Const.HUD_TARGET_CHANGE_TYPE = {
	CLOSE = 5,
	OBJECT_PROGRESS = 4,
	OBJECT = 3,
	STAGE = 2,
	IN = 1
}
Const.COURSE_TARGET_GROUP_MIN = 8001
Const.COURSE_TARGET_GROUP_MAX = 8999
Const.ROB_EGG_LOOT_TYPE = {
	BREAKABLE = 5,
	EGG_NEST = 4,
	PLAYER_BAG = 3,
	DEATH_BOX = 2,
	RESOURCE_BOX = 1,
	BOX_PUPPET = 6
}
Const.SERVER_AREANO = {
	EN = 2,
	CN = 1,
	AP = 4,
	US = 3
}
Const.SERVER_AREANO_NAME = {
	[Const.SERVER_AREANO.CN] = "cn",
	[Const.SERVER_AREANO.EN] = "en",
	[Const.SERVER_AREANO.US] = "us",
	[Const.SERVER_AREANO.AP] = "ap"
}
Const.SERVER_AREANO_DEAFULT_LANGUAGE = {
	[Const.SERVER_AREANO.CN] = "zh_CN",
	[Const.SERVER_AREANO.EN] = "en",
	[Const.SERVER_AREANO.US] = "en",
	[Const.SERVER_AREANO.AP] = "en"
}
Const.LANGUAGE_TYPE_MAP = {
	vi_VN = 5,
	ja_JP = 4,
	ko_KR = 3,
	zh_TW = 1,
	zh_CN = 0,
	en = 2,
	th_TH = 12,
	id_ID = 11,
	pt_PT = 10,
	es_ES = 9,
	fr_FR = 8,
	de_DE = 7,
	ru_RU = 6
}
Const.TIME_AREA_OFFSET = {
	[Const.SERVER_AREANO.CN] = 0,
	[Const.SERVER_AREANO.EN] = 28800,
	[Const.SERVER_AREANO.US] = 43200,
	[Const.SERVER_AREANO.AP] = 0
}
Const.TIME_AREA_OFFSET_UTCO = {
	[Const.SERVER_AREANO.CN] = 28800,
	[Const.SERVER_AREANO.EN] = 0,
	[Const.SERVER_AREANO.US] = -14400,
	[Const.SERVER_AREANO.AP] = 28800
}
Const.TIME_AREA_OFFSET_FROM_UTCO = {
	[Const.SERVER_AREANO.CN] = 8,
	[Const.SERVER_AREANO.EN] = 0,
	[Const.SERVER_AREANO.US] = -4,
	[Const.SERVER_AREANO.AP] = 8
}
Const.SERVER_TIME_ZONE_TEXT = {
	[Const.SERVER_AREANO.CN] = "",
	[Const.SERVER_AREANO.EN] = " UTC+0",
	[Const.SERVER_AREANO.US] = " UTC-4",
	[Const.SERVER_AREANO.AP] = ""
}
Const.SERVER_AREA_TYPE = {
	OVERSEAS = 2,
	CHINA_MAINLAND = 1
}
Const.ROB_EGG_HATCH_STATUS = {
	IDLE = 0,
	HATCHED = 2,
	HATCHING = 1
}
Const.ROB_EGG_TAKE_HATCHED = {
	FRIEND = 2,
	ROBBERY = 3,
	SELF = 1
}
Const.ProgressBarType = {
	TAKE_HATCHED_EGG = 2,
	ROB_HATCH_POINT = 1,
	ROB_TRANSPORT = 3
}
Const.CatchRogue = {
	SETTLE_PLAYER_DIED = 2,
	SETTLE_TIMEOUT = 1,
	PURCHASE_REVIVE = 2,
	PURCHASE_TIME = 1
}
Const.ForceUnGroundReasons = {
	Motion = 0,
	Ability = 1
}
Const.BossRushSceneId = 1070
Const.DittoDungeonSandboxId = 76696153
Const.BossRushDungeonype = {
	BOSS_RUSH_DUNGEON_PERSON = 1,
	BOSS_RUSH_DUNGEON_SINGLE_TEAM = 2
}
Const.BossRushTeleportTarget = {
	Season = "season",
	Prepare = "prepare",
	MiniGameLeft = "miniGameLeft",
	BossMid = "bossMid",
	MiniGameRight = "miniGameRight",
	BossRight = "bossRight",
	BossLeft = "bossLeft"
}
Const.BossRushTeleportTargetId = {
	[Const.BossRushTeleportTarget.Prepare] = 0,
	[Const.BossRushTeleportTarget.BossLeft] = 12,
	[Const.BossRushTeleportTarget.BossRight] = 32,
	[Const.BossRushTeleportTarget.BossMid] = 22,
	[Const.BossRushTeleportTarget.MiniGameLeft] = 11,
	[Const.BossRushTeleportTarget.MiniGameRight] = 31
}
Const.BossRushTeleportIdToTarget = {
	[0] = Const.BossRushTeleportTarget.Prepare,
	[12] = Const.BossRushTeleportTarget.BossLeft,
	[32] = Const.BossRushTeleportTarget.BossRight,
	[22] = Const.BossRushTeleportTarget.BossMid,
	[11] = Const.BossRushTeleportTarget.MiniGameLeft,
	[31] = Const.BossRushTeleportTarget.MiniGameRight
}
Const.BossRushBattlePlace = {
	Const.BossRushTeleportTarget.BossLeft,
	Const.BossRushTeleportTarget.BossMid,
	Const.BossRushTeleportTarget.BossRight
}
Const.BossRushMiniGamePlace = {
	Const.BossRushTeleportTarget.MiniGameLeft,
	Const.BossRushTeleportTarget.MiniGameRight
}
Const.BossRushPreparePlace = {
	Const.BossRushTeleportTarget.Prepare
}
Const.KV_KEY = {
	PHOTO_PRESET = 1
}
Const.KV_KEY_PREFIX = {
	[Const.KV_KEY.PHOTO_PRESET] = "photoPreset"
}
Const.PET_MOUNT_TYPE = {
	Default = 0,
	Optional = 1,
	DisablePet = 2,
	ForceWithPet = 3
}
Const.ROB_EGG_TARGET = {
	BecameEggHide = 500002,
	DefaultTarget = 500001,
	GuardEgg = 500004,
	BecameEggHunter = 500003
}
Const.ROB_EGG_RESULT = {
	Success = 0,
	Failure = 1
}
Const.ROB_EGG_TRANSPORT_STATE = {
	INVADING = 2,
	TRANSPORTING = 1,
	NORMAL = 0
}
Const.PHOTO_STUDIO_RET_CODE = {
	PARAMS_ERROR = 1004,
	NOT_ENOUGH_ITEM = 1003,
	NOT_EXIST = 1002,
	SUCCESS = 1000,
	UNLOCKED = 1001
}
Const.PHOTOGRAPHY_STUDIO_RET_CODE = {
	PHOTOGRAPHY_STUDIO_UNLOCK_ERR = 1015,
	NOT_ENOUGH_ITEM = 1001,
	SUCCESS = 1000,
	PHOTOGRAPHY_STUDIO_ACCEPT_OVER = 1014,
	PHOTOGRAPHY_STUDIO_FASHION_ERR = 1013,
	PHOTOGRAPHY_STUDIO_LEAVE_OWNER = 1012,
	PHOTOGRAPHY_STUDIO_FRIEND_OWNER = 1011,
	PHOTOGRAPHY_STUDIO_REFUSE_OWNER = 1010,
	PHOTOGRAPHY_STUDIO_ACCEPT_EXIST = 1009,
	PHOTOGRAPHY_STUDIO_INVITE_OVER = 1007,
	PHOTOGRAPHY_STUDIO_INVITE_ERROR = 1006,
	PHOTOGRAPHY_STUDIO_NOT_OWNER = 1005,
	PHOTOGRAPHY_STUDIO_CREATE_ERR = 1004,
	PHOTOGRAPHY_STUDIO_CONTENT_ERR = 1003,
	PHOTOGRAPHY_STUDIO_NOT_INFO = 1002
}
Const.PLAYER_AOI_MAX_LEVEL = 5
Const.TRAP_EVENT_TO_AOI_LEVEL = {
	[Const.TRAP_EVENT_PLAYER_AOI1] = 1,
	[Const.TRAP_EVENT_PLAYER_AOI2] = 2,
	[Const.TRAP_EVENT_PLAYER_AOI3] = 3,
	[Const.TRAP_EVENT_PLAYER_AOI4] = 4,
	[0] = Const.PLAYER_AOI_MAX_LEVEL
}
Const.COMMON_POPUP_TIP_ID = {
	BOSS_RUSH_HELP_CYCLE_BUFF = 31,
	BOSS_RUSH_HELP_SEASON = 30,
	GRAB_EGG_PROTECT_INFO = 24,
	GRAB_EGG_TALENT_INFO = 23,
	GRAB_EGG_SEASON_BOX_INFO = 22,
	GRAB_EGG_SEASON_INFO = 20,
	GRAB_EGG_WEIGHT_INFO = 19,
	PET_EXCHANGE_INFO = 15,
	ROGUE_DAILY_REWARD = 18,
	ROGUE_WEEKLY_REWARD = 12,
	ROGUE_TALENT_TREE = 11,
	ROGUE_MAIN_UP = 2,
	ROGUE_MAIN = 10,
	BOSS_RUSH_HELP_REWARD = 14,
	BOSS_RUSH_MAIN = 13,
	PHOTOGRAPH_INVITE_INFO = 41,
	BOSS_RUSH_HELP_SEASON_BUFF = 32
}
Const.HUD_NOTICE_ID = {
	BOSS_RUSH_HELP_NOTICE = 1001
}
Const.HOME_CAR_BASE_PART = {
	Color = 1,
	Wheel = 2
}
Const.HOMELAND_CAR_COMP_TYPE = {
	DNA = 8
}
Const.HOME_HATCHBOX_STATUS = {
	HATCHING = 2,
	CAN_PLACE = 1,
	INIT = 0,
	HATCHED = 3
}
Const.HOME_CAR_BOARD_NPC_ID = 990005
Const.NoFoodWorkloadRatio = 0.5
Const.EGG_SHIP_MSG_TYPE = {
	TRANS_EGG = 1,
	RETREAT = 0,
	TELEPORT = 2
}
Const.PHOTO_WORLD_LIST = {
	521
}
Const.PHOTO_WORLD_PLAYER_MAX = 100
Const.PHOTO_WORLD_DESTROY_WAIT_SECOND = 10
Const.PHOTO_SUBJECT_MASK = {
	FRIEND = 4,
	PET = 2,
	MAIN_CHAR = 1,
	NPC = 8
}
Const.UPGRADE_CHECK_FAIL_CODE = {
	NOT_ENOUGH_LEVEL = 1003,
	NOT_ENOUGH_ITEM = 1002,
	PARAMS_ERROR = 1001,
	NOT_ENOUGH_CONDITION = 1005,
	NOT_ENOUGH_ORIENTATION = 1004
}
Const.PetCulPages = {
	TALENT = 1,
	CARRY = 3,
	STARUP = 4,
	SKILL = 0,
	EVOLUTION = 2
}
Const.PetCulPageNames = {
	TALENT = "TALENT",
	CARRY = "CARRY",
	STARUP = "STARUP",
	SKILL = "SKILL",
	EVOLUTION = "EVOLUTION"
}
Const.PetCulPageIndex2Name = {
	[0] = "SKILL",
	"TALENT",
	"EVOLUTION",
	"CARRY",
	"STARUP"
}
Const.PetCulPageName2Index = {
	TALENT = 1,
	CARRY = 3,
	STARUP = 4,
	SKILL = 0,
	EVOLUTION = 2
}
Const.MAIN_SINGLEWORLD_SCENE_ID = 3000
Const.FOLLOW_SCENE_IDS = {
	3000,
	3003,
	501,
	252
}
Const.FollowGivePetError = {
	EPRR_LIMIT_EXCEED = 23,
	EPRR_PET_TYPE_FORBID = 22,
	SUCCESS = 0,
	EPRR_FRIENDSHIP_LOW = 21,
	EPRR_PET_IN_TEAM = 20,
	EPAR_FRIENDSHIP_LOW = 30,
	EPAR_PET_IN_DISPATCH = 31,
	EPRR_RECEIVER_CANNOT_GET = 26,
	EPRR_REC_LIMIT = 25,
	ERR_PET_GOT_TIMEOUT = 11,
	ERR_NOT_FOLLOW = 10,
	EPRR_PET_IN_HOME = 24
}
Const.FollowGivePetNotify = {
	[Const.FollowGivePetError.SUCCESS] = "GIVE_PET_SUCCESS",
	[Const.FollowGivePetError.ERR_NOT_FOLLOW] = "GIVE_PET_ERR_NOT_FOLLOW",
	[Const.FollowGivePetError.ERR_PET_GOT_TIMEOUT] = "GIVE_PET_ERR_PET_GOT_TIMEOUT",
	[Const.FollowGivePetError.EPRR_PET_IN_TEAM] = "GIVE_PET_EPRR_PET_IN_TEAM",
	[Const.FollowGivePetError.EPRR_FRIENDSHIP_LOW] = "GIVE_PET_EPRR_FRIENDSHIP_LOW",
	[Const.FollowGivePetError.EPRR_PET_TYPE_FORBID] = "GIVE_PET_EPRR_PET_TYPE_FORBID",
	[Const.FollowGivePetError.EPRR_LIMIT_EXCEED] = "GIVE_PET_EPRR_LIMIT_EXCEED",
	[Const.FollowGivePetError.EPRR_PET_IN_HOME] = "GIVE_PET_EPRR_PET_IN_HOME",
	[Const.FollowGivePetError.EPRR_REC_LIMIT] = "GIVE_PET_EPRR_REC_LIMIT",
	[Const.FollowGivePetError.EPRR_RECEIVER_CANNOT_GET] = "GIVE_PET_EPRR_RECEIVER_CANNOT_GET",
	[Const.FollowGivePetError.EPAR_FRIENDSHIP_LOW] = "GIVE_PET_EPAR_FRIENDSHIP_LOW",
	[Const.FollowGivePetError.EPAR_PET_IN_DISPATCH] = "DISPATCH_TASK_FORBIDDEN"
}
Const.SpaceFollowMemberState = {
	Moving = 2,
	SpecialCharacterState = 5,
	OutOfRange = 6,
	Normal = 1,
	Attach = 4,
	Away = 3
}
Const.HatchBoxLoveVfxOffset = 2.5
Const.HatchBoxLoveBubbleVfxOffset = 2.5
Const.USER_DATA_HBMSK_MAP = {
	[Const.PET_HBMSK_CATCHED] = true,
	[Const.PET_HBMSK_SHINY_CATCHED] = true,
	[Const.PET_HBMSK_RAINBOW_CATCHED] = true
}
Const.CARRY_TYPE = {
	PLAYER = 3,
	PET = 4,
	ROBEGG = 2,
	ITEM = 1
}
Const.DungeonDifficultLevel = {
	CHAOS = 6,
	NIGHTMARE = 5,
	HARD = 4,
	EASY = 2,
	NEWBIEGUIDE = 1,
	NORMAL = 3,
	PVP = 99
}
Const.RobEggEventProp = {
	FirstDropRainbow_4 = 8,
	GameTimes_99 = 7,
	GameTimes_6 = 6,
	GameTimes_5 = 5,
	GameTimes_4 = 4,
	GameTimes_3 = 3,
	FirstDigEgg = 1,
	FirstDropRainbow_5 = 9
}
Const.AttributeGroupKey = {
	Weight = 190
}
Const.BossRushSettleFunType = {
	AttackedMost = 8,
	CauseMostCure = 7,
	BearMostDamage = 6,
	KillNumMost = 5,
	AttackLast = 4,
	AttackBreakMost = 3,
	StrongestDamage = 2,
	TotalDamage = 1,
	AuxSkillMost = 10,
	AttackedLeast = 9
}
Const.LootErrCode = {
	Failure = 7,
	Success = 0,
	InvalidFunc = 11,
	SpaceErr = 10,
	NotStart = 9,
	NotOpened = 8,
	Finished = 6,
	ItemNotFound = 5,
	CanotOpen = 4,
	NotLoot = 3,
	InvalidPlayer = 2,
	AlreadyDisCovery = 1
}
Const.RobEggEvent = {
	EnterDG = 2,
	TransferEgg = 1,
	NewerGuide = 12,
	ExitDanger = 11,
	NeedKeyItem = 10,
	GetBigEgg = 9,
	LuckyMouseRefreshed = 8,
	KillLuckyMouse = 7,
	SuperEggTransfered = 6,
	SuperEggFirstControlled = 5,
	ActivateDG = 4,
	FindEgg = 3
}
Const.TransEggSrc = {
	EggShip = 1,
	Area = 3,
	Transporter = 2
}
Const.GivePetEventType = {
	SendPet = 1,
	RecPet = 2
}
Const.FollowEventType = {
	StartFollow = 1,
	ExitFollow = 2
}
Const.PlayerFollowRoleType = {
	FollowMember = 2,
	FollowLeader = 1
}
Const.SpaceFollowPendingTTL = 30
Const.SpaceFollowHandshakeExtraTTL = 15
Const.SpaceFollowPendingType = {
	InviteTo = "inviteTo",
	EstablishFrom = "establishFrom",
	ReqTo = "reqTo",
	InviteFrom = "inviteFrom",
	ReqFrom = "reqFrom"
}
Const.SpaceFollowRefuseType = {
	Require = 1,
	Invite = 0
}
Const.RobEggResTrigger = {
	Success = 1,
	Fail = 2
}
Const.CommonChallengeDelayFrame = 60
Const.RobEggUndergroundDoorType = {
	Exit = 2,
	Enter = 1
}
Const.RobEggGroupMin = 5000
Const.RobEggGroupMax = 5999
Const.DailyRewardType = {
	RobEggDailyReward = 101,
	RobEggFirstRetreat = 102
}
Const.DailyRewardStatus = {
	Rewarded = 2,
	NotFinished = 1,
	CanReward = 3
}
Const.ExitButtonType = {
	CONTINUE = 2,
	END_AND_EXIT = 1,
	READJUST = 4,
	TEMPORARY_EXIT = 3
}
Const.RogueExchangeRewardType = {
	CarryItem = 1,
	Gem = 2
}
Const.CommonItemID_SweepTicket = 1016
Const.RobEggLootType = {
	Light = 2,
	Normal = 1,
	Heavy = 3
}
Const.basePropsRate = {
	"hp_max_p",
	"atk_p",
	"def_p",
	"ep_regen_force_p",
	"def_mag_p",
	"bp_atk_p"
}
Const.MAX_FACILITY_PET_SLOTS = 4
Const.MAX_EVENT_CACHE_SIZE = 50
Const.EVENT_ASYNC = {
	dialogueGraphTeleport = 2,
	playDialogueGraph = 1
}
Const.TIDE_STATES = {
	HIGH_TIDE = 2,
	LOW_TIDE = 1,
	TIDE_DEFAULT = 1
}
Const.RobEggLuckyMouse = {
	CreationId = 102702,
	TemplateId = 11002700051,
	BuffId = {
		62102702
	}
}
Const.RobEggObMsgFilter = {
	RPC_CS_MoveRobEggItem = true,
	RPC_CS_EggShipInteract = true,
	RPC_CS_RobEggActivateDG = true,
	RPC_CS_InteractRegEggEntity = true,
	RPC_CS_ThrowItemFromRobBag = true,
	RPC_CS_StartInteract = true,
	RPC_CS_Interact = true,
	RPC_CS_OpenResourceBoxWithQTE = true,
	RPC_CS_SplitRobBagItem = true,
	RPC_CS_SplitResourceBoxItem = true
}
Const.PetHandBookConst = {
	SortingMode = {
		Default = 0,
		Species = 1,
		Min = 0,
		Max = 2
	},
	DisplayMode = {
		Max = 3,
		Species = 0,
		Min = 0,
		Cellular = 1
	}
}
Const.GAME_TIME_SCALE_MAX_VALUE = 10
Const.GAME_TIME_SCALE_REQUEST_CHECK_INTERVAL = 5
Const.GameTimeScaleType = {
	COMMON_CONFIRM = 7,
	UI = 5,
	FISSURE_INFO = 10,
	PHOTO = 11,
	TEST = 13,
	LEVEL_SCRIPT = 12,
	CUTSCENE = 4,
	FISHING_RULE_DESC = 9,
	VIDEO = 8,
	DIALOGUE_GRAPH = 1,
	RECONNECT = 6,
	DEFAULT = 0,
	FUNC_MENU_EXIT = 3,
	GUIDE = 2
}
Const.RESET_GAME_SCALE_LIST_ON_LOSE = {
	[Const.GameTimeScaleType.DIALOGUE_GRAPH] = true,
	[Const.GameTimeScaleType.GUIDE] = true,
	[Const.GameTimeScaleType.FUNC_MENU_EXIT] = true,
	[Const.GameTimeScaleType.CUTSCENE] = true,
	[Const.GameTimeScaleType.UI] = true,
	[Const.GameTimeScaleType.RECONNECT] = true,
	[Const.GameTimeScaleType.COMMON_CONFIRM] = true,
	[Const.GameTimeScaleType.VIDEO] = true,
	[Const.GameTimeScaleType.FISHING_RULE_DESC] = true,
	[Const.GameTimeScaleType.FISSURE_INFO] = true,
	[Const.GameTimeScaleType.PHOTO] = true,
	[Const.GameTimeScaleType.LEVEL_SCRIPT] = true,
	[Const.GameTimeScaleType.TEST] = true
}
Const.ShopMallTabType = {
	Tab_GiftPack = 3,
	Tab_MonthlyCard = 2,
	Tab_Rcommend = 1,
	Tab_Recharge = 7,
	Tab_Exchange = 6,
	Tab_Item = 5,
	Tab_Avater = 4
}
Const.ShopMallBuyType = {
	InApp = 0,
	Direct = 1
}
Const.ShopMallActionType = {
	Buy = 1,
	Give = 2
}
Const.ShopMallGiftpackType = {
	FreeFixed = 3,
	Select = 2,
	Fixed = 1
}
Const.RPC_ERROR_CODE = {
	SUCCESS = 0,
	FAILED = 1
}
Const.PvpMatchMode = {
	Double = 1,
	Single = 0
}
Const.RobEggGameType = {
	Dummy = 0,
	PveChaos = 5,
	Pvp = 4,
	PveNightmare = 3,
	PveHard = 2,
	PveNormal = 1
}
Const.RobEggScoreType = {
	RetreatFailure = 2,
	RetreatSuccess = 1,
	BringItemScore = 5,
	QuitRobEgg = 4,
	QuitRobEggOnlyMe = 3
}
Const.RobEggScoreName = {
	RetreatFailure = "RetreatFailure",
	RetreatSuccess = "RetreatSuccess",
	BringItemScore = "BringItemScore",
	QuitRobEgg = "QuitRobEgg",
	QuitRobEggOnlyMe = "QuitRobEggOnlyMe"
}
Const.RobEggScoreHandle = {}
Const.RobEggPerformance = {
	CarryMan = 3,
	Unstoppable = 2,
	HarvestMan = 4
}
Const.RobEggPerformanceQuality = {
	Level2 = 2,
	Level1 = 1,
	Level4 = 4,
	Level3 = 3
}
Const.CheckFixEquipRet = {
	OK = 0,
	InValid = 3,
	NoNeed = 4,
	TooHigh = 2,
	TooLow = 1
}
Const.RobEggLevelVersion = {
	VersionOBT = 20260915,
	VersionCBT3 = 20260520
}
Const.RobEggLevelVersion.CurVersion = Const.RobEggLevelVersion.VersionOBT
Const.ClientPlatformType = {
	Unknown = 0,
	Switch = 9,
	PlayStation = 8,
	Xbox = 7,
	Android = 6,
	IOS = 5,
	LinuxPlayer = 4,
	OSXPlayer = 3,
	WindowsPlayer = 2,
	Editor = 1
}
Const.PrivilegeType = {
	Give_CloudGameDays = 5,
	BpLevel_Up = 4,
	Extra_PetBox = 3,
	Hatch_Accel = 2,
	Energy_Extend = 1,
	Priv_Min = 1,
	Priv_Max = 5
}
Const.FormulaId = {
	RobEggPerformanceScoreEva6 = 1140,
	RobEggPerformanceScoreEva5 = 1139,
	RobEggPerformanceScoreEva4 = 1138,
	RobEggPerformanceScoreEva3 = 1137,
	RobEggPerformanceScoreEva2 = 1136,
	RobEggPerformanceScoreEva1 = 1135,
	RobEggPerformanceEva6 = 1134,
	RobEggPerformanceEva5 = 1133,
	RobEggPerformanceEva4 = 1132,
	RobEggPerformanceEva3 = 1131,
	RobEggPerformanceEva2 = 1130,
	RobEggPerformanceEva1 = 1129,
	RobEggRepairKitPrice = 1122,
	RobEggEquipPrice = 1121,
	CampCarPetComfort = 6010
}
Const.PetTransmogSlotType = {
	Max = 5,
	Color = 1,
	Hair = 4,
	Body = 3,
	Wing = 2,
	Flash = 5
}
Const.ErrInheritPetType = {
	EPRR_PET_IN_TEAM = 1,
	EPRR_PET_NOT_EXIST = 0,
	EPRR_PET_TYPE_FORBID = 2,
	EPRR_PET_SAME = 5
}
Const.PetTransmogCustomDefultSchemeIndex = 1
Const.HatchSpeedUpReason = {
	monthcard = 2,
	activty_petHatch = 1,
	stroke = 4,
	item = 3
}
Const.CMD_SOCKET_ERROR = {
	PARSE = 1001,
	INTERNAL = 1000,
	PARAM = 1004,
	AUTH = 1003,
	UNKNOWN_CMD = 1002
}
Const.SocialPartyOp = {
	EXECUTE = 3,
	POPUP_REC = 2,
	USE_ACTION = 1
}
Const.BehaviorType = {
	NONE = 0,
	FOLLOW = 2,
	SNUGGLE = 1
}
Const.SocialPartyPetAi = {
	TOAST_VARIANT_COUNT = 3,
	DEFAULT_CD = 60,
	MIN_GROUP_SIZE = 2,
	DEFAULT_BEHAVIOR_MAX = {
		[Const.BehaviorType.SNUGGLE] = 2,
		[Const.BehaviorType.FOLLOW] = 4
	}
}
Const.WORLD_FURNITURE = {
	CAN_PLACE_FURNITURE = 1
}
Const.SocialPartyLevelLimit = 30
Const.PlayerGhostIdSuffix = "ghost"
Const.PetGhostIdSuffix = "petGhost"
Const.COMPONENT_VOXEL = 0
Const.COMPONENT_INDEX_MODEL = 1
Const.COMPONENT_INDEX_ANIMATOR = 2
Const.COMPONENT_AUTO_PATH_FIND = 3
Const.COMPONENT_RVO = 4
Const.COMPONENT_INDEX_CHARACETER_CONTROLLER = 5
Const.COMPONENT_INDEX_PX_LISTENER = 6
Const.COMPONENT_INDEX_MONO_DEBUG = 7
Const.COMPONENT_INDEX_EFFECT = 8
Const.COMPONENT_INDEX_LUA = 9
Const.COMPONENT_INDEX_AUDIO = 10
Const.COMPONENT_INDEX_FOLLOW = 11
Const.COMPONENT_INDEX_ENT_BIND = 12
Const.COMPONENT_INDEX_MAIN_PLAYER = 13
Const.COMPONENT_ASSET_CACHE = 14
Const.COMPONENT_IDX_PLAYABLE = 15
Const.COMPONENT_LOCAL_WEATHER = 16
Const.COMPONENT_POS_SYNC = 18
Const.COMPONENT_ANIMATION_SYNC = 19
Const.COMPONENT_IDX_PHYSX = 20
Const.COMPONENT_IDX_ITEM = 21
Const.COMPONENT_MOTION = 22
Const.COMPONENT_CHEM_MATERIAL = 23
Const.COMPONENT_MAGNESIS_CONTROLLER = 24
Const.COMPONENT_MOUNT = 25
Const.COMPONENT_CATCH = 26
Const.COMPONENT_AI_CONTROLLER = 27
Const.COMPONENT_INDEX_SHADOW = 29
Const.COMPONENT_SIMPLE_MOVEMENT = 30
Const.COMPONENT_DIALOGUE = 31
Const.COMPONENT_AREA_HANDLER = 32
Const.COMPONENT_ECS = 33
Const.COMPONENT_FOLLOW_OTHER = 34
Const.COMPONENT_PHYSIC_CONTROLLER = 35
Const.COMPONENT_ATTACH = 62
Const.COMPONENT_INDEX_IK = 63
Const.COMPONENT_COUNT = 64
Const.AgentTransformReasonConst = {
	LogicFromLua = 8,
	TeleportFromLua = 7
}
Const.RiftState = {
	Win = 1,
	None = 0,
	Got = 2
}
Const.MotionDisableReason = {
	Authority = 1,
	ReasonNone = 0
}
Const.EntityControllerType = {
	Dialogue = 2,
	Player = 0,
	AI = 1
}
Const.KccDisableReason = {
	StaticSpawn = 128,
	PlayableInit = 64,
	AIRawRootMotion = 32,
	PetBall = 16,
	Skilling = 4,
	SandBoxLoading = 2,
	SceneLoading = 1,
	Authority = 8,
	ReasonNone = 0
}
Const.KccControlType = {
	ControlNone = 0,
	InCombat = 256,
	ForceDisplacementControl = 1024,
	PetControl = 4,
	ClimbControl = 128,
	SneakControl = 64,
	SkillControl = 32,
	Trampoline = 16,
	AIRootMotion = 8,
	BossControl = 2,
	PlayerControl = 1
}
Const.RecycleGameObjectType = {
	SetUIViewVisible = 5,
	SetUIViewInVisible = 4,
	SetZeroPos = 3,
	SetFarAway = 2,
	EnableGo = 1,
	DisableGo = 0
}
Const.DisplacementVelocitySource = {
	ControllerFollowTarget = 10,
	SkillHitDisplacement = 9,
	KnockUp = 8,
	KnockBack = 7,
	AppearDash = 6,
	ReboundDash = 5,
	FollowTarget = 4,
	ForceDisplacement = 3,
	Scroll = 2,
	MoveByDirection = 1,
	MoveByInput = 0
}
Const.MARKER_SETTINGS = {
	DEFAULT = 0,
	OTHER_HIDE = 2,
	SELF_HIDE = 1,
	STRANGER_HIDE = 3
}
Const.ROB_EGG_REFRESH_STATUS = {
	STAGE_3 = 3,
	STAGE_2 = 2,
	STAGE_1 = 1,
	NORMAL = 0
}
Const.DiscordInviteType = {
	FriendInvite = 1,
	TeamInvite = 2
}
Const.COUNTRY_LANGUAGES_CODE = {
	FR_FR = "fr-FR",
	PT_PT = "pt-PT",
	CN_TW = "cmn-Hant-TW",
	ES_ES = "es-ES",
	IT_IT = "it-IT",
	GD_HK = "yue-Hant-HK",
	EN_US = "en-US",
	CN_HK = "cmn-Hans-HK",
	IT = "it-IT",
	RU_RU = "ru-RU",
	ES = "es-ES",
	EN_GB = "en-GB",
	PH = "fil-PH",
	CN = "cmn-Hans-CN",
	PT = "pt-PT",
	JA_JP = "ja-JP",
	FR = "fr-FR",
	KO_KR = "ko-KR",
	RU = "ru-RU",
	JP = "ja-JP",
	KR = "ko-KR",
	TW = "cmn-Hant-TW",
	TH_TH = "th-TH",
	ID_ID = "id-ID",
	DE_DE = "de-DE",
	VI_VN = "vi-VN",
	FIL_PH = "fil-PH"
}
Const.GLOBAL_SERVER_AREA_NO = 2
Const.ENABLE_BLOCK_ADVENTURE = false

return Const
